Unstructured-IO/unstructured

- README.md
Adds an explicit link to the security policy in the`README` for the repo.
> docs: Link to security policy in the README

- .github/dependabot.yml
Addresses [CORE-53](https://unstructured-ai.atlassian.net/browse/CORE-53). Configures dependabot scans for the repo. Dependabot is set up to check for `pip-compile` and GitHub actions updates once a week.
> build: Configure dependabot scan

- .github/dependabot.yml
Fixes [this build failure](https://github.com/Unstructured-IO/unstructured/runs/8577828844). Corrects the ecosystem name by updating it to `pip` from `pip-compile`.
> fix: Change the Dependabot ecosystem from pip-compile to pip

- CHANGELOG.md
- docs/source/bricks.rst
- test_unstructured/staging/test_label_studio.py
- unstructured/__version__.py
- unstructured/staging/label_studio.py
Addresses CORE-253. Added `text_field` and `id_field` to `stage_for_label_studio` signature, to allow user to specify the keys in the resulting JSON. Includes tests and update to example in sphinx docs.
```python
from unstructured.staging.label_studio import stage_for_label_studio
from unstructured.documents.elements import NarrativeText, Title
elements = [Title(text="Title 1"), NarrativeText(text="Narrative 1")]
print(stage_for_label_studio(elements, text_field="i_love_text", id_field="i_love_ids"))
```
> feat: Add text_field and id_field to stage_for_label_studio signature

- CHANGELOG.md
- docs/source/bricks.rst
- prodigy.json
- test_unstructured/staging/test_prodigy.py
- unstructured/staging/prodigy.py
Resolves https://github.com/Unstructured-IO/community-tasks/issues/1
Summary of changes:
Example:
```python
import json
from unstructured.documents.elements import Title, NarrativeText
from unstructured.staging.prodigy import stage_for_prodigy
elements = [Title(text="Title"), NarrativeText(text="Narrative")]
metadata = [{"type": "title"}, {"type": "text"}]
prodigy_data = stage_for_prodigy(elements, metadata)
with open("prodigy.json", "w") as f:
json.dump(prodigy_data, f, indent=4)
```
> feat: Implement stage_for_prodigy brick

- CHANGELOG.md
- docs/source/bricks.rst
- test_unstructured/staging/test_prodigy.py
- unstructured/__version__.py
- unstructured/staging/prodigy.py
Resolves https://github.com/Unstructured-IO/community-tasks/issues/3
**Summary of changes:**
> feat: Implement `stage_csv_for_prodigy` brick

- CHANGELOG.md
- docs/source/bricks.rst
- docs/source/conf.py
- test_unstructured/staging/test_label_studio.py
- unstructured/__version__.py
- unstructured/staging/label_studio.py
Adds an optional `annotation` kwarg to the `stage_for_label_studio` function that uploads annotations along with the training examples. If `annotations` is specified, it must be the same length as `elements`. `annotations` is a list of lists, each element can have a list of annotations. If a given element does not have any annotations, use an empty list.
Install LabelStudio in a virtual environment and then run `label-studio` to start it.
```python
import json
from unstructured.documents.elements import NarrativeText
import unstructured.staging.label_studio as label_studio
element = NarrativeText(text="A big brown bear")
annotations = [
label_studio.LabelStudioAnnotation(
result=[
label_studio.LabelStudioResult(
type="choices",
value={"choices": ["Positive"]},
from_name="sentiment", …
```
> feat: Optionally include LabelStudio annotations in staging brick

- docs/source/examples.rst
Updates the documentation to include an example of how to use `stage_for_label_studio` to create a sentiment analysis task in LabelStudio.
Ensure that the instructions work through both the UI and the API.
> docs: Add example LabelStudio sentiment analysis example

- CHANGELOG.md
- docs/source/bricks.rst
- test_unstructured/staging/test_base_staging.py
- unstructured/__version__.py
- unstructured/documents/elements.py
- unstructured/staging/base.py
Adds a helper function to convert ISD dictionaries to a list of `Text` elements. Also corrects the category name and doc string for the `ListItem` element. Bumped the version to `0.2.1` and will push a release after this merge.
```python
from unstructured.staging.base import isd_to_elements
isd = [
{"text": "My Title", "type": "Title"},
{"text": "My Narrative", "type": "NarrativeText"}
]
elements = isd_to_elements(isd)
```
> feat: Adds a helper function to convert ISD dicts to elements

- CHANGELOG.md
- docs/source/bricks.rst
- test_unstructured/staging/test_datasaur.py
- unstructured/__version__.py
- unstructured/staging/datasaur.py
In this pull request I add staging bick for Datasaur.
Changed files:
- unstructured/staging/datasaur.py
- docs/source/bricks.rst 
Definition of Done:
Was added a staging brick with this signature:
```
stage_for_datasaur(  elements: List[Text] ) -> List[Dict[str, Any]]:
```
Formats a list of ``Text`` elements as input to token based tasks in Datasaur, the output has
the next format:  
```
[
{
"text": "The new series Narcos created by Chris Brancato , Eric Newman and Carlo Bernard , represents a pretty ambitious step for Netflix .",
"entities": []
}, ...
]
```
Example of usage:
```
from unstructured.staging.datasaur import stage_for_datasaur
input  = [Text("Text1"),Text("Text2")]
output = stage_for_datasaur(input)
```
> feat: Add staging brick for Datasaur token-based tasks

- CHANGELOG.md
- setup.py
- unstructured/__version__.py
Adds `long_description_content_type` to `setup.py` to ensure the `README` renders properly. Bumps the version so we can publish the long description updates to PyPI.
> chore: Add long description content type; bump version

- README.md
Changes the image `src` to an absolute link so it will render properly in the PyPI long description. Currently, the image doesn't appear, as shown below:
> fix: Change the image src to an absolute link

- README.md
Adds a developer quick start section to the README, following the same format as in `pipeline-sec-filings`.
> docs: Add developer quick start section

- CHANGELOG.md
- README.md
- docs/source/bricks.rst
- test_unstructured/cleaners/test_core.py
- unstructured/__version__.py
- unstructured/cleaners/core.py
- Adds a `clean_prefix` brick from removing prefixes
- Adds a `clean_postfix` brick for removing postfixes
```python
from unstructured.cleaners.core import clean_prefix
text = "SUMMARY: This is the best summary of all time!"
clean_prefix(text, r"(SUMMARY|DESCRIPTION):", ignore_case=True)
```
```python
from unstructured.cleaners.core import clean_postfix
text = "The end! END"
clean_postfix(text, r"(END|STOP)", ignore_case=True)
```
> feat: Cleaning bricks for removing prefixes and postfixes

- CHANGELOG.md
- docs/source/bricks.rst
- test_unstructured/cleaners/test_extract.py
- unstructured/__version__.py
- unstructured/cleaners/extract.py
- Adds a cleaning brick to extract text before a pattern
- Adds a cleaning brick to extract text after a pattern
- Bumps to `0.2.3` to support using these cleaning bricks in the OER pipeline
```python
from unstructured.cleaners.extract import extract_text_before
text = "Here I am! STOP Look at me! STOP I'm flying! STOP"
extract_text_before(text, r"STOP")
```
```python
from unstructured.cleaners.extract import extract_text_after
text = "SPEAKER 1: Look at me, I'm flying!"
extract_text_after(text, r"SPEAKER \d{1}:")
```
> feat: Cleaning bricks to extract text before/after a pattern

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/documents/html.py
- unstructured/logger.py
- unstructured/models/layout/detectron2.py
- unstructured/nlp/partition.py
- unstructured/nlp/patterns.py
- unstructured/nlp/tokenize.py
Addresses https://github.com/Unstructured-IO/unstructured/issues/57 that support an alternative way of importing `Final` if the python version is less than 3.8.
Will publish `unstructured` to version `0.2.4` once merged.
> feat: `Final` Compatibility with Python 3.7

- CHANGELOG.md
- Makefile
- test_unstructured/documents/test_base.py
- unstructured/__version__.py
- unstructured/documents/base.py
- unstructured/documents/xml.py
Changed where `_read` sits in the inheritance structure since `PDFDocument` doesn't really need lazy document processing and it was causing a typing issue with the new version of `mypy`.
- In `requirements/test.txt`, change the `mypy` version to 0.990
- In your `unstructured` environment, run `pip install -r requirements/test.txt`
- run `make check`
- There should be no errors
> fix: fix abstract class

- CHANGELOG.md
- unstructured/partition/pdf.py
- raise ValueError for bad responses in `partition_pdf`
- remove unused dependency Text from imports
> fix: partition pdf bad responses

- CHANGELOG.md
- docs/source/bricks.rst
- test_unstructured/staging/test_argilla.py
- unstructured/__version__.py
- unstructured/staging/argilla.py
Closes Unstructured-IO/community#27 and Unstructured-IO/community#28. Adds support for `text2text` and `token_classification` tasks to the `stage_for_argilla` brick. For token classification tasks, if `tokens` is not specified as an optional kwarg, then the `nltk` word tokenizer is used by default.
```python
import json
from unstructured.documents.elements import Title, NarrativeText
from unstructured.staging.argilla import stage_for_argilla
elements = [Title(text="Title"), NarrativeText(text="Narrative")]
metadata = [{"type": "title"}, {"type": "text"}]
argilla_dataset = stage_for_argilla(elements, "token_classification", metadata=metadata)
```
```python
import json
from unstructured.documents.elements import Title, NarrativeText
from unstructured.staging.argilla import stage_for_argilla …
```
> feat: text2text and token classification for argilla

- CHANGELOG.md
- test_unstructured/partition/test_pdf.py
- unstructured/__version__.py
- unstructured/partition/pdf.py
- Updates the `partition_pdf` tests to use mock API calls instead of calling the live API.
- Expands `partition_pdf` tests to achieve 100% test coverage
`make test` should work with the updated tests and show 100% coverage
> test: mock model api calls; full coverage for partition_pdf

- unstructured/partition/pdf.py
In cases where the `types-requests` package was installed, `mypy` would throw an error on the `files` argument of `requests.post` in `unstructured/partition/pdf.py`. This PR fixes that without any functional change to the code by providing a type hint to the argument passed to `requests.post`.
Verify the error from the `main` branch by installing `types-requests` in your environment and running `make check`.
Verify the fix from this branch in the same manner. With `types-requests` installed, `make check` should find no errors.
> chore: add type hint to requests.post arg

- requirements/test.in
- requirements/test.txt
Bumps and pins the `certifi` version to address vulnerabilities from the dependabot scans.
> build(deps): Bump certifi to address security scans

- CHANGELOG.md
- unstructured/__version__.py
- Add `__init__.py` to the `partition` module so it can be imported.
> fix: add __init__.py to the partition module

- CHANGELOG.md
- Makefile
- docs/source/bricks.rst
- requirements/huggingface.txt
- setup.py
- test_unstructured/cleaners/test_translate.py
- unstructured/__version__.py
- unstructured/cleaners/translate.py
Adds a `translate_text` cleaning brick for translating content between languages. Uses the [Helsinki NLP](https://huggingface.co/Helsinki-NLP) models from `transformers` for translation. If the source language is not specified, the language is detected with `langdetect`.
```python
from unstructured.cleaners.translate import translate_text
translate_text("Ich bin ein Berliner!")
translate_text("Я тоже можно переводать русский язык!", "ru", "en")
```
> feat: `translate_text` cleaning brick

- CHANGELOG.md
- docs/source/elements.rst
- test_unstructured/documents/test_elements.py
- unstructured/__version__.py
- unstructured/documents/elements.py
Adds an `apply` method to `Text` elements to make it easier to apply cleaning bricks after partitioning. Previously, users would need to either create a new element or modify the text element in place to apply a cleaning brick. The `apply` method accepts either a single cleaner or a list of cleaners.
```python
from functools import partial
from unstructured.cleaners.core import clean_prefix
from unstructured.cleaners.translate import translate_text
from unstructured.documents.elements import ListItem
cleaners = [
partial(clean_prefix, pattern=r"\[\d{1,2}\]"),
partial(translate_text, target_lang="ru"),
]
item = ListItem(text="[1] A Textbook on Crocodile Habitats")
item.apply(*cleaners)
print(item)
```
> feat: `apply` method to apply cleaning bricks to elements

- CHANGELOG.md
- README.md
- docs/source/bricks.rst
- example-docs/fake-email.eml
- test_unstructured/cleaners/test_core.py
- test_unstructured/partition/test_email.py
- unstructured/__version__.py
- unstructured/cleaners/core.py
- unstructured/documents/html.py
- unstructured/partition/email.py
- Adds a `partition_email` cleaning brick that process the `text/html` content from emails
- Adds a `replace_mime_encodings` cleaning brick for cleaning encodings from emails
- Makes a small fix to the current HTML code so that list items with embedded spans and paragraphs are processed correctly.
```python
elements = partition_email(filename="example-docs/fake-email.eml")
with open("example-docs/fake-email.eml", "r") as f:
elements = partition_email(file=f)
with open("example-docs/fake-email.eml", "r") as f:
text = f.read()
elements = partition_email(text=text)
```
> feat: add `partition_email` cleaning brick

- docs/requirements.txt
- requirements/base.txt
- requirements/build.in
- requirements/build.txt
- requirements/huggingface.txt
- setup.py
Bumps and pins the `certify` version to incorporate security patches in version `2022.12.07`.
> build(deps): bump `certify` to incorporate security patches

- CHANGELOG.md
- unstructured/__version__.py
Bump library to `0.3.3` and will be published later.
> doc: bump to newer version

- CHANGELOG.md
- test_unstructured/documents/test_html.py
- unstructured/__version__.py
- unstructured/documents/html.py
Fixes an issue with `partition_html` that caused `div` tags that were both containers and included to text to be skipped. For example:
```html
<div>My name is Matt
<div>This is my message</div>
</div>
```
would previously include `This is my message` but not `My name is Matt`. With the fix, all of the text is included.
Using the sample doc from the `pipeline-email` repo:
```python
filename = "sample-docs/family_day.eml"
elements = partition_email(filename=filename)
print("\n\n".join([str(el) for el in elements]))
```
The output should look like:
```python
Hi All,
Get excited for our first annual family day!
They'll be face painting, a petting zoo, funnel cake and more.
Make sure to RSVP!
Best.
Mallori Harrell
Unstructured …
```
> fix: `partition_html` should process container divs that include text

- CHANGELOG.md
- docs/source/bricks.rst
- test_unstructured/cleaners/test_extract.py
- test_unstructured/partition/test_text_type.py
- unstructured/__version__.py
- unstructured/cleaners/extract.py
- unstructured/nlp/patterns.py
- unstructured/partition/text_type.py
Adds a `contains_phone_number` function to identify if a section of text contains a phone number and an `extract_phone_number` cleaning brick for extracting the phone numbers.
```python
from unstructured.cleaners.extract import extract_phone_number
extract_phone_number("Phone number: 215-867-5309")
```
```python
from unstructured.partition.text_type import contains_phone_number
contains_phone_number("Phone number: 215-867-5309")
```
> feat: helper functions to identify and extract phone numbers

- CHANGELOG.md
- docs/source/bricks.rst
- test_unstructured/partition/test_docx.py
- unstructured/__version__.py
- unstructured/partition/docx.py
Adds a `partition_docx` partitioning brick with basic `.docx` parsing. This should be considered a starting point for `.docx` parsing that we will continue to refine over time.
```python
import docx
from unstructured.partition.docx import partition_docx
document = docx.Document()
document.add_paragraph("Important Analysis", style="Heading 1")
document.add_paragraph("Here is my first thought.", style="Body Text")
document.add_paragraph("Here is my second thought.", style="Normal")
document.save("mydoc.docx")
elements = partition_docx(filename="mydoc.docx")
with open("mydoc.docx", "rb") as f:
elements = partition_docx(file=f)
```
> feat: add `partition_docx` for Word documents

- CHANGELOG.md
- README.md
- docs/source/bricks.rst
- test_unstructured/partition/test_auto.py
- test_unstructured/partition/test_text.py
- unstructured/__version__.py
- unstructured/partition/auto.py
Adds support for processing `.txt` files in the automatic `partition` brick.
Most of the doc updates in the diffs are automatic extra whitespace removal.
```python
from unstructured.partition.text import partition_text
elements1 = partition("example-docs/fake-text.txt")
elements2 = partition_text("example-docs/fake-text.txt")
elements1 == elements2
```
> feat: add support for `.txt` files in `partition`

- CHANGELOG.md
- setup.py
- unstructured/__version__.py
Bumps `unstructured-inference` to pull in an `opencv-dependency` pin that is required to install `unstructured` on Linux.
> build(deps): bump `unstructured_inference` version range

- CHANGELOG.md
- test_unstructured/partition/test_text_type.py
- unstructured/__version__.py
- unstructured/partition/text_type.py
Closes #159. Fixes a divide by zero error that occurs in `exceeds_cap_ratio` if the input is empty.
The following should return `False`.
```python
from unstructured.partition.text_type import exceeds_cap_ratio
exceeds_cap_ratio("")
```
> fix: avoid divide by zero in `exceeds_cap_ratio`

- CHANGELOG.md
- example-docs/fake-email-header.eml
- test_unstructured/partition/test_email.py
- unstructured/__version__.py
- unstructured/documents/email_elements.py
- unstructured/partition/email.py
The `_parse_received_data` function current returns `None` when the `datetimestamp` variable is set. This PR fixes this bug.
> chore: Fix parse received data

- CHANGELOG.md
- test_unstructured/file_utils/test_filetype.py
- unstructured/__version__.py
- unstructured/file_utils/filetype.py
Updates `detect_filetype` to properly handle older Office filetypes such as `.doc`, `.ppt`, and `.xls`. Previous these were detected as `.docx`, `.pptx`, and `.xlsx`.
Run `detect_filetype` on `.doc`, `.ppt`, and `.xls` files and verify that the outputs are correct.
> fix: update `detect_filetype` to properly handle older office files

- CHANGELOG.md
- test_unstructured/partition/test_common.py
- unstructured/__version__.py
- unstructured/nlp/patterns.py
- unstructured/partition/common.py
- unstructured/partition/pdf.py
Closes #163. Adds the ability to split lists that are detected in LayoutParse with the List type instead of treating them as a single block of text.
The following should now show `ListItem` objects in `elements` after the document is parsed.
```python
filename = "example-docs/layout-parser-paper-fast.pdf"
elements = partition(filename=filename)
```
> feat: add ability to parse `LayoutElement` lists

- README.md
Adds links to the community Slack and our LinkedIn page to the README.
Click the links to make sure they work.
> docs: add links to linkedin and slack

- CHANGELOG.md
- test_unstructured/file_utils/test_filetype.py
- unstructured/__version__.py
- unstructured/file_utils/filetype.py
Updates `detect_filetype` to properly detect `.xml` and `.html` files on Amazon Linux systems. On Amazon linux, the MIME type is `application/xml` instead of `text/xml`. The logic now treats any MIME type that ends in `.xml` as an XML file. Also updates the tests to account for different operating systems potentially returning different MIME types from buffer.
Tests pass on an Amazon Linux instance.
> fix: handle xml filetype detection on amazon linux

- CHANGELOG.md
- test_unstructured/partition/test_auto.py
- unstructured/__version__.py
- unstructured/partition/pdf.py
Closes #174. Suppresses the `UserWarning` when `partition_pdf` is called. Also fixes up a few of the PDF tests in `test_auto.py`.
The following should no longer output a warning
```python
filename = "example-docs/layout-parser-paper-fast.pdf"
partition(filename=filename)
```
> fix: no `UserWarning` when `partition_pdf` is called

- CHANGELOG.md
- Makefile
- docs/source/bricks.rst
- test_unstructured/partition/test_text_type.py
- unstructured/__version__.py
- unstructured/nlp/english_words.py
- unstructured/partition/text_type.py
Adds a check that requires narrative text and titles to have at least one English words. Prevents office symbols like `ASDF-JQL` and similar items from being flagged as titles.
```python
from unstructured.partition.text_type import is_possible_narrative_text, is_possible_title
is_possible_title("PARROT BEAK") # should be True
is_possible_title("ASDF-JQL") # should be False
is_possible_narrative_text("The parrot is squawking!") # should be True
is_possible_narrative_text("ASDJ JQL; QWER. TUSP AHSAD.") # should be False
```
> fix: titles and narrative text need at least one english word

- CHANGELOG.md
- docs/source/bricks.rst
- test_unstructured/partition/test_text_type.py
- unstructured/__version__.py
- unstructured/partition/text_type.py
Adds a max word length for titles to avoid long text with title-like characteristics from getting categorized as text. Users can use the `title_max_word_length` kwarg in `is_possible_title` or the `UNSTRUCTURED_TITLE_MAX_WORD_LENGTH` env var control this setting. Also added an `UNSTRUCTURED_` prefix to the narrative text caps threshold environment variable.
The following should return `False` for `is_possible_title`. Previously it returned `True`.
```python
from unstructured.partition.text_type import is_possible_title
is_possible_title("The box contains: 5 GOLDEN RINGS, 4 CALLING BIRDS, 3 FRENCH HENS, 2 TURTLE DOVES AND A PARTRIDGE IN A PEAR TREE")
```
> feat: set a user controlled max word length for titles

- CHANGELOG.md
- docs/source/bricks.rst
- setup.py
- test_unstructured/partition/test_text_type.py
- unstructured/__version__.py
- unstructured/nlp/english_words.py
- unstructured/partition/text_type.py
Adds a broader list of English words and also splits on punctuation during the English word check to capture titles that a "jammed together" like `1.A.RISKS`. Also updated the default non-alpha threshold since it was a little too aggressive.
The following should return `True`. It currently returns `False` on `main`.
```python
from unstructured.partition.text_type import is_possible_title
is_possible_title("1.A.RISKS")
```
Also run `make install &&  python setup.py install` and confirm that `english-words.txt` is present at `~/.pyenv/versions/3.8.13/envs/english_words/lib/python3.8/site-packages/unstructured-0.4.5.dev5-py3.8.egg/unstructured/nlp`
> fix: more english words; split on punctuation

- CHANGELOG.md
- test_unstructured/partition/test_pptx.py
- unstructured/__version__.py
- unstructured/partition/pptx.py
Orders the elements extracted from `.pptx` files based on their position on the page. Proceeds from top to bottom and left to right. Previously the elements were not in the correct order.
Run the following using the filename Matt provides you. The outputs should go top to bottom and left to right based on the position of the shapes.
```python
partition(filename=filename)
```
> fix: preserve the order of shapes in `partition_pptx` output

- CHANGELOG.md
- requirements/test.in
- requirements/test.txt
- test_unstructured/partition/test_html_partition.py
- unstructured/__version__.py
- unstructured/partition/html.py
Adds the ability to pass a URL into the `partition_html` function. Will raise an error if the status code is bad, or if the content type is not `text/html`.
```python
elements = partition_html(url="https://www.understandingwar.org/backgrounder/russian-offensive-campaign-update-february-5-2023")
```
> feat: `partition_html` directly from a url

- README.md
Colab Notebooks have been moved and updated. This PR updates the link for [`Unstructured_Quick_Tour.ipynb`](https://colab.research.google.com/drive/1U8VCjY2-x8c6y5TYMbSFtQGlQVFHCVIW) in the README.md
> docs: update the link for colab notebook

- CHANGELOG.md
- docs/source/bricks.rst
- test_unstructured/partition/test_auto.py
- test_unstructured/partition/test_html_partition.py
- test_unstructured/partition/test_image.py
- test_unstructured/partition/test_pdf.py
- test_unstructured/partition/test_pptx.py
- unstructured/__version__.py
- unstructured/documents/elements.py
- unstructured/partition/__init__.py
- unstructured/partition/auto.py
- unstructured/partition/common.py
- unstructured/partition/docx.py
- unstructured/partition/html.py
- unstructured/partition/image.py
- unstructured/partition/pdf.py
- unstructured/partition/pptx.py
Adds a `include_page_breaks` kwarg to optionally add page breaks for filetypes that support it (`.pptx`, `.pdf`, `.html` and images). This is especially helpful for documents like `.pptx` where content doesn't naturally flow from slide to slide. `include_page_breaks` defaults to `False` for backward compatibility. Note, `.docx` does not support paging due to the behavior described in [this SO post](https://stackoverflow.com/questions/36193159/page-number-python-docx). Page breaks are created by the renderer as opposed to the `.docx` source files.
Run the following code. You should see `PageBreak` in `elements`.
```python
filename = "example-docs/layout-parser-paper-fast.pdf"
elements = partition(filename=filename, include_page_breaks=True) …
```
> feat: optional page breaks for `.pptx`, `.pdf`, `.html` and images

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/partition/html.py
Removes the response text from the exception if the HTML status code is an error. The error message is too long if it's a 404 html page. Also bumps the version for the `0.4.7` release.
> fix: remove response text when the HTML status code is an error

- README.md
Added information about OS dependencies `poppler` and `tesseract`.
> docs: add info about os dependencies

- README.md
Update suggested make targets for installation in README, and also add suggestion about using `make install-local-inference`.
> docs: update make targets

- CHANGELOG.md
- docs/source/bricks.rst
- unstructured/__version__.py
- unstructured/partition/image.py
- unstructured/partition/pdf.py
Updates `partition_pdf` and `partition_image` to use local inference by default since the hosted model inference endpoint is no longer running and most of our users are running inference locally.
The following snippets should run in local inference mode (if they run at all at the moment, that means the changes work).
```python
elements = partition_pdf("example-docs/layout-parser-paper-fast.pdf")
```
> chore: default to local inference for `partition_pdf` and `partition_image`

- CHANGELOG.md
- docs/source/bricks.rst
- test_unstructured/partition/test_text_type.py
- unstructured/__version__.py
- unstructured/partition/text_type.py
Adds the ability to skip English language specific text type checks by setting the `UNSTRUCTURED_LANGUAGE` environment variable to `""` or by setting the `language` kwarg to `""`.
```python
from unstructured.partition.text_type import is_possible_narrative_text, is_possible_title
text = "Я говорю по-русски. Вы тоже?"
is_possible_narrative_text(text, language="en") # should be False
is_possible_narrative_text(text, language="") # should be True
text = "Риски"
is_possible_narrative_text(text, language="en") # should be False
is_possible_narrative_text(text, language="") # should be False
is_possible_title(text, language="en") # should be False
is_possible_title(text, language="") # should be True
```
> feat: ability to skip English language specific checks with env var

- CHANGELOG.md
- test_unstructured/staging/test_base_staging.py
- unstructured/__version__.py
- unstructured/documents/elements.py
Closes #232. Ensures ISD dictionaries are JSON serializable when the filename is a `Path` object.
The following code should work. Previously you'd get a `JSONDecode` error.
```python
import pathlib
import json
from unstructured.documents.elements import ElementMetadata, Title, NarrativeText
from unstructured.staging.base import convert_to_isd
metadata = ElementMetadata(filename=pathlib.PosixPath("../../fake-file.txt"))
elements = [
Title(text="Title 1", metadata=metadata),
NarrativeText(text="Narrative 1", metadata=metadata),
]
output = convert_to_isd(elements)
json.dumps(output)
```
> fix: `ElementMetadata` serializes when the filename is a `Path` object

- README.md
- docs/source/installing.rst
Adds a quick start page to the readme and docs to make it easier for users to get up and running with the package faster.
> docs: add a quick start page to the readme and docs

- README.md
- docs/source/installing.rst
Corrects the install instruction for local inference to `pip install "unstructured[local-inference]"`
> docs: add quotes to `unstructured[local-inference]` install instructions

- CHANGELOG.md
- unstructured/ingest/doc_processor/generalized.py
Separate `elements` out into separate variable to more naturally allow for conditional logic based on the instance type of the `doc` (or other properties).
E.g.
```
elements = partition(filename=doc.filename)
if isinstance(doc, SubstackIngestDoc):
from unstructured.ingests.doc_processor import substack
elements = substack.process_html_elements(elements)
```
> refactor: break up logic from one line to 2

- CHANGELOG.md
- Ingest.md
- unstructured/ingest/connector/s3_connector.py
- unstructured/ingest/doc_processor/generalized.py
- unstructured/ingest/interfaces.py
Moves the logic to partition a raw document to the IngestDoc level to allow for easier overrides for subclasses of [IngestDoc](https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/ingest/interfaces.py).
> refactor: move processing logic to IngestDoc

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/partition/html.py
Close #250.
This will allow `partition_html` to use a custom XMLParser or HTMLParser.
It can be useful if one needs to specify additional arguments to these parsers (not only built-in `remove_comments=True`).
> feat: add allow custom parsers in partition_html

- CHANGELOG.md
- Ingest.md
- unstructured/__version__.py
Fixes an issue where the packaged CLI `unstructured-ingest` was failing due to:
ModuleNotFoundError: No module named 'unstructured.ingest'
Also updates the Ingest documentation to make clear that detectron and other OS dependencies are needed when processing PDF's.
Tested locally in a fresh virtual env where the `unstructured` package was installed from the local checkout with `pip install -e .`
> fix: Adds missing __init__.py

- scripts/setup_ubuntu.sh
Updates so that script will run inside a docker container to set it up.
Tested versions:
Create a directory with only `scripts/setup_ubuntu.sh` in it.
Create the following `Dockerfile` in that directory:
```docker
FROM ubuntu
COPY setup_ubuntu.sh /
```
From within the directory, run `docker build . -t ub-test`.
Run with `docker run -it ub-test /bin/bash`.
Now within the container, run the script with:
```shell
./setup_ubuntu.sh root
```
After installation, run `source $HOME/.bashrc` and you should have the `pyenv` command available. `pyenv versions` should show that version 3.8.15 is installed.
Check that poppler is installed with `pdftoppm -h`.
Check that tesseract is installed with `tesseract`.
> fix: update script for docker

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/ingest/main.py
This brings back the connector initialization as was intended and got lost in a refactor.
Thanks @tomaarsen for catching this.
> fix: Ingest main: actually initialize the connector

- CHANGELOG.md
- test_unstructured/partition/test_common.py
- unstructured/__version__.py
- unstructured/documents/elements.py
- unstructured/partition/common.py
Fixes an issue introduced in [this commit](https://github.com/Unstructured-IO/unstructured/commit/74e6b84b41ff5456ba8f87958a2c7cde73d3c8d1#diff-9eb4b1248793302fa3b6bc9db25756503ea28f53ca556417c27f0be85d7a709b) that caused `NarrativeText` and `FigureCaption` elements to get represented as `Text` in HTML documents.
The following previously showed no `NarrativeText` elements, but should now display `NarrativeText`.
```python
from unstructured.documents.elements import NarrativeText
url = "https://www.understandingwar.org/backgrounder/russian-offensive-campaign-assessment-february-8-2023"
elements = partition_html(url=url)
narrative_text = [el for el in elements if isinstance(el, NarrativeText)][2:]
for element in narrative_text: …
```
> fix: track narrative text and figure captions in HTML documents

- CHANGELOG.md
- test_unstructured_ingest/expected-structured-output/github-downloadify/test.html.json
- test_unstructured_ingest/test-ingest-github.sh
- unstructured/__version__.py
Updates the github-ingest test's expected output, which is a result of https://github.com/Unstructured-IO/unstructured/pull/309 .
Includes tweaks so that the github ingest test script now runs 20% of the time. The above would have been caught sooner if this ran 100% of the time. Related issue: https://github.com/Unstructured-IO/unstructured/issues/306 .
> bump: release commit

- CHANGELOG.md
- scripts/setup_ubuntu.sh
- unstructured/__version__.py
When I took the changes to the Ubuntu setup script and propagated them to other scripts that run in slightly different contexts, the script failed at line 45 as `DEBIAN_FRONTEND=noninteractive` was interpreted as a command rather than a variable assignment.
Added the `env` command so there's no misinterpretation. Tested in docker as both root and user.
A good test is @cragwolfe 's [gist](https://gist.github.com/cragwolfe/e230fea5491ce2704356ee17857ee73c) although lines 9-17 should be removed from [setup-deps-and-test-user.sh](https://gist.github.com/cragwolfe/e230fea5491ce2704356ee17857ee73c#file-setup-deps-and-test-user-sh) for the most thorough check, as the script is set up to avoid halting at an interactive prompt when `tzdata` is being installed. Also the `wget` line will get the old …
> fix: set through env to avoid interpretation as command

- CHANGELOG.md
- docs/source/bricks.rst
- test_unstructured/partition/test_text_type.py
- unstructured/__version__.py
- unstructured/partition/text_type.py
Adds an `UNSTRUCTURED_LANGUAGE_CHECK` environment variable that controls whether language specific checks such as vocab and part of speech checks are applied. Users can set this to `"true"` for more accurate partitioning or `"false"` for faster processing.
The following shows how to apply this language checks with both the kwarg and the environment variable.
```python
from unstructured.partition.text_type import is_possible_title
is_possible_title("BLI BLA BLARG") # should be True
is_possible_title("BLI BLA BLARG", language_checks=True) # should be False
os.environ["UNSTRUCTURED_LANGUAGE_CHECKS"] = "true"
is_possible_title("BLI BLA BLARG") # should be False
```
We should also observe a speed up when `partition_html` is applied on the feature branch relative to `main`. My tests locally …
> feat: `UNSTRUCTURED_LANGUAGE_CHECK` env var to control 

- scripts/setup_ubuntu.sh
Adds `libreoffice` to the dependencies that get installed in the `setup_ubuntu.sh` script. We previously omitted this dependency in the setup scripts we were unsure how many users would have the older `.doc`/`.ppt` files as a opposed to the newer `.docx`/`.pptx`.
> chore: add libreoffice to ubuntu install script

- .github/workflows/create_issue.yml
Created a github workflow to create a new issue in JIRA when a github issue is created, mirroring the summary and description.
Pretty simplistic for now with a hardcoded project, and no support for any ongoing sync events.
> ci: workflow to create JIRA issue on GH issue create

- README.md
People are using the quick start code in the README and are getting errors when using the latest versions of python. This adds a note about python higher up in the docs.
> chore: Add note about python version

- docs/source/bricks.rst
- docs/source/index.rst
- docs/source/integrations.rst
Created `integrations.rst` with intro and 8 integrations, and added that to the index. I only included code for LangChain integration (not visible in github preview though). The other integrations have a simple descriptions with capabilities, some parameters usage, and links to the "integration company"/github and to the code snippet in our staging bricks docu. Here is the list:
- Arguila
- Datasaur
- Hugging Face
- Labelbox
- Label Studio
- LangChain
- Pandas
- Prodigy
> Docs: add Integrations section

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/nlp/english_words.py
Before:
```
(sec) MacBook-Pro-2:unstructured cragwolfe$ time python -c "from unstructured.partition.text import partition_text; partition_text('./unstructured/nlp/english-words.txt')"
real    16m14.820s
user    15m51.560s
sys     0m9.885s
```
After:
```
(sec) MacBook-Pro-2:unstructured cragwolfe$ time python -c "from unstructured.partition.text import partition_text; partition_text('./unstructured/nlp/english-words.txt')"
real    1m41.702s
user    1m40.683s
sys     0m2.806s
```
> feat: change english_words to set for performance gain

- CHANGELOG.md
- test_unstructured_ingest/test-ingest-azure.sh
- test_unstructured_ingest/test-ingest-biomed-api.sh
- test_unstructured_ingest/test-ingest-biomed-path.sh
- test_unstructured_ingest/test-ingest-github.sh
- test_unstructured_ingest/test-ingest-gitlab.sh
- test_unstructured_ingest/test-ingest-s3.sh
- test_unstructured_ingest/test-ingest-wikipedia.sh
- test_unstructured_ingest/test_interfaces.py
- unstructured/ingest/connector/biomed.py
- unstructured/ingest/connector/fsspec.py
- unstructured/ingest/connector/git.py
- unstructured/ingest/connector/google_drive.py
- unstructured/ingest/connector/reddit.py
- unstructured/ingest/connector/wikipedia.py
- unstructured/ingest/interfaces.py
- unstructured/ingest/main.py
Currently, the default behavior of [unstructured-ingest](https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/ingest/main.py) is to [drop the metadata field](https://github.com/Unstructured-IO/unstructured/blob/70420b5/unstructured/ingest/interfaces.py#L97) “filename” from the json output.
However, it would be better if the user could specify what metadata fields to drop (if they exist) or what fields to include (drop all other fields).
> feat: add --metadata-include and --metadata-exclude parameters to unstructured-ingest

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/partition/pdf.py
This PR addresses the issue https://github.com/Unstructured-IO/unstructured/issues/374 with the suggested fix.
In order to test is possible to use
```
from unstructured.partition import pdf
results = pdf.partition_pdf("example-docs/layout-parser-paper-fast.pdf")
all_text =[r1.text for r1 in r]
print(all_text)
```
And the result should be the complete text from the file without any missing or duplicated text block.
> Fix: duplicated addition to elements list

- CHANGELOG.md
- test_unstructured_ingest/test_interfaces.py
- unstructured/__version__.py
- unstructured/ingest/connector/biomed.py
- unstructured/ingest/connector/fsspec.py
- unstructured/ingest/connector/git.py
- unstructured/ingest/connector/google_drive.py
- unstructured/ingest/connector/reddit.py
- unstructured/ingest/connector/wikipedia.py
- unstructured/ingest/interfaces.py
- unstructured/ingest/main.py
For some use cases, json output is often translated into a single row in a table, but having an extra level of indirection with a metadata nested dictionary makes inserting into such a table awkward.
Therefore, we want to add a `--flatten-metadata` parameter to https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/ingest/main.py, which simply results in all elements in the metadata field moving up a level and removing the metadata field. I.e.:
```
{
"element_id": "d551bbfc9477547e4dce6264d8196c7b",
"text": "More info available at the Github Project Page",
"type": "Title",
"metadata": {
"page_number": 1
}
},
```
->
```
{
"element_id": "d551bbfc9477547e4dce6264d8196c7b",
"text": "More info available at the Github Project Page",
"type": "Title",
"page_number": 1
},
```
> feat: add --flatten-metadata to unstructured-ingest

- CHANGELOG.md
- docs/source/bricks.rst
- test_unstructured/partition/test_auto.py
- unstructured/__version__.py
- unstructured/file_utils/filetype.py
- unstructured/partition/auto.py
Adding content_type and file_filename to auto_partition function. By accepting content_type as a string, we can bypass filetype detection in a lot of cases.
> Adding content_type and file_filename to autopartition

- CHANGELOG.md
- test_unstructured/partition/test_email.py
- test_unstructured/partition/test_html_partition.py
- test_unstructured/partition/test_json.py
- test_unstructured/partition/test_text.py
- unstructured/__version__.py
- unstructured/partition/email.py
- unstructured/partition/html.py
- unstructured/partition/json.py
- unstructured/partition/text.py
Adds a fix to partition functions that accepts a `text` kwarg. They no longer fail if an empty string is passed, but rather return an empty list of elements. Additional, `partition_json` was updated so that it does not fail if the input is an empty list. Instead, an empty list of elements is returned.
```python
from unstructured.partition.text import partition_text
partition_text(text="")
```
```python
from unstructured.partition.json import partition_json
partition_json(text="[]")
```
> fix: text kwargs no longer fail with empty string

- .github/workflows/docker-publish.yml
- Dockerfile
This doesn't significantly impact image size nor build time and resolves issues where the first run needs to download content.
```
remote/compressed (there's some rounding here):
original: 3.7 GB
+nltk: 3.8 GB
+nltk+models: 4.0 GB
local/decompressed:
original: 8.91GB
+nltk: 8.97GB
+nltk+models: 9.3GB
```
I pushed a test build in this [commit](https://github.com/Unstructured-IO/unstructured/pull/418/commits/5dafc53f9b11cb384bafae798f765a5f7f8e1c42) and the output can be pulled from [here](https://github.com/Unstructured-IO/unstructured/actions/runs/4559588428).
Test by running:
```
docker pull quay.io/unstructured-io/test-unstructured:5dafc53
docker run -it quay.io/unstructured-io/test-unstructured:5dafc53
python3
>> from unstructured.partition.auto import partition
>> elements = …
```
> ci: update dockerfile to also add models and nltk

- .github/workflows/docker-publish.yml
The set-output command will [soon be deprecated ](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)in GitHub Actions. This updates to use GITHUB_OUTPUT as recommended.
> ci: update CI for deprecated set-output

- CHANGELOG.md
- test_unstructured/staging/test_huggingface.py
- unstructured/__version__.py
- unstructured/staging/huggingface.py
Updates the `stage_for_transformers` function to return a list of elements, like the other staging bricks. Users can continue to use `chunk_by_attention_window` if they need to operate directly on strings. Having `stage_for_transformers` enables you to run operations like getting a pandas dataframe with pre-chunked segments by running `convert_to_dataframe(stage_for_transformers(elements, tokenizer))`.
Also fixed a bug that was causing the last word of the last segment to get cut off in `chunk_by_attention_window`.
```python
from unstructured.documents.elements import NarrativeText, Title
from unstructured.staging.huggingface import stage_for_transformers
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("google/flan-t5-base")
text = <text>
elements = …
```
> !fix: return a list of elements in `stage_for_transformers`

- CHANGELOG.md
- test_unstructured/partition/test_text.py
- unstructured/__version__.py
- unstructured/partition/text.py
Ran into an error in tests for unstructured-api (see below for output). Somewhere along the lines we were reading a txt file into bytes and then the `PARAGRAPH_PATTERN` (a string) was not able to be compared to the bytes file. The simplest solution to make the test happy was to convert the `file_text` to a string before passing to the function resulting in the error.
```
test_general/api/test_app.py:43: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
.venv/lib/python3.8/site-packages/starlette/testclient.py:590: in post
return super().post(
.venv/lib/python3.8/site-packages/httpx/_client.py:1136: in post
return self.request(
.venv/lib/python3.8/site-packages/starlette/testclient.py:465: in request
return super().request( …
```
> Fixing test for unstructured-api

- Dockerfile
- Makefile
- README.md
- docs/source/installing.rst
Update `Dockerfile` and docs with updated `detectron2` version.
CI should pass (may require updating ingest fixtures again).
> build: sync detectron version

- CHANGELOG.md
- test_unstructured/partition/test_email.py
- test_unstructured/partition/test_msg.py
- unstructured/__version__.py
- unstructured/documents/elements.py
- unstructured/partition/email.py
- unstructured/partition/msg.py
Adds `sent_from`, `sent_to`, `subject`, and `date` to the element metadata for emails
The following code should now show the above metadata fields populated:
```python
elements = partition_email(filename="example-docs/fake-email.eml")
elements[0].metadata
```
```python
from unstructured.partition.msg import partition_msg
elements = partition_msg(filename="example-docs/fake-email.msg")
elements[0].metadata
```
> feat: add sender and receive info to element metadata for emails

- .github/workflows/create_issue.yml
I realized that `github.event.issue.url` gives a url to the domain `api.github.com`. `html_url` (which doesn't seem to be documented in the `issues` interface) gives the url we want.
> fix: change url to html_url

- CHANGELOG.md
- test_unstructured/partition/test_html_partition.py
- unstructured/__version__.py
- unstructured/documents/xml.py
Closes #436. Updates the string encoding logic in `documents/xml.py` to better support reading foreign language characters.
The following should now show `"每日新闻"` as the output. Previously the output was `"æ¯æ¥æ°é»`".
```python
html_text = "<html><div><p>每日新闻</p></div></html>"
elements = partition_html(text=html_text)
str(elements[0])
```
> fix: fix html encoding to support foreign characters

- CHANGELOG.md
- test_unstructured/cleaners/test_core.py
- unstructured/__version__.py
- unstructured/cleaners/core.py
- unstructured/partition/email.py
Closes #444. Updates `replace_mime_encodings` to accept an `encoding` kwarg. Also passes in the `encoding` kwarg from `partition_email`.
The following work now. With utf-8 encoding, this failed with a `UniDecodeError`.
```python
from unstructured.cleaners.core import replace_mime_encodings
text = '5 w=E2=80-92s'
replace_mime_encodings(text, encoding="latin-1")
```
> fix: allow `replace_mime_encodings` to accept and `encoding` kwarg

- CHANGELOG.md
- docs/source/bricks.rst
- test_unstructured/cleaners/test_core.py
- test_unstructured/partition/test_text.py
- unstructured/__version__.py
- unstructured/cleaners/core.py
- unstructured/nlp/patterns.py
- unstructured/partition/auto.py
- unstructured/partition/text.py
Closes #406. Adds a `group_broken_paragraphs` cleaning brick for grouping together sentences that have a page break for formatting purposes. This is common in `.txt` files. Also add a `paragraph_grouper` kwarg to `partition_text` to allow for passing in a paragraph grouping callable.
The following code should produce two `NarrativeText` elements. Without the paragraph grouper, `partition_text` produce four elements due to the line break.
```python
from unstructured.partition.text import partition_text
from unstructured.cleaners.core import group_broken_paragraphs
text = """The big brown fox
was walking down the lane.
At the end of the lane, the
fox met a bear."""
partition_text(text=text, paragraph_grouper=group_broken_paragraphs)
```
> feat: enable grouping broken paragraphs in `partition_text`

- CHANGELOG.md
- Dockerfile
- unstructured/__version__.py
- unstructured/file_utils/filetype.py
The `mailcap` centos7 package provides the file `/etc/mime.types`, which is used by the `mimetypes` python package. That said, the `unstructured` code base does not make much use of this but the upstream `unstructured-api` does.
Bonus: `docx` mimetype added in lookup table.
> build: add mimetypes DB to docker image

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/ingest/connector/local.py
- unstructured/ingest/interfaces.py
- unstructured/ingest/main.py
As most connectors have additional dependencies that may not be installed locally, only import those connectors' modules when they are being used.
> fix(ingest): import connector-specific modules on demand

- CHANGELOG.md
- README.md
- docs/source/bricks.rst
- example-docs/fake-doc.rtf
- test_unstructured/file_utils/test_filetype.py
- test_unstructured/partition/test_auto.py
- test_unstructured/partition/test_rtf.py
- unstructured/__version__.py
- unstructured/file_utils/file_conversion.py
- unstructured/file_utils/filetype.py
- unstructured/partition/auto.py
- unstructured/partition/html.py
- unstructured/partition/rtf.py
Closes #410. Adds `partition_rtf` for processing rich text files. Also refactors `partition_epub` to use a common function for converting docs to HTML with `pandoc` and partitioning with `partition_html`.
Updates a few outdated docs.
First make sure the new RTF code works.
```python
from unstructured.partition.rtf import partition_rtf
elements = partition_rtf(filename="example-docs/fake-doc.rtf")
```
Next, make sure EPUBs still work
```python
from unstructured.partition.epub import partition_epub
elements = partition_epub(filename="example-docs/winter-sports.epub")
```
> feat: add `partition_rtf` for rich text files

- test_unstructured_ingest/test-ingest-biomed-api.sh
- test_unstructured_ingest/test-ingest-biomed-path.sh
The Biomed connectors have been flaky with ftp connections lately.
> build: skip biomed ingest tests 90% of time due to ftp connectivity

- .github/workflows/create_issue.yml
Attempting to fix formatting of github issues transferred to Jira.
The old format was attempting to use double-slashes (`\\`) to specify line breaks. This worked in the [test repo](https://github.com/Unstructured-IO/jira-integration-test) but didn't look right when merged to this repo (see description in [CORE-910](https://unstructured-ai.atlassian.net/browse/CORE-910) for an example of how it looks).
Now attempting to use formatted text in the `yaml` with `|`. This worked in the test repo, but I guess that's no guarantee. See attached image for results from personal Jira project from [this issue](https://github.com/Unstructured-IO/jira-integration-test/issues/14).
It's been tested using the test repo linked to a personal Jira project. We won't be able to see the results in this repo …
> fix: fix github issue formatting

- CHANGELOG.md
- docs/source/bricks.rst
- test_unstructured/partition/test_auto.py
- unstructured/__version__.py
- unstructured/partition/auto.py
Closes #464 and addresses user requests in [langchain#979](https://github.com/hwchase17/langchain/pull/979) Adds a `url` kwarg to `partition` to allow users to process remote documents directly. If the user passes in `content_type`, `partition` will process the document using `content_type` as the MIME type. Otherwise, it will use the `Content-Type` header to determine the MIME type.
```python
url = "https://raw.githubusercontent.com/Unstructured-IO/unstructured/main/LICENSE.md"
elements = partition(url=url, content_type="text/markdown")
url = "https://www.understandingwar.org/backgrounder/russian-offensive-campaign-assessment-april-11-2023"
elements = partition(url=url)
url = "https://www.understandingwar.org/sites/default/files/Russian%20 …
```
> feat: add `url` kwarg to `partititon`

- CHANGELOG.md
- test_unstructured/documents/test_html.py
- unstructured/__version__.py
- unstructured/documents/xml.py
I had trouble reading a markdown document in langchain which contained an emoji. Currently in that case `etree.fromstring(content, self.parser)` returns None. So it doesn't raise the ValueError and doesn't try to encode to string. I'm raising the ValueError in that case to ensure we enter the except block and encode the string.
> fix: encode xml string if document_tree is `None` in `_read_xml`

- CHANGELOG.md
- test_unstructured/documents/test_html.py
- test_unstructured/partition/test_auto.py
- unstructured/__version__.py
- unstructured/partition/auto.py
Allows for passing in headers to `partition` if a URL is passed.
```python
url = "https://www.understandingwar.org/sites/default/files/Russian%20Offensive%20Campaign%20Assessment%2C%20April%2011%2C%202023.pdf"
elements = partition(url=url, headers={"Accept": "application/pdf"}, strategy="fast")
```
> feat: allow headers in `partition`

- CHANGELOG.md
- test_unstructured/partition/test_auto.py
- unstructured/__version__.py
- unstructured/documents/xml.py
Closes #475. Updates the HTML code to support processing markdown files with embedded HTML. Adding a carriage return to the beginning of the HTML document appears to fix the issue.
The following should show the content of the markdown file instead of `'h   3       a   l   i   g   n   =   "   c   e   n   t   e   r   "   >'`.
```python
url = "https://raw.githubusercontent.com/Unstructured-IO/unstructured/main/README.md"
elements = partition(url=url, content_type="text/markdown")
elements[0].text
```
> fix: updates markdown code to process markdown with embedded html

- CHANGELOG.md
- docs/source/bricks.rst
- test_unstructured/cleaners/test_core.py
- test_unstructured/partition/test_html_partition.py
- unstructured/__version__.py
- unstructured/cleaners/core.py
Closes #474, expanding on the fix from #477. Adds a cleaning brick for converting bytes string output to properly encoded strings. This type of output occurs when there's a character like an emoji in HTML or Markdown that the HTML parser does not understand. Note that this is not required if the HTML document uses [UTF-8 codes](https://www.w3schools.com/html/html_emojis.asp) for emojis.
The following two snippets should result in outputs that contain the emoji.
```python
from unstructured.cleaners.core import bytes_string_to_string
text = """\n<html charset="utf-8"><p>Hello 😀</p></html>"""
elements = partition_html(text=text)
elements[0].apply(bytes_string_to_string)
elements[0].text
```
```python
from unstructured.partition.html …
```
> feat: cleaning brick for normalizing bytes string output

- .github/workflows/ci.yml
- test_unstructured_ingest/test-ingest-github.sh
Avoids the occaisonal CI test failures  in test-ingest-github.sh that were due to rate-limited non-auth'ed requests against a GitHub repo.
> build(CI): add access token for github-ingest test

- CHANGELOG.md
- test_unstructured/partition/test_text_type.py
- unstructured/partition/text_type.py
There are cases when function is_possible_narrative_text receives an incorrect return from function exceeds_cap_ratio and does an incorrect classification, so some of the return values of exceeds_cap_ratio are corrected
> fix: fix text_type.py exceeds_cap_ratio() returns

- scripts/ingest-test-fixtures-update.sh
- test_unstructured_ingest/expected-structured-output/azure-blob-storage/rfc854.txt.json
- test_unstructured_ingest/test-ingest-biomed-api.sh
- test_unstructured_ingest/test-ingest-biomed-path.sh
* Update test fixtures that should have been updated in prior commit
* Disable biomed ingest tests for now, the fail more often than not
* Bonus: echo `tesseract --version` in the update script, since that is a key thing that influences fixture outputs.
> fix: update ingest test fixtures, disable biomed test

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/partition/json.py
Closes [487](https://github.com/Unstructured-IO/unstructured/issues/487). Fixed typo in call to `exactly_one` in `partition_json`.
> fix: Fix typo in function call

- CHANGELOG.md
- Makefile
- test_unstructured/partition/test_auto.py
- unstructured/__version__.py
- unstructured/file_utils/filetype.py
Fixes issue where .json files were recognized as "text/plain" rather than "application/json on the Unstructured image (and other installs that may have an older libmagic).
Also adds missing json auto partition tests.
Including an xfail test for https://github.com/Unstructured-IO/unstructured/issues/492 .
> fix: workaround .json file detection with old libmagic installs

- docs/source/bricks.rst
Closes #497. Fixes incomplete docs on hi res processing.
> docs: fix incomplete hi_res docs

- CHANGELOG.md
- docs/source/bricks.rst
- test_unstructured/partition/test_html_partition.py
- unstructured/__version__.py
- unstructured/partition/auto.py
- unstructured/partition/html.py
Closes #383. Adds an `ssl_verify` kwarg to `partition` and `partition_html` that enables users to turn off SSL verification for HTTP requests.
```python
url = 'https://malegislature.gov/Laws/GeneralLaws/PartI/TitleXV/Chapter93A/Section1'
headers = {
'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0  Safari/537.36'
}
elements = partition_html(url=url, headers=headers)
elements = partition_html(url=url, ssl_verify=False, headers=headers)
elements = partition(url=url, ssl_verify=False, headers=headers)
```
> feat: parameter to turn off SSL verification

- CHANGELOG.md
- docs/source/bricks.rst
- test_unstructured/partition/test_api.py
- unstructured/__version__.py
- unstructured/partition/api.py
Adds a helper function for partitioning documents through the hosted REST API. Implemented in response to feedback from users who were interested in more convenient ways to use the hosted API. 
Notes, this function processes a single document and mimics the `partition` and `partition_{doc_type}` functions. The API also accepts multiple files. There will be a follow on PR that calls the API with multiple files.
Note the API key here is obviously fake. API keys are not enforced yet but will be soon. For future humans, if the test code doesn't work, please sign up for an API key :-)
```python
from unstructured.partition.api import partition_via_api
filename = "example-docs/fake-email.eml"
elements = partition_via_api(filename=filename, api_key="MY_API_KEY", content_type="message/rfc822") …
```
> feat: `partition_via_api` helper function

- CHANGELOG.md
- example-docs/spring-weather.html.json
- test_unstructured/file_utils/test_filetype.py
- test_unstructured/partition/test_auto.py
- unstructured/__version__.py
- unstructured/file_utils/filetype.py
- unstructured/nlp/patterns.py
- unstructured/partition/json.py
Closes #492. Updates the `detect_filetype` logic to properly detect JSON files even when the MIME type is `text/plain`. Enables to the `partition` function to process JSONs when they are passed in as a file.
The output here should show "News Around NOAA"
```python
filename = "test_unstructured_ingest/expected-structured-output/azure-blob-storage/spring-weather.html.json"
with open(filename, "rb") as f:
elements = partition(file=f)
elements[0].text
elements = partition(filename=filename)
elements[0].text
```
> fix: update `detect_filetype` for JSONs with text/plain MIME type

- README.md
Adds badges to the REAME showing total downloads and downloads per month.
Looks like this in dark mode.
> docs: add download badges to README

- docs/source/_static/unstructured.css
- docs/source/_templates/base.html
- docs/source/_templates/page.html
- docs/source/_templates/sidebar/brand.html
- docs/source/conf.py
- docs/source/index.rst
Closes #534. Adds GitHub star and Slack links back into the docs. For some reason they disappeared from the sidebar.
- Make sure the "Star" part of the link redirects to the GH page
- Make sure the Slack link redirects to our community Slack
- The docs page should look like the following if you run `make html`
> docs: add slack and github links back into docs page

- .github/workflows/sphinx.yml
Updates the documentation job to only build on tags. Currently, it builds on every push to `main`, which can result in documentation for new features becoming public before the features themselves are available. Also builds on a `docs-build` branch if we need to do a docs only update between releases. `docs-build` is now a protected branch.
> ci: only build docs on tags

- requirements/base.txt
- setup.py
Closes #523 . Adds `pdfminer-six` explicitly to the list of `unstructured` dependencies since it is used when the `"fast"` strategy is called for `partition_pdf`.
> build(deps): add `pdfminer.six` to dependencies

- CHANGELOG.md
- docs/source/bricks.rst
- test_unstructured/partition/test_api.py
- unstructured/__version__.py
- unstructured/partition/api.py
Adds a function for partitioning multiple files through the API. The new function batches multiple files into a single request.
```python
from unstructured.partition.api import partition_multiple_via_api
filenames = ["example-docs/fake-email.eml", "example-docs/fake.docx"]
documents = partition_multiple_via_api(filenames=filenames)
```
```python
from contextlib import ExitStack
from unstructured.partition.api import partition_multiple_via_api
filenames = ["example-docs/fake-email.eml", "example-docs/fake.docx"]
files = [open(filename, "rb") for filename in filenames]
with ExitStack() as stack:
files = [stack.enter_context(open(filename, "rb")) for filename in filenames]
documents = partition_multiple_via_api(files=files, file_filenames=filenames)
```
> feat: add `partition_multiple_via_api` function

- CHANGELOG.md
- docs/source/bricks.rst
- docs/source/integrations.rst
- test_unstructured/staging/test_baseplate.py
- unstructured/__version__.py
- unstructured/staging/baseplate.py
Closes #517. Adds a `stage_for_baseplate` function that prepares `unstructured` output for ingestion into Baseplate through the Baseplate API. The [Baseplate docs](https://docs.baseplate.ai/api-reference/documents/overview) show how the data needs to be formatted.
You can run the staging function with the following code
```python
from unstructured.documents.elements import ElementMetadata, NarrativeText, Title
from unstructured.staging.baseplate import stage_for_baseplate
metadata = ElementMetadata(filename="fox.epub")
elements = [
Title("A Wonderful Story About A Fox", metadata=metadata),
NarrativeText(
"A fox ran into the chicken coop and the chickens flew off!",
metadata=metadata,
),
]
rows = stage_for_baseplate(elements)
```
The output will look like:
```python
{
"rows": [
{
"data": { …
```
> feat: `stage_for_baseplate` function

- .github/workflows/sphinx.yml
Removing the conditional statement from the deploy step in the docs build CI job. Now we only run the docs on tag. Since the tag ref isn't main, this was causing our docs not to deploy.
> fix(ci): don't skip docs deploy for tags

- Dockerfile
- Makefile
- README.md
Tested on Apple silicon based MacBook Pro.  This installs tensorboard which is required on OSX and arm based cpu’s for detectron2.
> Fixes issue where detectron2 would not install on OSX

- Dockerfile
- docs/requirements.txt
- requirements/base.txt
- requirements/build.txt
- requirements/dev.txt
- requirements/huggingface.txt
- requirements/local-inference.txt
- requirements/test.txt
- setup.py
- test_unstructured/staging/test_label_studio.py
- test_unstructured_ingest/expected-structured-output/azure-blob-storage/IRS-form-1987.pdf.json
- pin unstructured-inference to 0.4.4 in setup.py
- bump dependencies
- update image build to install openssl 1.1.1 and python to compile with it
- bonus: disable a labelstudio test that relies on vcr which fails with usrllib3==2.0.2
> chore: pin inference version, bump deps, and update openssl

- examples/mysql/README.md
- examples/mysql/load-into-mysql.ipynb
- examples/mysql/requirements.txt
Adds an example notebook showing how to load `unstructured` outputs into MySQL and run a query based on extracted metadata.
Set up MySQL and run the notebook under `examples/mysql`.
> docs: `unstructured` -> MySQL example

- CHANGELOG.md
- test_unstructured/partition/test_docx.py
- test_unstructured/partition/test_pdf.py
- test_unstructured/partition/test_pptx.py
- unstructured/__version__.py
- unstructured/partition/__init__.py
- unstructured/partition/common.py
- unstructured/partition/docx.py
- unstructured/partition/pdf.py
- unstructured/partition/pptx.py
- unstructured/partition/strategies.py
Add support for SpooledTemporaryFile file arguments when partitioning pdf, docx, and pptx. These all rely on various functionality not supported by SpooledTemporaryFile. This PR adds a `spooled_to_bytes_io_if_needed` function so that we can change filetypes in place and get the functionality expected by these partition modules.
> chore: add support for SpooledTemporaryFiles

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/logger.py
- unstructured/partition/text_type.py
Addresses https://github.com/Unstructured-IO/unstructured/issues/331 and adds an additional trace logger to differentiate between `DEBUG` and `DETAIL` level output so that most NLP debug logs to the trace logger.
Python script:
```
import logging
logger = logging.getLogger("unstructured")
trace_logger = logging.getLogger("unstructured.trace")
handler = logging.StreamHandler()
handler.setFormatter(logging.Formatter("%(asctime)s %(levelname)s %(message)s"))
logger.addHandler(handler)
logger.setLevel(logging.DEBUG)
trace_logger.setLevel(logging.WARNING)
elements = partition(filename="example-docs/fake-email.eml")
```
And the output will not contain any `DEBUG` or `DETAIL` level logs.
> Chore: Add a trace logger for NLP output

- CHANGELOG.md
- test_unstructured/file_utils/test_filetype.py
- unstructured/__version__.py
- unstructured/file_utils/filetype.py
First time contributor. Please help review if there are any problems with the style.
This commit fixed the problem when reading the first 4096 bytes results in a chunked character at the end. Decoding these characters will result in `UnicodeDecodeError`. 
In my case, I have a character that is `b'\xe2\x80\x94'` (non-standard dash connector) and reading the first 4096 byte will not read the last `\x94`. Since these two functions only checking json and eml, ignoring the character will fix the problem while not affecting the core logic.
> fix: check json and eml decode ignore error

- CHANGELOG.md
- docs/source/bricks.rst
- unstructured/__version__.py
- unstructured/partition/pdf.py
Closes #562. Makes `pytesseract` a function level import so you can use strategies that don't require `pytesseract` without `pytesseract` being installed. Also added the `required_dependencies` decorator for the `"hi_res"` and `"ocr_only"` strategies.
This PR also includes a small docs formatting fix.
If you uninstall `pytesseract`, the following should work:
```python
filename = "example-docs/layout-parser-paper-fast.pdf"
elements = partition_pdf(filename=filename, strategy="fast")
```
> fix: make `pytesseract` a function level import

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/file_utils/filetype.py
Addresses https://github.com/Unstructured-IO/unstructured/issues/584 and adds `hml` as a filetype
```
file_path = "example-docs/example.htm"
partition(filename=file_path)
```
> Fix: support `hml` filetype in partition as a variation of html

- CHANGELOG.md
- test_unstructured/partition/test_auto.py
- test_unstructured/partition/test_doc.py
- test_unstructured/partition/test_html_partition.py
- test_unstructured/partition/test_msg.py
- test_unstructured/partition/test_pdf.py
- test_unstructured_ingest/expected-structured-output/slack-ingest-channel/C052BGT7718.json
- test_unstructured_ingest/test-ingest-azure.sh
- test_unstructured_ingest/test-ingest-biomed-api.sh
- test_unstructured_ingest/test-ingest-biomed-path.sh
- test_unstructured_ingest/test-ingest-github.sh
- test_unstructured_ingest/test-ingest-gitlab.sh
- test_unstructured_ingest/test-ingest-local.sh
- test_unstructured_ingest/test-ingest-s3.sh
- test_unstructured_ingest/test-ingest-wikipedia.sh
- unstructured/__version__.py
- unstructured/documents/elements.py
Adds a `file_directory` attribute alongside `filename` in the element metadata.
```python
elements = partition_pdf("../unstructured/example-docs/layout-parser-paper-fast.pdf")
print(elements[0].metadata.filename)
print(elements[0].metadata.file_directory)
```
> enhancement: add `file_directory` to element metadata

- CHANGELOG.md
- test_unstructured/partition/test_xlsx.py
- unstructured/__version__.py
- unstructured/documents/elements.py
- unstructured/partition/xlsx.py
Added tracking for the sheet name of Excels documents as a `page_name` field in the `ElementMetadata` class.
#600
> feat: add page_name to metadata for Excel documents

- CHANGELOG.md
- test_unstructured/partition/test_pdf.py
- unstructured/__version__.py
- unstructured/partition/pdf.py
- unstructured/partition/text.py
After telling a user that the element bounding box coordinates were available when using the `fast` strategy, I realized that's actually not true. This PR is to make the bounding box coordinates available.
- Refactored `partition_text` to make the workflow of categorizing an element purely from the text available without running the entirety of `partition_text`. 
- Transformed the coordinates from pdf space into pixel space to be consistent with `hi_res`. We will probably want to revisit the coordinate system soon.
- Updated a test
```python
elements = partition_pdf("example-docs/layout-parser-paper-fast.pdf", strategy="fast")
for el in elements:
print(el.coordinates)
```
Coordinates should not be `None`.
You can also run the following …
> enhancement: include coords in fast

- Dockerfile
This should speed up the builds a lot by using a docker image that has all the required system libraries and packages compiled/installed.
You can find the Dockerfile for the base image at https://github.com/Unstructured-IO/base-images or pull them from quay at quay.io/unstructured-io/base-images:centos7.9
The base image has been built for both linux/arm64 and linux/amd64 using docker buildx
> Build using base image

- .github/workflows/ci.yml
Jobs occasionally fall in to a competing state to set the cache where they don't all install the same things in the venv (which is cached), but they all use the same cache key. So if say `check-deps` wins, it will only install base-pip-packages [here](https://github.com/Unstructured-IO/unstructured/blob/main/.github/workflows/ci.yml#L65). Then any time anyone else fetches they'll get -that- version of the venv and not have the modules they necessarily need.
To resolve, this makes the setup job solely responsible for writing to the cache. All other jobs require setup to complete and then only pull the cache (not try to write to it). 
To make matters slightly more odd, afaict it seems the path argument for the gha cache module will impact whether or not a key matches. So when we were …
> fix(ci):  prevent gha caching conflicts

- CHANGELOG.md
- test_unstructured/partition/test_html_partition.py
- unstructured/file_utils/filetype.py
- unstructured/partition/common.py
Fixes bug from #592
Creates test for partitioning html from filename when `metadata=False`
Creates `_remove_element_metadata` method
```
filename = "example-docs/example-10k.html"
elements = partition_html(filename=filename, include_metadata=False)
elements[-1].metadata
```
> fix: page_number appears in partition_html metadata if include_metadata=False

- .github/workflows/ci.yml
- test_unstructured_ingest/unit/test_interfaces.py
At some point [tests were created](https://github.com/Unstructured-IO/unstructured/blob/main/test_unstructured_ingest/test_interfaces.py) to explicitly validate the features of the ingest interface definitions. These do not currently pass and aren't being processed in CI. This PR updates/fixes the tests (now pass). It also refactors such that they behave as unit tests and don't rely on external services. It also adds them to the CI workflow.
> test: revive ingest unit tests

- docker/ubuntu-22/Dockerfile
- scripts/ingest-test-fixtures-update.sh
Passes Docker, Slack, and Github tokens (`DISCORD_TOKEN`, `SLACK_TOKEN`, and `GH_READ_ONLY_ACCESS_TOKEN)` from the local environment to the docker container built and run in `ingest-test-fixtures-update.sh`, this way the script can run end to end without needing to run commands against the built image (to insert env vars and re-run) after the script has run.
bonus: removes duplicate run of slack test
bonus: fixes install of required discord and slack libraries in Dockerfile
Export `DISCORD_TOKEN`, `SLACK_TOKEN`, and `GH_READ_ONLY_ACCESS_TOKEN`. Run `./scripts/ingest-test-fixtures-update.sh` on x86 arch.  It should build a container, run end to end, not skip tests, and update the fixtures.
> fix: ingest-test-fixtures-update script to pass env vars

- CHANGELOG.md
- test_unstructured/partition/test_common.py
- test_unstructured/partition/test_doc.py
- unstructured/__version__.py
- unstructured/partition/common.py
Closes #647. Updates `convert_office_doc` so that informational message about file conversion are not printed to stdout. Output is now captured and routed to `logger.info` or `logger.error` as appropriate.
You should no longer see a file conversion message when you run this code:
```python
from unstructured.partition.doc import partition_doc
filename = "example-docs/fake.doc"
elements = partition_doc(filename=filename)
```
> fix: suppress file conversion warnings in `convert_office_doc`

- CHANGELOG.md
- test_unstructured/file_utils/test_filetype.py
- test_unstructured/partition/test_auto.py
- unstructured/__version__.py
- unstructured/file_utils/filetype.py
- unstructured/nlp/patterns.py
Creates filetype detection if a CSV has a text/plain MIME type. 
Closes #621.
Also adds some parameters for `test_is_text_file_a_json`, removes unnecessary empty lines, and improves regex pattern for JSON matching.
```
from unstructured.file_utils.filetype import _is_text_file_a_csv
from io import BytesIO
files = [b"d\xe2\x80", b'[{"key": "value"}]', b"column1,column2,column3\nvalue1,value2,value3\n"]
for file in files:
with BytesIO(file) as f:
print(_is_text_file_a_csv(file=f))
```
> fix:  Filetype detection if a CSV has a text/plain MIME type

- CHANGELOG.md
- test_unstructured/file_utils/test_filetype.py
- unstructured/__version__.py
- unstructured/file_utils/filetype.py
- unstructured/partition/auto.py
Closes #705. Updates the text file checks for JSON and CSV structured in `detect_filetype` to handle documents with different encodings.
This code should now run without error
```python
from unstructured.file_utils.filetype import _is_text_file_a_csv, _is_text_file_a_json
filename = "example-docs/fake-text-utf-32.txt"
_is_text_file_a_csv(filename=filename)
_is_text_file_a_json(filename=filename)
```
> fix: handle encoding for text file checks

- CHANGELOG.md
- test_file.html
- test_unstructured/file_utils/test_filetype.py
- test_unstructured/partition/test_auto.py
- unstructured/__version__.py
- unstructured/file_utils/filetype.py
- unstructured/partition/auto.py
Closes #612. Adds handling for empty files in `detect_filetype` and `partition`. Empty files will now return an empty list from `partition`.
```python
filename = "example-docs/empty.txt"
detect_filetype(filename=filename) # Should be FileType.Empty
partition(filename=filename) # Should be []
with open(filename, "rb") as f:
filetype = detect_filetype(filename=filename) # Should be FileType.Empty
with open(filename, "rb") as f:
elements = partition(filename=filename) # Should be []
```
> enhancement: handling for empty files in `detect_filetype` and `partition`

- CHANGELOG.md
- docs/requirements.txt
- requirements/base.in
- requirements/base.txt
- requirements/build.txt
- requirements/dev.txt
- requirements/huggingface.txt
- requirements/ingest-azure.txt
- requirements/ingest-gitlab.txt
- requirements/ingest-reddit.txt
- requirements/ingest-s3.txt
- requirements/local-inference.txt
- requirements/test.txt
- test_unstructured/file_utils/test_filetype.py
- unstructured/__version__.py
- unstructured/file_utils/filetype.py
Closes #682
Enables MIME type detection if libmagic is not available. 
Uses [filetype](https://github.com/h2non/filetype.py/tree/master) as a fallback if libmagic is not present.
Updates associated `ImportError` test to check for `warning`
Adds comments
```
pytest test_unstructured/file_utils/test_filetype.py
```
> fix: Enable MIME type detection if libmagic is not available

- CHANGELOG.md
- Dockerfile
- requirements/dev.txt
- requirements/huggingface.txt
- requirements/local-inference.txt
- requirements/test.in
- requirements/test.txt
- test_unstructured/partition/test_api.py
- unstructured/__version__.py
- unstructured/partition/api.py
Passing kwargs to the data field of request to Unstructrued API. This allows additional parameters to be passed in like `strategy`, `coordinates` or `ocr_languages`. Have to bump this version again for upstream `unstructured-api`.
> Chore: Allow passing kwargs to request data field

- .github/workflows/ingest-test-fixtures-update-pr.yml
Without a version specified this added one more cache, set to v1 so this re-uses the same one in the CI workflow
> ci: add cache version to ingest-test-fixtures-update-pr workflow

- .github/workflows/ci.yml
Otherwise if the cache is evicted before the unit tests, they will fail due to not having the correct version of python and they will populate the cache without the python binary, so they will always fail when using the cache after that point.
Here I'm following the convention of all the other jobs and just always running Setup Python in the unit tests job.
> ci: add set up python to test_unit job

- CHANGELOG.md
- requirements/base.in
- requirements/base.txt
- requirements/dev.txt
- requirements/huggingface.txt
- requirements/ingest-azure.txt
- requirements/ingest-discord.txt
- requirements/ingest-google-drive.txt
- requirements/local-inference.txt
- unstructured/__version__.py
Fixes an issue of a missing python dependency if one installs `unstructured` without any extras.
> fix: pdf2image library is core requirement

- README.md
- docs/source/_templates/page.html
- docs/source/_templates/sidebar/brand.html
Updating the Slack link due to reports that we had a few people experiencing difficult signing up for the community Slack. This Slack link is set to never expire.
> docs: update slack invite link

- CHANGELOG.md
- test_unstructured/partition/test_api.py
- unstructured/__version__.py
Remove all fake keys in test, we now require valid/empty key (default is empty).
> Fix: remove fake api key in test

- Makefile
Since the move to onnxruntime'd version of detetron2 in https://github.com/Unstructured-IO/unstructured/pull/662 , these makefile targets are no longer serving a purpose.
> chore: rm old detectron2 install from makefile

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/partition/docx.py
Closes #775. First checks for the `xml` attribute on the document elements before checking for pagebreaks.
> fix: check for xml attribute when identifying pagebreaks

- .github/workflows/docker-publish.yml
AMD images were building but failing to load in CI (meaning there weren't able to test and publish). This seems to be an issue with buildx. The solution is to use the "docker" driver. 
[Here is a reference ](https://github.com/Unstructured-IO/unstructured/actions/runs/5366686113/jobs/9736247833)to test commit with build+test steps enabled on push.
> ci: fix amd build issue

- .github/workflows/ci.yml
- .github/workflows/docker-publish.yml
[This PR](https://github.com/Unstructured-IO/unstructured/pull/804) introduced a change to use the "docker" driver instead of the "docker-container" driver that docker/setup-buildx-action@v1 defaults to. This intermittently hits an issue with arm builds where the build fails with `exec /bin/sh: exec format error`. Because the original issue only affected AMD builds, this PR reverts the change specifically for ARM builds by making the driver condition on the architecture specified.
[Here](https://github.com/Unstructured-IO/unstructured/actions/runs/5383408561/jobs/9770135678) is a run showing this conditional driver logic working and passing the image build steps for both architectures.
> ci: fix arm build issue with docker driver

- CHANGELOG.md
- example-docs/hebrew-text-base64-iso88598i.txt
- test_unstructured/cleaners/test_core.py
- unstructured/__version__.py
- unstructured/cleaners/core.py
- unstructured/file_utils/encoding.py
- unstructured/file_utils/filetype.py
The Arabic (ISO-8859-6) and Hebrew (ISO-8859-8) charsets sometimes include -i or -e annotations to indicate order/direction of the characters. These annotated encodings are not recognized by the standard encodings in the Python codecs module itself (https://docs.python.org/3/library/codecs.html#standard-encodings). 
Closes #801. In order to be able to process documents in encodings such as ISO-8859-8-i, we can map them to their non-annotated encoding format.
This fix is not expected to handle base64 encodings, see #816 
```
from unstructured.partition.text import partition_text
filename = "example-docs/hebrew-text-base64-iso88598i.txt"
elements = partition(filename=filename, strategy="fast", encoding="iso-8859-8-i") …
```
> fix: format Arabic and Hebrew annotated encodings

- CHANGELOG.md
- test_unstructured/partition/test_image.py
- test_unstructured/partition/test_pdf.py
- unstructured/__version__.py
- unstructured/ingest/doc_processor/generalized.py
- unstructured/partition/common.py
- unstructured/partition/image.py
- unstructured/partition/pdf.py
Added the ability to select the `hi_res` model via the environment variable `UNSTRUCTURED_HI_RES_MODEL_NAME`. Variable must be a string that matches up with a model name defined in `unstructured_inference`.
Also removed code related to old `unstructured_inference` API which has been removed from currently pinned version of `unstructured-inference` and is no longer running as a service.
```python
import os
out = partition_pdf("example-docs/layout-parser-paper-fast.pdf", strategy="hi_res")
print(len(out))
os.environ["UNSTRUCTURED_HI_RES_MODEL_NAME"] = "yolox"
out_yolox = partition_pdf("example-docs/layout-parser-paper-fast.pdf", strategy="hi_res")
print(len(out_yolox))
```
> feat: choose model

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/ingest/interfaces.py
The skip_if_file_exists ingest decorator should skip downloading a file if it has already been downloaded. Currently, instead of checking if the source document exists in the download location, it's checking if the output file exists. This pr updates to check for the latter.
To test: 
* remove previous s3 outputs and any downloaded content `~/.cache/unstructured` and `./files-ingest-download`
* run `./test_unstructured_ingest/test-ingest-s3.sh`
* it should succeed
* remove downloaded content `~/.cache/unstructured` and `./files-ingest-download`
* run it again `./test_unstructured_ingest/test-ingest-s3.sh`
* before this pr: it should fail because it doesn't have the downloaded content
* after this pr: it should succeed because it downloads the content after recognizing it is not there
> fix: ingest download skipping

- .github/workflows/docker-publish.yml
Similar to the change [here](https://github.com/Unstructured-IO/unstructured/pull/843) to add api keys to ci testing, this adds the api key to the publish flow which tests the built images. Triggered a test publish flow (minus the final push of images) [here](https://github.com/Unstructured-IO/unstructured/actions/runs/5416102827/jobs/9845358298) to validate this change..
> fix: add api key to image publishing workflow tests

- CHANGELOG.md
- README.md
- docs/source/bricks.rst
- test_unstructured/partition/test_email.py
- test_unstructured/partition/test_msg.py
- unstructured/__version__.py
- unstructured/documents/elements.py
- unstructured/file_utils/filetype.py
- unstructured/partition/email.py
- unstructured/partition/msg.py
Closes #604. Adds the ability to process attachments to `partition_email` and `partition_msg`. The partitioning function to use with the attachments is set with `attachment_partitioner`. We can't set that automatically to `partition` since that would create a circular import. Adds an `attached_to_filename` to track the file the attached document was originally attached to.
```python
filename = "example-docs/eml/fake-email-attachment.eml"
elements = partition_email(
filename=filename, process_attachments=True, attachment_partitioner=partition
)
```
```python
from unstructured.partition.msg import partition_msg
filename = …
```
> feat: attachment processing for emails

- .github/workflows/docker-publish.yml
Fixes issue where arm64 docker builds were failing and preventing images from being published.
The latest main commit plus this branch (1st commit) has already been published in CI here: https://github.com/Unstructured-IO/unstructured/actions/runs/5428719470/jobs/9873272705
> build(image): docker build tweak for arm64

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/file_utils/filetype.py
This PR adds a missing space in a warning message in the `filetype.py` file.
> Add a missing space in a warning message in filetype.py

- CHANGELOG.md
- test_unstructured/staging/test_base_staging.py
- unstructured/staging/base.py
I don't have a reproducible example, but we continue to get API errors with the following stack. I suppose the safest thing is to skip an item that has no type, but happy to consider other behavior if we don't want to be silently ignoring data. Any suggestions for how to track down where these items are coming from?
> fix: Fix KeyError in isd_to_elements

- .pre-commit-config.yaml
- CHANGELOG.md
- test_unstructured_ingest/expected-structured-output/local-single-file/english-and-korean.png.json
- unstructured/__version__.py
- unstructured/ingest/connector/local.py
Fix _output_filename for local connector, allowing single files to be written correctly to the disk
To test, try ingesting a local file and a local folder. Expected outputs below.
```
python unstructured/ingest/main.py --local-input-path /Users/ahmet/Downloads/sample_pdf.pdf \
--verbose --partition-strategy fast --reprocess \
--structured-output-dir ~/output_dir
2023-07-04 14:00:05,176 SpawnPoolWorker-1 INFO     Processing /Users/ahmet/Downloads/sample_pdf.pdf
2023-07-04 14:00:05,176 SpawnPoolWorker-1 DEBUG    Using local partition
2023-07-04 14:00:05,225 SpawnPoolWorker-1 INFO     Wrote /Users/ahmet/output_dir/sample_pdf.pdf.json
```
```
python unstructured/ingest/main.py --local-input-path /Users/ahmet/Downloads/sample_folder \ 
--verbose --partition-strategy fast --reprocess \ …
```
> fix: local connector output filename when a single file is being processed

- .github/workflows/docker-publish.yml
arm64 Images (and amd64 ones) now building again 😐 , as per this github action: https://github.com/Unstructured-IO/unstructured/actions/runs/5471810374 .
> build(image): revert docker build tweak for arm64

- CHANGELOG.md
- requirements/local-inference.in
- requirements/local-inference.txt
- test_unstructured/partition/test_pdf.py
- unstructured/__version__.py
- unstructured/ingest/doc_processor/generalized.py
- unstructured/partition/pdf.py
To support unstructured-api in choosing between the default detectron model and the latest large model that was introduced, an optional parameter was added to use first before checking the environment variable which is the current behavior. 
To also support multiple models being, the `initialize()` method was also updated to check a new env var `UNSTRUCTURED_HI_RES_SUPPORTED_MODEL` which can be a comma-delimited string of all models to initialize explicitly.
> Add optional param for model name when partitioning pdfs

- CHANGELOG.md
- test_unstructured/staging/test_base_staging.py
- unstructured/__version__.py
- unstructured/staging/base.py
Closes #888. Updates `convert_to_dataframe` so that it grabs all of the metadata fields.
After running the following code, you should see `filename`, `file_directory` and `attached_to_filename` in the dataframe columns.
```python
from unstructured.staging.base import convert_to_dataframe
filename="example-docs/eml/fake-email-attachment.eml"
elements = partition_email(
filename=filename,
attachment_partitioner=partition,
process_attachments=True,
)
df = convert_to_dataframe(elements)
df.columns
```
> fix: grab all metadata fields in `convert_to_dataframe`

- CHANGELOG.md
- test_unstructured/file_utils/test_filetype.py
- unstructured/__version__.py
- unstructured/file_utils/filetype.py
- unstructured/partition/pdf.py
- unstructured/partition/text.py
https://github.com/Unstructured-IO/unstructured/pull/827 introduced an optional CoordinatesMetadata for each Element. As a safeguard, its constructor raises a ValueError on attempts to instantiate it with coordinate points and no coordinate system, or vice versa.
As a result, the following code raises a ValueError:
```
s.environ["UNSTRUCTURED_HI_RES_MODEL_NAME"] = "chipper"
os.environ["UNSTRUCTURED_HF_TOKEN"] = "redacted"
filename = "/path/to/chevron-page.pdf"
elements = partition(filename=filename, strategy="hi_res") 
```
It goes through this code path:
In unstructured_inference, `process_file_with_model` returns a PageLayout object that has an image attribute. Therefore, the unstructured library resolves a coordinate system here: …
> Don't instantiate an element with a coordinate system when there isn't a way to get its location

- docs/source/bricks.rst
- docs/source/getting_started.rst
Closes #693. Adds more detailed documentation on `partition_via_api` and table extraction capabilities.
> docs: update table and API documentation

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/file_utils/filetype.py
Related to #886. Adds `.txt`, `.text` and `.tab` to the list of file extension to check if a file has a `text/plain` MIME type.
> fix: adds to list of extensions to check if a file has a plain text MIME type

- docs/source/bricks.rst
Adding the source code for each brick in bricks.rst, and resorting partition_tsv and partition_org to keep alphabetical order.
I added only the file link for the source code links and not the line of the particular function to keep it maintainable.
> docs: Add source code links to bricks' docs

- CHANGELOG.md
- unstructured/partition/pptx.py
This adds the ability to gather the notes on the slides. 
Added a new argument `include_slide_notes` to `partition_pptx.` This defaults to `False` to stay backwards compatible.
PPTX API Reference https://python-pptx.readthedocs.io/en/latest/user/notes.html
> Add slide notes to pptx

- CHANGELOG.md
- docs/source/bricks.rst
- test_unstructured/partition/test_html_partition.py
- test_unstructured_ingest/expected-structured-output/azure/spring-weather.html.json
- test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/1605956.json
- test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/229477.json
- test_unstructured_ingest/expected-structured-output/confluence-diff/testteamsp/1605859.json
- test_unstructured_ingest/expected-structured-output/confluence-diff/testteamsp/1605989.json
- test_unstructured_ingest/expected-structured-output/confluence-diff/testteamsp/1802252.json
- test_unstructured_ingest/expected-structured-output/confluence-diff/~64083457896d10ebd4738661/65627.json
- test_unstructured_ingest/expected-structured-output/confluence-diff/~64083457896d10ebd4738661/65628.json
- test_unstructured_ingest/expected-structured-output/confluence-diff/~7120205368eedfcecd43e18b25b2221316ee6f/2130016.json
- test_unstructured_ingest/expected-structured-output/gcs/ideas-page.html.json
- test_unstructured_ingest/expected-structured-output/gcs/nested-1/nested/ideas-page.html.json
- test_unstructured_ingest/expected-structured-output/gcs/nested-2/nested/ideas-page.html.json
- test_unstructured_ingest/expected-structured-output/github/test.html.json
- unstructured/__version__.py
- unstructured/documents/elements.py
- unstructured/documents/html.py
- unstructured/partition/common.py
- unstructured/staging/weaviate.py
Closes #556. Updates `partition_html` to track links in metadata when anchor tags are present. 
```python
html_text = """<html>
<p>Hello there I am a <a href="/link">very important link!</a></p>
<p>Here is a list of my favorite things</p>
<ul>
<li><a href="https://en.wikipedia.org/wiki/Parrot">Parrots</a></li>
<li>Dogs</li>
</ul>
<a href="/loner">A lone link!</a>
</html>"""
elements = partition_html(text=html_text)
```
> feat: track links from anchor tags in `partition_html`

- CHANGELOG.md
- unstructured/__version__.py
Cleans up the CHANGELOG for the `0.8.2` release
> chore: cleanup changelog for 0.8.2

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/nlp/tokenize.py
Closes #610. Updates the `tokenize` module so that NLTK packages are only downloaded if they are going to be used rather than downloading them at the top level of the module.
> fix: only download nltk packages if necessary

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/partition/text.py
Put the function back since the notebook in API repo is using it, and is helpful in the future.
> Chore: put back function `split_by_paragraph`

- CHANGELOG.md
- docs/source/api.rst
- unstructured/__version__.py
as of `0.0.33` prod API, we have a new partition parameter `include_page_break`, add this in doc to reflect changes
> doc: update API doc to sych with new parameter in prod API

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
To enable merge queues for the unstructured repo, which will allow more users to commit changes simultaneously without having to manually upgrade their branches to latest.
Reference:
https://github.blog/changelog/2022-08-18-merge-group-webhook-event-and-github-actions-workflow-trigger/
> build: enable merge_group checks

- CHANGELOG.md
- test_unstructured_ingest/check-num-files-output.sh
- unstructured/__version__.py
Comparing variable values with `-ne` rather than `!=` fixes issue where matching expected values fails specifically for ingest tests in a Docker container.
I validated this by running this before and after the change:
`make docker-build`
`make docker-smoke-test`
Before this change, the comparison failed despite comparing equal values. Now it succeeds.
> fix: ingest test check num files in smoke test

- scripts/version-sync.sh
We only want one commit to correspond to a release, so this change checks if a non-dev version is identical to a previous commit release version.
Manual version changes to test the cases below. Print statements included temporarily for visibility.
no errors (Unaffected by current PR)
Error: out of sync (Unaffected by current PR)
Error: already a commit for this release version
Error: already a commit for this release version
Error: out of sync
no errors
> Update `make check-version` script to fail if release version is unchanged

- CHANGELOG.md
- test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper.pdf.json
- test_unstructured_ingest/test-ingest-local-single-file-with-encoding.sh
- test_unstructured_ingest/test-ingest-local-single-file-with-pdf-infer-table-structure.sh
- test_unstructured_ingest/test-ingest.sh
- unstructured/__version__.py
- unstructured/ingest/cli/common.py
- unstructured/ingest/interfaces.py
- unstructured/ingest/processor.py
- unstructured/partition/auto.py
* adding --partition-pdf-infer-table-structure to unstructured-ingest
* check there are field `"text_as_html"` for extracted tables in output json file
all partition parameters are not passing into request correctly when use together with `partition-by-api`, so currently we have to stick with local partition (will be fixed soon).
> Chore[ingest]: adding parameter --partition-pdf-infer-table-structure

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/ingest/main.py
The library entrypoint for ingest `unstructured-ingest` was broken with the recent refactor. This is because the main function which is accessed here: https://github.com/Unstructured-IO/unstructured/blob/7f9340ce00a23f71f9348d9f8e542ba86a79753f/setup.py#L105 was removed from `unstructured/ingest/main.py`
* add main function back to `unstructured/ingest/main.py`
On the main branch, run `pip install -e .` to install the latest local version of the unstructured library. Then validate the broken state by running `PYTHONPATH=. unstructured-ingest --help` which results in: 
```
Traceback (most recent call last):
File "~/.pyenv/versions/unstructured/bin/unstructured-ingest", line 5, in <module>
from unstructured.ingest.main import main
ImportError: cannot import name 'main' from …
```
> fix: unstructured-ingest entrypoint

- docs/source/bricks.rst
- unstructured/partition/epub.py
- unstructured/partition/rtf.py
Fixes a typo in several places where the word `partition` is misspelled as `partiton`
> docs: correct spelling of partition in docs

- CHANGELOG.md
- example-docs/eml/email-equals-attachment-filename.eml
- test_unstructured/partition/test_email.py
- unstructured/partition/email.py
Fix attachments with `=` in filename
* Limit `split` to first match of `=` to prevent creating a list of more than two parts
* Add example email with attachment name and test for issue
> Fix attachments with `=` in filename

- CHANGELOG.md
- requirements/constraints.in
- requirements/extra-pdf-image.txt
- unstructured/__version__.py
Pulls in @awalker4 's fix:
https://github.com/Unstructured-IO/unstructured-inference/pull/178
> When a pdf page doesn't have much data, it may get buffered in the write to a tempfile. If this happens, we'll hit an error reading the file back. Open to suggestions for a way to unit test this - I was creating some test files with pypdf but I couldn't trigger the error.
>  build(deps): bump unstructured-inference to 0.5.12

- CHANGELOG.md
- unstructured/__version__.py
0.10.2 had been released, but  prior commit co-mingled 0.10.2 and 0.10.3. This corrects the changelog and intentionally skips over 0.10.3.
Bonus: remove accidental dupe line in 0.10.0.
> chore: changelog repair

- test_unstructured/partition/test_api.py
The reason this test is failing is the API is returning "fast" results when "hi_res" is requested, which is being tracked in this ticket: https://github.com/Unstructured-IO/unstructured-api/issues/188 .
This failure was only showing up on the `main` branch, per the commented out `pytest` skips.
> chore: skip consistently failing test in main

- docs/source/upstream_connectors/wikipedia.rst
The Wikipedia data connector was labeled as Airtable.
> Fixed some typos

- CHANGELOG.md
- setup.py
- test_unstructured/partition/test_auto.py
- unstructured/__version__.py
- unstructured/partition/auto.py
Updates `partition` to let users know to installs the appropriate extras if they're missing. Prior to this PR, users would get an exception stating `partition_pdf` (or whichever function that requires extras) does not exist.
First `pip uninstall ebooklib`. Then run
```python
partition(filename="example-docs/winter-sports.epub")
```
The error should look like
```python
ImportError: partition_epub is not available. Install the epub dependencies with pip install "unstructured[epub]"
```
> enhancement: tell users to install missing extras

- CHANGELOG.md
- docs/source/bricks/partition.rst
- test_unstructured/partition/test_api.py
- test_unstructured/partition/test_auto.py
- unstructured/__version__.py
- unstructured/partition/api.py
- unstructured/partition/auto.py
- unstructured/partition/epub.py
Closes #1007. Adds a deprecation warning for the `file_filename` kwarg to `partition`, `partition_via_api`, and `partition_multiple_via_api`. Also catches a warning in `ebooklib` that we do not want to emit in `unstructured`.
```python
filename = "example-docs/winter-sports.epub"
with open(filename, "rb") as f:
elements = partition(file=f, metadata_filename="test.epub")
elements[0].metadata.filename
with open(filename, "rb") as f:
elements = partition(file=f, file_filename="test.epub")
elements[0].metadata.filename
with open(filename, "rb") as f:
elements = partition(file=f, metadata_filename="test.epub", file_filename="test.epub")
```
> chore: deprecation warning for `file_filename`

- requirements/constraints.in
- requirements/extra-pdf-image.txt
- requirements/huggingface.txt
The build for ARM fails when attempting to build safetensors 0.3.3. This PR rolls it back to 0.3.2 by adding a constraint and building dependencies
* adds constraint for safetensors
* bumps dependencies
> fix: ARM build with constraint for safetensors <=0.3.2

- Makefile
Removed a duplicate make target in the `Makefile`.
> fix: remove duplicate target in makefile

- .github/workflows/docker-publish.yml
- scripts/docker-smoke-test.sh
Moving to a non-root user in the docker image caused a failure in the publication workflow.
This fix was used to publish the 0.10.9 unstructured image in this workflow:
https://github.com/Unstructured-IO/unstructured/actions/runs/6020624226/job/16332230987
> build: docker image fix

- .gitignore
- test_unstructured_ingest/.gitignore
We recently added plain-text comparison during the ingest testing. This generates files in `test_unstructured_ingest/expected-text-output/`. It looks like the intent was that these files are to be generated but ignored in git. However, the paths relative to the root of the repo were used instead of paths relative to the `.gitignore` file in which they were added. This updates those paths so that the `test_unstructured_ingest/expected-text-output/` and `test_unstructured_ingest/text-output` paths are ignored. Additionally a `outputdiff.txt` file is generated at the root of the repo. This will change with each test, so presumably we don't want that checked in either. This also adds that to the gitignore.
I ran an ingest test which generated some of these text comparison files. I updated …
> fix: update .gitignores to include text comparison files

- CHANGELOG.md
- requirements/constraints.in
- requirements/extra-pdf-image.txt
- requirements/test.txt
- test_unstructured_ingest/expected-structured-output/azure/Core-Skills-for-Biomedical-Data-Scientists-2-pages.pdf.json
- test_unstructured_ingest/expected-structured-output/azure/IRS-form-1987.pdf.json
- test_unstructured_ingest/expected-structured-output/azure/IRS-form-1987.png.json
- test_unstructured_ingest/expected-structured-output/biomed-api/65/11/main.PMC6312790.pdf.json
- test_unstructured_ingest/expected-structured-output/biomed-api/75/29/main.PMC6312793.pdf.json
- test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper.pdf.json
- test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/2023-Jan-economic-outlook.pdf.json
- test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/Silent-Giant-(1).pdf.json
- test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/recalibrating-risk-report.pdf.json
- unstructured/__version__.py
Bumps unstructured-inference==0.5.19 to bring in @christinestraub's enhancement
https://github.com/Unstructured-IO/unstructured-inference/pull/186 .
This is a **massive** improvement where previously omitted text was not included in `hi_res` output if the layout model had not put a bounding box around it. In addition, the xycut sorting algorithm generally does a good job of ordering the merged OCR-text-not-in-layout-model bboxes with layout-model bboxes into "natural reading order." More details in https://github.com/Unstructured-IO/unstructured-inference/pull/186#issuecomment-1700438645 .
Bonus: changelog fix.
> enhancement: entire page OCR output included with hi_res

- CHANGELOG.md
- scripts/version-sync.sh
- unstructured/__version__.py
The check to verify version changes has recently permitted commits with the same release version to merge; the intention is that this should be prevented.
The issue is that the version-sync script's call to get the version on `main` attempts to look at the local main branch. When this doesn't exist the variable MAIN_VERSION is assigned to an empty value rather than a semantic version string. This means that later comparisons are meaningless. [Here](https://github.com/ryannikolaidis/unstructured/actions/runs/6045554705/job/16405814607#step:6:77) is an example of the script "succeeding" with this condition.
Instead, this PR adds logic to fetch origin main and compare against the version value there. It also adds `set -eux` at the top of the script so we can debug issues if they come up in …
> fix: version-sync

- CHANGELOG.md
- Makefile
- requirements/constraints.in
- requirements/dev.txt
- requirements/extra-pdf-image.in
- requirements/extra-pdf-image.txt
- requirements/extra-pptx.in
- requirements/extra-pptx.txt
- requirements/ingest-gcs.txt
- requirements/test.txt
- unstructured/__version__.py
Removed pin for `PIL` as `detectron2` repo has been updated, and so has `unstructured-inference` (see [154](https://github.com/Unstructured-IO/unstructured-inference/pull/154)).
Any problems should have shown up as a unit test failure in `unstructured-inference` (that tests with `PIL==10.0.0`) so we should be good to go.
> build(deps): Remove pillow pin

- CHANGELOG.md
- test_unstructured/cleaners/test_core.py
- unstructured/cleaners/core.py
[Ligatures](https://en.wikipedia.org/wiki/Ligature_(writing)#Ligatures_in_Unicode_(Latin_alphabets)) can sometimes show up during the text extraction process when they should not. Very common examples of this are with the Latin `f` related ligatures which can be **very subtle** to spot by eye (see example below), but can wreak havoc later.
```python
"ﬀ": "ff",
"ﬁ": "fi",
"ﬂ": "fl",
"ﬃ": "ffi",
"ﬄ": "ffl",
```
Several libraries already do something like this. Most recently, `pdfplumber` added this sort of capability as part of the text extraction process, see https://github.com/jsvine/pdfplumber/issues/598
Instead of incorporating any sort of breaking change to the PDF text processing in `unstructured`, it is best to add this as another cleaner and allow users to opt in. In turn, the …
> Add clean_ligatures to core cleaners

- CHANGELOG.md
- requirements/constraints.in
- requirements/dev.txt
- requirements/extra-pdf-image.txt
- requirements/ingest-azure.txt
- requirements/ingest-confluence.txt
- requirements/ingest-jira.txt
- requirements/test.txt
- test_unstructured_ingest/expected-structured-output/biomed-api/65/11/main.PMC6312790.pdf.json
- test_unstructured_ingest/expected-structured-output/biomed-api/75/29/main.PMC6312793.pdf.json
- test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper.pdf.json
- test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/2023-Jan-economic-outlook.pdf.json
- test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/Silent-Giant-(1).pdf.json
- test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/recalibrating-risk-report.pdf.json
- unstructured/__version__.py
Bumps unstructured-inference==05.23 to pull in @christinestraub's fix:
https://github.com/Unstructured-IO/unstructured-inference/pull/198 , so embedded Images
in PDF's are now included in partition results ("hi_res").
From the perspective of elements with clean text, this is not a big win as a lot of the images have OCR garbage. However, it is important to preserve image elements for other downstream use cases, so overall this is a step forward.
> build(deps): PDF images, unstructured-inference==0.5.23

- CHANGELOG.md
- test_unstructured/file_utils/test_filetype.py
- unstructured/file_utils/filetype.py
Addressed the issue #494 .
Updated the `_detect_filetype_from_octet_stream()` function to use libmagic to infer the content type of file when it is not a zip file.
> Chore: Libmagic detection for "application/octet-stream" when  it is not a zip file.

- scripts/version-sync.sh
Remove -x in version-sync script to stop printing all commands and arguments and improve readability.
`make check` and `make check-version` no longer print all the commands and arguments.
```
(unstructured) shreyanid@Shreyas-MBP-2 unstructured % make check-version 
scripts/version-sync.sh -c \
-f "unstructured/__version__.py" semver
From github.com:Unstructured-IO/unstructured
* branch              main       -> FETCH_HEAD
version sync would make no changes to unstructured/__version__.py.
```
> stop printing all commands in version-sync script

- CHANGELOG.md
- docs/source/api.rst
- example-docs/fake-doc.rtf
- scripts/version-sync.sh
- test_unstructured/partition/epub/test_epub.py
- test_unstructured/partition/pypandoc/test_rtf.py
- unstructured/__version__.py
- unstructured/partition/auto.py
This PR does two things:
1. Adds test case (and alters sample doc) for rtf and epub files with table
2. Adds `xls/x` file extension to `skip_infer_table_types` default list
> Table processing test for RTF

- CHANGELOG.md
- test_unstructured/partition/pdf-image/test_image.py
- unstructured/__version__.py
- unstructured/partition/image.py
In order to support language functionality other than Tesseract OCR, we want to represent languages provided for either partitioning accuracy or OCR as a standard list of langcodes as strings.
Follows the pattern established with PDFs in #1334. Adds languages (a list of strings) as a parameter to `partition_image`. Marks ocr_languages for deprecation. 
Call partition_image or partition_pdf_or_image with a variety of strategies, languages, or ocr_languages.
- inclusion of ocr_languages as a parameter should display a deprecation warning and may proceed with partitioning if no other conflicts
- the other valid call outputs should be no different from the current outputs.
ex:
```
from unstructured.partition.image import partition_image
elements = …
```
> chore: refactor languages parameter for image partition functions

- CHANGELOG.md
- test_unstructured/partition/test_auto.py
- unstructured/__version__.py
- unstructured/partition/auto.py
In order to support language functionality other than Tesseract OCR, we want to represent languages provided for either partitioning accuracy or OCR as a standard list of langcodes as strings.
Follows the pattern established with PDFs in #1334. Adds languages (a list of strings) as a parameter to partition in auto.py. Marks ocr_languages for deprecation.
Call partition with a variety of filetypes (especially pdfs/images), strategies, languages, or ocr_languages.
- inclusion of ocr_languages as a parameter should display a deprecation warning and may proceed with partitioning if no other conflicts
- the other valid call outputs should be no different from the current outputs
> chore: refactor languages parameter for auto partition

- CHANGELOG.md
- test_unstructured/partition/test_text_type.py
- unstructured/__version__.py
- unstructured/partition/text_type.py
In order to support language functionality other than Tesseract OCR, we want to represent languages provided for either partitioning accuracy or OCR as a standard list of langcodes as strings. To identify element types such as NarrativeText and Title, continue the refactor into functions that use language checks to determine those potential classifications.
Replaces `language` with `languages` (a list of strings) as a parameter to `is_possible_narrative_text` and `is_possible_title`. Removes the `UNSTRUCTURED_LANGUAGE` environment variable and its usages.
Call `is_possible_narrative_text` and `is_possible_title` with text in a variety of languages and different inputs for `languages`. The resulting element classifications should be no different from the current outputs.
ex: see …
> chore: refactor languages parameter for text_type functions

- CHANGELOG.md
- test_unstructured/chunking/test_title.py
- unstructured/__version__.py
- unstructured/chunking/title.py
Closes https://github.com/Unstructured-IO/unstructured/issues/1373
This PR: 
- drops the `coordinates`  metadata field in `chunk_by_title` to fix https://github.com/Unstructured-IO/unstructured/issues/1373 (read issue for the details)
- adds relevant test that checks the particular case
> fix: coordinates metadata hinders chunking

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/documents/elements.py
This PR updates [TYPE_TO_TEXT_ELEMENT_MAP](https://github.com/Unstructured-IO/unstructured/blob/bd33a52ee0fcec3928db171e6d717e70521c5aef/unstructured/documents/elements.py#L551) with additional mapping for `chipper` elements:
```
“Threading”: NarrativeText,
“Form”: NarrativeText,
“Field-Name”: Title,
“Value”: NarrativeText,
“Link”: NarrativeText,
```
> feat: improved mapping for missing chipper elements

- test_unstructured_ingest/test-ingest.sh
There is a fix in progress here: https://github.com/Unstructured-IO/unstructured/pull/1492 , but let's see proven stability of a few days before allowing notion ingest test failures to block CI.
> build(test): ignore notion ingest test failures for now

- README.md
We've created a custom domain, downloads.unstructured.io that redirects to quay.io
(using https://scarf.sh/). This custom domain allows us to swap the
underlying container registry without impacting users. It also provides
us with important metrics about container and package usage, without surfacing PII
like IP addresses.
Python package follows the same pattern at packages.unstructured.io
> Add notification that we will be utilizing scarf for docker and python downloads

- README.md
Related to: https://github.com/Unstructured-IO/unstructured#chart_with_upwards_trend-analytics
Testing:
`docker pull downloads.unstructured.io/unstructured-io/unstructured:latest`
There should be no additional steps needed.
> Chore: Update readme to using new download location to track download metrics

- test_unstructured_ingest/test-ingest.sh
We test the Airtable source connector through a detailed diff test and a "large" test that pulls a lot of content over the course of a lot of requests (for 246 docs). This is triggering `HTTP 429 Too Many Requests` errors when several tests are running in parallel in CI. In the meantime it's probably okay for us to skip that particular test in CI while keeping coverage in the diff test.
> build(test): disable airtable-large ingest test

- docs/source/installation/docker.rst
This updates the docker image download url to pass through the scarf gateway, this allows anonymous tracking of downloads
Related to: https://github.com/Unstructured-IO/unstructured#chart_with_upwards_trend-analytics
Testing:
docker pull downloads.unstructured.io/unstructured-io/unstructured:latest
Result:
Image should download
> Update docker download url to use scarf gateway

- CHANGELOG.md
- test_unstructured_ingest/files/azure_cognitive_index_schema.json
- test_unstructured_ingest/test-ingest-sharepoint-embed-cog-index.sh
- unstructured/__version__.py
- unstructured/embed/openai.py
- unstructured/ingest/cli/cmds/azure_cognitive_search.py
- unstructured/ingest/cli/cmds/sharepoint.py
- unstructured/ingest/cli/interfaces.py
- unstructured/ingest/connector/sharepoint.py
- unstructured/ingest/doc_processor/generalized.py
- unstructured/ingest/interfaces.py
- unstructured/ingest/runner/base_runner.py
- unstructured/ingest/runner/sharepoint.py
Optionally adds in chunking to the CLI which adds a flag to trigger chunking and exposes the parameters used by the `chunk_by_title` method. Runs chunking before the embedding step. 
Opened to replace original PR https://github.com/Unstructured-IO/unstructured/pull/1531
> Chunking support for SharePoint Connector

- requirements/base.in
- requirements/base.txt
- setup.py
This also follows what I have seen as the recommend way to define a file package like this.
Also bumps minor versions from pip compile
Testing:
`pip install -e .`
Everything should build as normal
`❯ pip install -e .
Obtaining file:///Users/trevor/dev/unstructured
Installing build dependencies ... done
Checking if build backend supports build_editable ... done
Getting requirements to build editable ... done
Preparing editable metadata (pyproject.toml) ... done
Collecting scarf@ https://packages.unstructured.io/scarf.tgz (from unstructured==0.10.17.dev16)
Using cached https://packages.unstructured.io/scarf.tgz (1.1 kB)
Installing build dependencies ... done
Getting requirements to build wheel ... done
Preparing metadata (pyproject.toml) ... done`
When new release goes out, I will test just …
> Chore: move scarf to setup.py

- CHANGELOG.md
- test_unstructured/documents/test_html.py
- unstructured/documents/html.py
Fix 4 cases of text missing after partition:
1. Text immediately after `<body>`
```html
<body>
missing1
<div>hello</div>
</body>
```
2. Text inside container and immediately after `<br/>`
```html
<div>hello<br/>missing2</div>
```
3. Text immediately after a text opening tag, if said tag contains `<br/>`
```html
<p>missing3<br/>hello</p>
```
4. Text inside `<body>` if it is the only content (different cause from case 1)
```html
<body>missing4</body>
```
Also fix problem causing `test_unstructured/documents/test_html.py::test_exclude_tag_types` to not work as intended.
This will close #1543
> fix: Fix various cases of HTML text missing after partition

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/file_utils/metadata.py
In a different PR, some no-extras tests started failing with import errors when something innocuous was imported from `unstructured.file_utils.metadata`. This turned out to be because of the top-level, doctype-specific imports in that file. Importing a general metadata object shouldn't require installation of modules like `PIL`, `docx`, and `openpyxl`.
To fix, I moved these functions to be imported inside the functions that use them, and added the `requires_dependencies` decorator to the functions.
You should be able to run something like:
```python
from unstructured.file_utils.metadata import Metadata
```
Without `openpyxl` installed.
> fix: isolate metadata imports to doctype

- test_unstructured_ingest/cleanup.sh
When running test-ingest test fixtures locally (but not in CI), keep output .json's and other workdir artifacts around for the convenience of debugging.
**Test Instructions**
Run 
bash -x ./test_unstructured_ingest/test-ingest-azure.sh
and witness output .json's are visible. Yay! Now, to instead clean up output .json's and workdir, run:
UNSTRUCTURED_CLEANUP_DEV_FIXTURES=1 bash -x ./test_unstructured_ingest/test-ingest-azure.sh
and witness the files have been cleaned up. Yay!
> chore: don't cleanup ingest test outputs (non-CI)

- .github/workflows/ingest-test-fixtures-update-pr.yml
- test_unstructured_ingest/test-ingest.sh
We’re probably unfairly (to the test) making a large volume of new connections and requests to test services when all of our ingest tests run across the full python test matrix and when a lot of PRs a firing at once. Lets limit the full matrix run to a select few, but still have all ingest tests run on python v3.10. This is done by checking the version and skipping in ingest-test.sh.
Bonus: Bumps ingest test fixture workflow to use 3.10. This technically shouldn't make a difference, but since we're making 3.10 the default of the matrix strategy, it probably makes sense to use 3.10 for the ingest fixture generation as well for consistency.
- [example](https://github.com/Unstructured-IO/unstructured/actions/runs/6460319121/job/17537900978?pr=1687) running all tests in 3.10
- …
> build(test): skip full python matrix for most ingest tests

- CHANGELOG.md
- test_unstructured/metrics/test_text_extraction.py
- unstructured/__version__.py
- unstructured/metrics/text_extraction.py
Missing text is a particularly important metric of quality for the Unstructured library because information from the document is not being captured and therefore not usable by downstream applications.
Add function to calculate the percent of text missing relative to the source transcription. Function takes 2 text strings (output and source) as input, and returns the percentage of text missing as a decimal.
- The 2 input strings are both assumed to already contain clean and concatenated text (CCT)
- Implementation compares the bags of words (frequency counts for each word present in the text) of each input text
- Duplicated/extra text is not penalized
- Value is limited to the range [0, 1]
- Several edge cases are covered in the test function (missing text, duplicated text, spaced out …
> feat: calculate metric for percent of text missing

- CHANGELOG.md
- Makefile
- README.md
- unstructured/__version__.py
It’s no longer required to specify the extra index url as we utilize a different method of gathering install anonymous analytics.
> Remove extra index url from docs

- CHANGELOG.md
- test_unstructured/partition/test_text_type.py
- unstructured/__version__.py
- unstructured/partition/text_type.py
The function `under_non_alpha_ratio` in `unstructured.partition.text_type` was producing a divide-by-zero error. After investigation I found this was a possibility when the function was passed a string of all spaces.
> fix: zero divide in under_non_alpha_ratio

- CHANGELOG.md
- unstructured/__version__.py
Fix https://github.com/Unstructured-IO/unstructured-api/issues/286 where `partition/utils/ocr_models` folder is not uploaded to PyPI since its missing an `__init__.py` file
> Fix: ModuleNotFoundError for `partition.utils.ocr_models`

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/partition/pdf.py
Closes #1763.
**Import PDFResourceManager more directly** We were importing `PDFResourceManager` from `pdfminer.converter` which was causing an error for some users. We changed to import from the actual location of `PDFResourceManager`, which is `pdfminer.pdfinterp`.
Importing `partition_pdf` should raise an error on `main` if `pdfminer.six` is version `20201018` but on this branch it will import successfully.
> fix: import PDFResourceManager from pdfinterp

- CHANGELOG.md
- test_unstructured/chunking/test_title.py
- test_unstructured/documents/test_elements.py
- test_unstructured_ingest/test-ingest.sh
- unstructured/chunking/title.py
- unstructured/partition/html.py
**Executive Summary.** Introducing strict type-checking as preparation for adding the chunk-overlap feature revealed a type mismatch for regex-metadata between chunking tests and the (authoritative) ElementMetadata definition. The implementation of regex-metadata aspects of chunking passed the tests but did not produce the appropriate behaviors in production where the actual data-structure was different. This PR fixes these two bugs.
1. **Over-chunking.** The presence of `regex-metadata` in an element was incorrectly being interpreted as a semantic boundary, leading to such elements being isolated in their own chunks.
2. **Discarded regex-metadata.** regex-metadata present on the second or later elements in a section (chunk) was discarded.
**Technical Summary**
The type of …
> fix: chunks break on regex-meta changes and regex-meta start/stop not adjusted

- CHANGELOG.md
- unstructured/__version__.py
Fix `ModuleNotFoundError: No module named 'unstructured.metrics'` where the unstructured/metrics folder is not discoverable from a package import since its missing an __init__.py file.
> fix: ModuleNotFoundError for unstructured metrics folder

- CHANGELOG.md
- test_unstructured/partition/pdf_image/test_pdf.py
- unstructured/__version__.py
- unstructured/file_utils/filetype.py
This PR resolves #1754 
- function wrapper tries to use `cast` to convert kwargs into `str` but when a value is `None` `cast(str, None)` still returns `None`
- fix replaces the conversion to simply using `str()` function call
> fix: model_name being None raises attribution error

- CHANGELOG.md
- unstructured/metrics/text_extraction.py
Add `calculate_accuracy` function that is a wrapper of `calculate_edit_distance` that returns the "score".
> feat: add accuracy as wrapper for edit distance score

- CHANGELOG.md
- test_unstructured/partition/test_html_partition.py
- unstructured/__version__.py
- unstructured/documents/html.py
This PR resolves #1807 
- fix a bug where when a table tagged content does not contain `tbody` tag but `thead` tag for the rows the code fails
- now when there is no `tbody` in a table section we try to look for `thead` isntead
- when both are not found return empty table
> fix: partition html fail with table without tbody

- test_unstructured/partition/pdf_image/test_pdf.py
Closes [#93](https://github.com/Unstructured-IO/unstructured-inference/issues/93).
Adds a test to ensure language parameters are passed all the way from `partition_pdf` down to the OCR calls.
CI should pass.
> test: Add test to ensure languages trickle down to ocr

- CHANGELOG.md
- test_unstructured/chunking/test_title.py
- unstructured/chunking/title.py
**Executive Summary.** Perhaps the most commonly specified option for `chunk_by_title()` is `max_characters` (default: 500), which specifies the chunk window size.
When a user specifies this value, they get an error message:
```python
>>> chunks = chunk_by_title(elements, max_characters=100)
ValueError: Invalid values for combine_text_under_n_chars, new_after_n_chars, and/or max_characters.
```
A few of the things that might reasonably pass through a user's mind at such a moment are:
* "Is `110` not a valid value for `max_characters`? Why would that be?"
* "I didn't specify a value for `combine_text_under_n_chars` or `new_after_n_chars`, in fact I don't know what they are because I haven't studied the documentation and would prefer not to; I just want smaller chunks! How could I supply an …
> fix: chunk_by_title() interface is rude

- CHANGELOG.md
- test_unstructured/partition/pdf_image/test_image.py
- unstructured/__version__.py
- unstructured/file_utils/filetype.py
- unstructured/partition/image.py
Closes [#1859](https://github.com/Unstructured-IO/unstructured/issues/1859).
* **Fixes elements partitioned from an image file missing certain metadata** Metadata for image files, like file type, was being handled differently from other file types. This caused a bug where other metadata, like the file name, was being missed. This change brought metadata handling for image files to be more in line with the handling for other file types so that file name and other metadata fields are being captured.
Additionally:
* Added test to verify filename is being captured in metadata
* Cleaned up `CHANGELOG.md` formatting
The following produces output `None` on `main`, but outputs the filename `layout-parser-paper-fast.jpg` on this branch:
```python …
```
> fix: filename missing from image metadata

- CHANGELOG.md
- test_unstructured/chunking/test_title.py
- unstructured/__version__.py
- unstructured/chunking/title.py
**Executive Summary.** A primary responsibility of the sectioner is to minimize the number of chunks that need to be split mid-text. It does this by computing text-length of the section being formed and "finishing" the section when adding another element would extend its text beyond the window size.
When element-text is consolidated into a chunk, the text of each element is joined, separated by a "blank-line" (`"\n\n"`). The sectioner does not currently consider the added length of separators (2-chars each) and so forms sections that need to be split mid-text when chunked.
Chunk-splitting should only be necessary when the text of a single element is longer than the chunking window.
**Example**
```python
elements: List[Element] = [
Title("Chunking Priorities"),  # 19 chars
ListItem("Divide …
```
> fix: sectioner does not consider separator length

- .github/workflows/ci.yml
Updated CI to shave time off in some conditions with no real downside.
- When the base cache already exists, we don't download it during setup, and we skip all other steps as well.
- During ingest setup, we check if the ingest cache exists before downloading the base cache, and if the ingest cache already exists, we skip everything else.
- `check-deps` doesn't have to wait on `setup` or download a cache, as the dependencies aren't needed, only `pip`.
| CI version | Setup (on hit) | Ingest Setup (on hit) | Check deps (on hit) |
| ---------- | --------- | ------------ | -------- |
| Old     | 2:06-2:31  | 3:07-3:31  | 3:19-6:26 |
| New   | 0:08-0:09  |  0:07-0:09 | 2:05-2:23 |
- Results of cache hits (best case scenario) can be seen …
> build: streamline ci

- Makefile
Show which tests are slowing things down when running `make test`:
E.g., from the CI run in this PR:
```
2023-10-27T05:51:05.6256039Z 105.12s setup    test_unstructured/partition/pdf_image/test_pdf.py::test_chipper_has_hierarchy
2023-10-27T05:51:05.6257784Z 93.47s call     test_unstructured/partition/pdf_image/test_pdf.py::test_partition_pdf_hi_res_ocr_mode_with_table_extraction[entire_page]
2023-10-27T05:51:05.6259866Z 93.09s call     test_unstructured/partition/pdf_image/test_pdf.py::test_partition_pdf_hi_res_ocr_mode_with_table_extraction[individual_blocks]
2023-10-27T05:51:05.6261818Z 31.70s call     test_unstructured/partition/epub/test_epub.py::test_add_chunking_strategy_on_partition_epub_non_default
2023-10-27T05:51:05.6263774Z 17.22s call …
```
> test: print slowest unittests

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/partition/utils/ocr_models/paddle_ocr.py
The logger from `paddle_ocr.py` is wrong, it should be `from unstructured.logger` since the module is in unst repo
* install this branch of unst to an unst-api env with `pip install -e .`
* in unst-api repo, run `OCR_AGENT=paddle make run-web-app`
* curl with:
```
curl -X 'POST'   'http://0.0.0.0:8000/general/v0/general' \
-H 'accept: application/json'  \
-H 'Content-Type: multipart/form-data'  \
-F 'files=@sample-docs/layout-parser-paper.pdf'  \
-F 'strategy=hi_res'  \
-F 'pdf_infer_table_structure=True' \
| jq -C . | less -R
```
you should be able to see log like 
```
2023-10-27 10:31:48,691 unstructured INFO Processing OCR with paddle...
2023-10-27 10:31:48,969 unstructured INFO Loading paddle with CPU on language=en...
```
not 
```
2023-10-27 10:16:08,654 unstructured_inference INFO …
```
> Fix: replace wrong logger for paddle info 

- .github/workflows/ci.yml
temporarily, until large workers are working again.
> build: re-enable ingest on normal CI workers

- .github/workflows/ingest-test-fixtures-update-pr.yml
Run fixtures-update workflow on smaller github runner until larger one is available again.
> build(fixtures-update): run on smaller worker

- CHANGELOG.md
- test_unstructured/chunking/test_title.py
- unstructured/chunking/title.py
**Executive Summary**. Section titles are often combined with the prior section and then missing from the section they belong to.
_Chunk combination_ is a behavior in which two succesive small chunks are combined into a single chunk that better fills the chunk window. Chunking can be and by default is configured to combine sequential small chunks that will together fit within the full chunk window (default 500 chars).
Combination is only valid for "whole" chunks. The current implementation attempts to combine at the element level (in the sectioner), meaning a small initial element (such as a `Title`) is combined with the prior section without considering the remaining length of the section that title belongs to. This frequently causes a title element to be removed from the chunk it …
> fix: sectioner dissociated titles from their chunk

- .github/workflows/ci.yml
- .github/workflows/ingest-test-fixtures-update-pr.yml
Now that "medium" runners are available in GitHub Actions again, re-enable them.
Intentionally not reverting https://github.com/Unstructured-IO/unstructured/commit/76213ecba7cfbab4163f052d89084e66f4a07d74 the change to the setup-ingest job since additional CPU shouldn't make a difference (e.g. it ran in 5 minutes here: https://github.com/Unstructured-IO/unstructured/commit/76213ecba7cfbab4163f052d89084e66f4a07d74 ).
> build(ci): bring back medium runners where appropriate

- .github/workflows/ci.yml
This was only used for debugging on a branch, not needed here.  It was failing because it didn't have the environment var set to "ci".
> remove test login

- .github/workflows/ci.yml
- .github/workflows/ingest-test-fixtures-update-pr.yml
Hopefully avoid incomplete cache issues. Though to be fair, there is no solid evidence pointing to runner size as the source of the issue.
> build(ci): use larger CI runners for setup

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/ingest/connector/biomed.py
- unstructured/ingest/connector/confluence.py
- unstructured/ingest/connector/delta_table.py
- unstructured/ingest/connector/discord.py
- unstructured/ingest/connector/elasticsearch.py
- unstructured/ingest/connector/fsspec.py
- unstructured/ingest/connector/github.py
- unstructured/ingest/connector/gitlab.py
- unstructured/ingest/connector/google_drive.py
- unstructured/ingest/connector/jira.py
- unstructured/ingest/connector/onedrive.py
- unstructured/ingest/connector/outlook.py
- unstructured/ingest/connector/reddit.py
- unstructured/ingest/connector/salesforce.py
- unstructured/ingest/connector/sharepoint.py
- unstructured/ingest/connector/slack.py
- unstructured/ingest/connector/wikipedia.py
All http calls being made by the ingest source connectors have been isolated and wrapped by the `SourceConnectionNetworkError` custom error, which triggers the retry logic, if enabled, in the ingest pipeline.
> expand retry logic in source connectors

- CHANGELOG.md
- docs/source/source_connectors/azure.rst
- docs/source/source_connectors/box.rst
- docs/source/source_connectors/dropbox.rst
- docs/source/source_connectors/google_cloud_storage.rst
- docs/source/source_connectors/s3.rst
- unstructured/__version__.py
- unstructured/ingest/interfaces.py
- unstructured/ingest/runner/azure.py
Add in the fsspec configs needed for the fsspec-based connectors
To match the behavior of the original CLI, the default used by the click option was mirrored in the base config for the api endpoint.
> Update fsspecs-specific source connector docs

- CHANGELOG.md
- test_unstructured_ingest/test-ingest-gcs-dest.sh
- test_unstructured_ingest/test-ingest-gcs.sh
- unstructured/__version__.py
- unstructured/ingest/cli/cmds/gcs.py
- unstructured/ingest/cli/cmds/google_drive.py
- unstructured/ingest/cli/interfaces.py
- unstructured/ingest/connector/google_drive.py
- unstructured/ingest/runner/gcs.py
- unstructured/ingest/runner/google_drive.py
- unstructured/ingest/runner/writers/gcs.py
The existing service account parameter was expanded to support either a file path or a json value to generate the credentials when instantiating the google drive client.
Google Cloud Storage already supports the value being passed in, from their docstring:
> - you may supply a token generated by the
[gcloud](https://cloud.google.com/sdk/docs/)
utility; this is either a python dictionary, the name of a file
containing the JSON returned by logging in with the gcloud CLI tool,
or a Credentials object.
I tested this locally:
```python
from gcsfs import GCSFileSystem
import json
with open("/Users/romanisecke/.ssh/google-cloud-unstructured-ingest-test-d4fc30286d9d.json") as json_file:
json_data = json.load(json_file)
print(json_data)
fs = GCSFileSystem(token=json_data) …
```
> support passing credentials from memory for google connectors

- CHANGELOG.md
- test_unstructured/chunking/test_title.py
- test_unstructured/documents/test_elements.py
- unstructured/chunking/title.py
- unstructured/documents/elements.py
**Executive Summary.**  When the elements in a _section_ are combined into a _chunk_, the metadata in each of the elements is _consolidated_ into a single `ElementMetadata` instance. There are two main problems with the current implementation:
1. The current algorithm simply uses the metadata of the first element as the metadata for the chunk. This produces:
- **empty chunk metadata** when the first element has no metadata, such as a `PageBreak("")`
- **missing chunk metadata** when the first element contains only partial metadata such as a `Header()` or `Footer()`
- **misleading  metadata** when the first element contains values applicable only to that element, such as `category_depth`, `coordinates` (bounding-box), `header_footer_type`, or `parent_id`
2. Second, list metadata such as …
> fix: flaky chunk metadata

- CHANGELOG.md
- test_unstructured_ingest/expected-structured-output/jira-diff/1/10000.json
- test_unstructured_ingest/expected-structured-output/local-single-file/example-docs/language-docs/UDHR_first_article_all.txt.json
- test_unstructured_ingest/metrics/aggregate-scores-cct.tsv
- test_unstructured_ingest/metrics/aggregate-scores-element-type.tsv
- test_unstructured_ingest/metrics/all-docs-cct.tsv
- test_unstructured_ingest/metrics/all-docs-element-type-frequency.tsv
- unstructured/__version__.py
- unstructured/ingest/evaluate.py
To combine ingest and holistic metrics efforts, add the `doctype` field to the results from the functions in evaluate.py for use in subsequent aggregation functions.
Run `sh ./test_unstructured_ingest/evaluation-metrics.sh text-extraction` and there will be a new doctype column with the file's doctype extension.
> chore: add doctype to ingest evaluation functions

- CHANGELOG.md
- test_unstructured_ingest/src/local-single-file.sh
- unstructured/__version__.py
- unstructured/ingest/cli/interfaces.py
- unstructured/ingest/interfaces.py
- unstructured/ingest/pipeline/partition.py
To always support the latest changed to the partition method and the possible kwargs it supports, the ingest CLI has been refactored to take in a valid json string to represent those values to allow a user more flexibility with controlling the partition method.
> feat: support generic inputs for partition kwargs from ingest CLI

- .github/workflows/ci.yml
Azure federated branch subject doesn’t work with merge queues.
> Add back environment to unblock

- docs/source/_templates/page.html
- docs/source/_templates/sidebar/brand.html
- docs/source/ingest/destination_connectors.rst
- docs/source/ingest/source_connectors.rst
Per @tabossert we're now using a link shortener behind which we can rotate the link to keep it current. That way we (🤞 ) never have to update this here again.
Links should work. No more links should exist in the documentation except this one.
> fix: update slack link to link shortener

- README.md
Updated slack links in the README that were using an old shortened URL.
> chore: Update readme slack links

- scripts/ingest-test-fixtures-update.sh
- test_unstructured_ingest/dest/azure-cognitive-search.sh
- test_unstructured_ingest/dest/azure.sh
- test_unstructured_ingest/dest/box.sh
- test_unstructured_ingest/dest/dropbox.sh
- test_unstructured_ingest/dest/gcs.sh
- test_unstructured_ingest/dest/s3.sh
- test_unstructured_ingest/src/sharepoint-embed-cog-index.sh
Intermittently the various destination test will fail with:
```
{noformat}--- Cleanup done ---
gs://utic-test-ingest-fixtures-output/1699377964/example-docs/
deleting gs://utic-test-ingest-fixtures-output/1699377964
Removing objects:
ERROR: (gcloud.storage.rm) The following URLs matched no objects or files:
-gs://utic-test-ingest-fixtures-output/1699377964
Last ran script: gcs.sh
Error: Process completed with exit code 1.{noformat}
```
Reference trace [here](https://github.com/Unstructured-IO/unstructured/actions/runs/6787927424/job/18452240764?pr=2020)
After some investigation it looks like this error is due to collisions that occur because we’re assuming 1s date accuracy is sufficient when generating (and deleting) "unique" test destination location names. The likelihood is actually …
> fix:  ingest destination test failure with missing output

- CHANGELOG.md
- test_unstructured/staging/test_base_staging.py
- unstructured/__version__.py
- unstructured/documents/elements.py
This metadata field is assumedly vestigial and is unused by any code in the repo. `max_characters` is an optional argument to `chunk_by_title()` and has meaning in that context, but is not written to the metadata.
Remove this unused field.
> fix: remove `.max_characters` from ElementMetadata

- scripts/docker-smoke-test.sh
Fixes docker-smoke-test.sh to reference the new location for the wikipedia ingest script, which was moved in https://github.com/Unstructured-IO/unstructured/pull/1951 . This fix should allow the docker image build to complete on merges to main.
Reference to recent failed job:
https://github.com/Unstructured-IO/unstructured/actions/runs/6819416096/job/18546724401
> fix(build): update ingest script loc in Dockerfile

- Makefile
Fixes the Makefile `ingest-` targets were broken in https://github.com/Unstructured-IO/unstructured/pull/1799/files. 
**Test Instructions**
for maketarget in $(grep .PHONY Makefile | grep  install-ingest  | perl -p -e 's/.PHONY://' | tr -d '\n'); do   
echo $maketarget; make $maketarget
done
> chore: fix Makefile ingest targets

- CHANGELOG.md
- Dockerfile
- unstructured/__version__.py
This was legacy and is no longer needed.  It also has the effect of incorrect owner for known_hosts of notebook-user
Relates to: #2056
> Remove ssh-keyscan and files

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/partition/utils/constants.py
- unstructured/partition/utils/ocr_models/paddle_ocr.py
Close: https://github.com/Unstructured-IO/unstructured-api/issues/247
User now can specify default [paddle lang code](https://github.com/Mushroomcat9998/PaddleOCR/blob/main/doc/doc_en/multi_languages_en.md#5-support-languages-and-abbreviations) with env `DEFAULT_PADDLE_LANG` before we have the language mapping for paddle
* in your unstructured API env, cd to unstructured repo and install it locally with `pip install -e .`
* check out to this branch
* run paddle on intel chip:
```
pip install paddlepaddle
pip install "unstructured.PaddleOCR"
export OCR_AGENT=paddle
export DEFAULT_PADDLE_LANG=ch
make run-web-app
```
* curl:
```
curl  -X 'POST'  'http://localhost:8000/general/v0/general'   -H 'accept: application/json'  -F 'files=@sample-docs/english-and-korean.png'   | jq -C . | less -R
``` …
> Chore: specify default language parameter to paddle with `DEFAULT_PADDLE_LANG`

- test_unstructured_ingest/check-diff-expected-output.sh
- allow the overwrite destination to be set to the `OUTPUT_ROOT` instead of default to script dir.
run
```bash
OVERWRITE_FIXTURES=true OUTPUT_ROOT=/tmp ./test_unstructured_ingest/src/s3.sh
```
with this change we should find new files generated under `/tmp/expected-structured-output/s3`. 
Without this change there will be no such new files.
> chore: add more parametrization to ingestion test

- test_unstructured_ingest/cleanup.sh
When testing ingest tests, one often wants to keep the .json output or generated metrics files around for inspection after the fact. This updates the bash condition to actually honor the comment that mentions
** Test Instructions **
Run:
export UNSTRUCTURED_CLEANUP_DEV_FIXTURES=1
./test_unstructured_ingest/src/s3.sh
./test_unstructured_ingest/evaluation-metrics.sh text-extraction
and witness test directories/files do not get cleaned up. E.g., `test_unstructured_ingest/metrics-tmp/`. One can also add a `set -x` at the top of test_unstructured_ingest/cleanup.sh to see what is getting skipped (it's a lot!).
> chore: ingest-script cleanup, better skip condition

- test_unstructured/partition/docx/test_docx.py
The test for nested tables added a few PRs ago indirectly relies on the padding added to table-HTML by `tabulate`. The length of that padding turns out to be non-deterministic, perhaps related to M1 vs. Intel hardware.
Remove padding from tabulate output in the test so only actual content is compared.
> fix(docx): tabulate output is non-deterministic

- .github/workflows/ci.yml
- CHANGELOG.md
- test_unstructured_ingest/dest/azure.sh
- test_unstructured_ingest/dest/gcs.sh
- test_unstructured_ingest/python/test-azure-output.py
- test_unstructured_ingest/python/test-gcs-output.py
- unstructured/__version__.py
- unstructured/ingest/cli/cmds/azure.py
To not require additional dependencies on cloud-related CLIs (i.e. gcloud and az), using python and the existing dependencies already used to run out code to interact with those providers for overhead work associated with destination ingest tests.
> drop cloud cli deps

- CHANGELOG.md
- test_unstructured/documents/test_html.py
- unstructured/__version__.py
- unstructured/cleaners/core.py
- unstructured/documents/html.py
There are a cluster of bugs in the HTML parsing code, particularly surrounding table behaviors but also inclusion of style elements, etc.
Clean up typing and docstrings in that neighborhood as a way to familiarize myself with that part of the code-base.
> rfctr(html): clean types and docs in prep for HTML table parsing fixes

- CHANGELOG.md
- test_unstructured/documents/test_html.py
- unstructured/__version__.py
- unstructured/documents/html.py
Fixes #1958.
`<style>` is invalid where it appears in the HTML of thw WSJ page mentioned by that issue but invalid has little meaning in the HTML world if Chrome accepts it.
In any case, we have no use for the contents of a `<style>` tag wherever it appears so safe enough for us to just strip all those tags. Note we do not want to also strip the *tail text* which can contain text we're interested in.
> fix(html): style (CSS) content appears in HTML text

- docs/source/ingest/destination_connectors.rst
The mongodb documentation page exists but is missing from the list of destination connectors, meaning it's not actually visible in the documentation.
> docs: add mongodb destination connector to ingest docs

- CHANGELOG.md
- test_unstructured_ingest/check-diff-evaluation-metrics.sh
- test_unstructured_ingest/evaluation-metrics.sh
- unstructured/metrics/evaluate.py
Currently the `check-diff-evaluation-metrics` only runs when there is file to perform evaluation on. Add the checking condition to skip the action when there is none. Additionally, more refactoring and `visualize` option for both evaluation calculation functions is also added.
> fix: fix eval ci to skip the overwrite if none exists

- .gitignore
- test_unstructured_ingest/dest/azure-cognitive-search.sh
- test_unstructured_ingest/dest/azure.sh
- test_unstructured_ingest/dest/dropbox.sh
- test_unstructured_ingest/dest/gcs.sh
- test_unstructured_ingest/dest/mongodb.sh
- test_unstructured_ingest/dest/sharepoint-embed-cog-index.sh
- test_unstructured_ingest/src/against-api.sh
- test_unstructured_ingest/src/airtable-diff.sh
- test_unstructured_ingest/src/airtable-large.sh
- test_unstructured_ingest/src/box.sh
- test_unstructured_ingest/src/confluence-diff.sh
- test_unstructured_ingest/src/confluence-large.sh
- test_unstructured_ingest/src/delta-table.sh
- test_unstructured_ingest/src/discord.sh
- test_unstructured_ingest/src/dropbox.sh
- test_unstructured_ingest/src/gcs.sh
- test_unstructured_ingest/src/google-drive.sh
- test_unstructured_ingest/src/hubspot.sh
- test_unstructured_ingest/src/jira.sh
- test_unstructured_ingest/src/notion.sh
- test_unstructured_ingest/src/onedrive.sh
- test_unstructured_ingest/src/outlook.sh
- test_unstructured_ingest/src/salesforce.sh
- test_unstructured_ingest/src/sharepoint-with-permissions.sh
- test_unstructured_ingest/src/sharepoint.sh
- test_unstructured_ingest/src/slack.sh
- test_unstructured_ingest/test-ingest-dest.sh
- test_unstructured_ingest/test-ingest-src.sh
Often times there are tests being skipped either due to missing env vars or explicitly defined in the base script but these get lost in the logs. This PR updates the scripts to leverage a custom error code if being skipped due to missing env vars and this custom error code is being caught by the base script and logs all files being skipped to a file. At the end of the script, this file gets logged in the CI output.
> feat: add logging to ingest CLI for tests being skipped at the end

- CHANGELOG.md
- Makefile
- requirements/test.in
- requirements/test.txt
- setup.cfg
- test_unstructured_ingest/dest/azure.sh
- test_unstructured_ingest/python/test-azure-output.py
- unstructured/__version__.py
- unstructured/ingest/connector/sharepoint.py
- unstructured/ingest/interfaces.py
Given the filtering in the ingest logger, anything going to console should go through that. This adds a linter that only checks for `print()` statements in the ingest code and ignored it elsewhere for now.
> chore: lint for print statements in ingest code

- CHANGELOG.md
- test_unstructured/documents/test_elements.py
- unstructured/__version__.py
- unstructured/cleaners/translate.py
- unstructured/documents/elements.py
In preparation for work on generalized chunking including `chunk_by_character()` and overlap, get `elements` module and tests passing strict type-checking.
> rfctr: improve element typing

- CHANGELOG.md
- test_unstructured/partition/pdf_image/test_ocr.py
- unstructured/partition/pdf_image/ocr.py
- unstructured/partition/utils/constants.py
This PR addresses [CORE-2965](https://unstructured-ai.atlassian.net/browse/CORE-2965) by limiting zoom factor so that the scaled image can still be processed by tesseract.
- tesseract has a 2^31 byte limit on image data
- occasionally an image may be scaled too much and larger than that size
- fix limits the scaling factor so that we never scale an image larger than what tesseract can handle
A unit test is added in this PR to test a unlikely case where we'd scale an image a few thousand times and massively exceed the limit without the fix. 
Unstructured reviewers can also use the document in the ticket to test.
[CORE-2965]: https://unstructured-ai.atlassian.net/browse/CORE-2965?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: image may be scaled too large for tesseract

- CHANGELOG.md
- test_unstructured/chunking/test_title.py
- test_unstructured/documents/test_elements.py
- test_unstructured/documents/test_html.py
- test_unstructured/partition/docx/test_docx.py
- test_unstructured/partition/pptx/test_pptx.py
- test_unstructured/partition/test_text.py
- unstructured/__version__.py
- unstructured/chunking/title.py
- unstructured/documents/elements.py
`CheckBox` elements get special treatment during chunking. `CheckBox` does not derive from `Text` and can contribute no text to a chunk. It is considered "non-combinable" and so is emitted as-is as a chunk of its own. A consequence of this is it breaks an otherwise contiguous chunk into two wherever it occurs.
This is problematic, but becomes much more so when overlap is introduced. Each chunk accepts a "tail" text fragment from its preceding element and contributes its own tail fragment to the next chunk. These tails represent the "overlap" between chunks. However, a non-text chunk can neither accept nor provide a tail-fragment and so interrupts the overlap. None of the possible solutions are terrific.
Give `Element` a `.text` attribute such that _all_ elements have a `.text` attribute, …
> rfctr: skip CheckBox elements during chunking

- CHANGELOG.md
- test_unstructured/chunking/test_title.py
- unstructured/__version__.py
- unstructured/chunking/title.py
The original naming for the pre-cursor to a chunk in `chunk_by_title()` was conflated with the idea of how these element subsequences were bounded (by document-section) for that strategy. I mistakenly picked that up as a universal concept but in fact no notion of section arises in the `by_character` or other chunking strategies.
Fix this misconception by using the name `pre-chunk` for this concept throughout.
> rfctr: rename pre chunk

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/chunking/__init__.py
- unstructured/chunking/title.py
- unstructured/partition/csv.py
- unstructured/partition/doc.py
- unstructured/partition/docx.py
- unstructured/partition/email.py
- unstructured/partition/epub.py
- unstructured/partition/html.py
- unstructured/partition/md.py
- unstructured/partition/msg.py
- unstructured/partition/odt.py
- unstructured/partition/org.py
- unstructured/partition/pdf_image/image.py
- unstructured/partition/pdf_image/pdf.py
- unstructured/partition/ppt.py
- unstructured/partition/pptx.py
- unstructured/partition/rst.py
- unstructured/partition/rtf.py
- unstructured/partition/text.py
- unstructured/partition/xlsx.py
- unstructured/partition/xml.py
The chunking subpackage `unstructured.chunking` currently contains only the `title` module and the `@add_chunking_strategy()` decorator is located in that module even though it has no special relationship to the `by_title` chunking strategy.
Move it to the `__init__.py` module such that it is exported from `unstructured.chunking`. Adjust all references, pretty much one per partitioner, to import it from there.
This prepares the way for further separation of the chunking package into modules, including a new `character` module for the `by_character` chunking strategy.
> rfctr(chunking): move add_chunking_strategy() decorator up

- CHANGELOG.md
- unstructured/__version__.py
also cleans up the CHANGELOG to reflect the previous release of 0.11.2
> build: release commit for 0.11.4

- CHANGELOG.md
- test_unstructured/chunking/test_base.py
- test_unstructured/chunking/test_title.py
- unstructured/__version__.py
- unstructured/chunking/base.py
- unstructured/chunking/title.py
Chunking options for things like chunk-size are largely independent of chunking strategy. Further, validating the args and applying defaults based on call arguments is sophisticated to make its use easy for the caller. These details distract from what the chunker is actually doing and would need to be repeated for every chunking strategy if left where they are.
Extract these settings and the rules governing chunking behavior based on options into its own immutable object that can be passed to any component that is subject to optional behavior (pretty much all of them).
> rfctr: extract ChunkingOptions

- CHANGELOG.md
- test_unstructured/chunking/test_base.py
- unstructured/__version__.py
- unstructured/chunking/base.py
- unstructured/chunking/title.py
To implement inter-pre-chunk overlap, we need a context that sees every pre-chunk both before and after it is accumulated (from elements).
- We need access to the pre-chunk when it is completed so we can extract the "tail" overlap to be applied to the next chunk.
- We need access to the as-yet-unpopulated pre-chunk so we can add the prior tail to it as a prefix.
This "visibility" is split between `PreChunkBuilder` and the pre-chunker itself, which handles `TablePreChunk`s without the builder.
Move `Table` element and TablePreChunk` formation into `PreChunkBuilder` such that _all_ element types (adding `Table` elements in particular) pass through it. Then `PreChunkBuilder` becomes the context we require.
The actual overlap harvesting and application will come in a subsequent commit.
> rfctr(chunking): generalize PreChunkBuilder

- CHANGELOG.md
- test_unstructured/chunking/test_base.py
- unstructured/__version__.py
- unstructured/chunking/base.py
- unstructured/chunking/title.py
`chunk_by_title()` respects certain semantic boundaries while chunking. Those are sections introduced by a `Title` element, sections introduced by a `metadata.section` value change, and optionally page-breaks. "Respecting" in this context means that elements on opposite sides of a semantic boundary never appear in the same chunk.
The `metadata_differs()` function used for this purpose is clumsy to use requiring the caller to maintain state (prior element). It also combines what are independent predicates such that they cannot be individually reused.
Introduce the `BoundaryPredicate` type which takes an element and returns bool, indicating whether the element introduces a new semantic boundary. These can be reused by any chunking strategy that needs them and allows the pre-chunking …
> rfctr(chunking): extract boundary predicates

- CHANGELOG.md
- test_unstructured/chunking/test_base.py
- test_unstructured/chunking/test_title.py
- unstructured/__version__.py
- unstructured/chunking/base.py
- unstructured/chunking/title.py
The `_split_elements_by_title_and_table()` function fulfills the pre-chunker role for `chunk_by_title()`, but most of its operation is not strategy-specific and can be reused by other chunking strategies.
Extract `BasePreChunker` and use it as the base class for `_ByTitlePreChunker` which now only needs to provide the boundary predicates specific to that strategy.
> rfctr(chunking): extract BasePreChunker

- CHANGELOG.md
- test_unstructured/chunking/test_base.py
- test_unstructured/chunking/test_title.py
- test_unstructured/partition/test_auto.py
- unstructured/__version__.py
- unstructured/chunking/base.py
The text of an oversized chunk is split on an arbitrary character boundary (mid-word). The `chunk_by_character()` strategy introduces the idea of allowing the user to specify a separator to use for chunk-splitting. For `langchain` this is typically "\n\n", "\n", or " "; blank-line, newline, or word boundaries respectively.
Even if the user is allowed to specify a separator, we must provide fall-back for when a chunk contains no such character. This can be done incrementally, like blank-line is preferable to newline, newline is preferable to word, and word is preferable to arbitrary character.
Further, there is nothing particular to `chunk_by_character()` in providing such a fall-back text-splitting strategy. It would be
preferable for all strategies to split oversized chunks on even-word …
> rfctr(chunking): split oversized chunks on word boundary

- CHANGELOG.md
- setup.cfg
- test_unstructured/chunking/test_base.py
- unstructured/__version__.py
- unstructured/chunking/base.py
There are two distinct overlap operations with completely different implementations. This is "intra-chunk" overlap, applying overlap to chunks resulting from text-splitting an oversized element.
So if an oversized element had text "abcd efgh ijkl mnop qrst" and was split at 15 chars with overlap of 5, it would produce "abcd efgh ijkl" and "ijkl mnop qrst". Any inter-chunk overlap from the prior chunk and applied at the beginning of the string (before "abcd") is handled in a separate operation in the next PR.
> feat(chunking): add overlap on chunk-splits

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/embed/bedrock.py
- unstructured/embed/huggingface.py
- unstructured/embed/interfaces.py
- unstructured/embed/openai.py
Convert all encoders to be based off dataclasses. Purpose: this will allow encoders to be used in a generic way amongst other  dataclasses. Otherwise, it'll break validation in those parent dataclasses.
> feat: update encoders to be dataclasses

- CHANGELOG.md
- test_unstructured/embed/test_openai.py
- unstructured/__version__.py
- unstructured/embed/bedrock.py
- unstructured/embed/huggingface.py
- unstructured/embed/interfaces.py
- unstructured/embed/openai.py
- unstructured/ingest/interfaces.py
Leverage a similar pattern to what is used for connectors, where there is a nested config dataclass as a field, along with cached content for things like the client and sample embedding for each. This required an update on the embeddings config in ingest and I left a TODO in there because the current approach breaks on other encoders such as bedrock because the parameters in that config don't map to all encoders. But this keeps the existing functionality working.
This update makes sure all variables associated with the dataclass exist when it's instantiated rather than being added in the `__post_init__()` method or the `initialize()`, allowing other libraries like pydantic to appropriately generate schemas from it.  It also now follows the pattern of the connectors in that each class has …
> feat: improve dataclass use for encoders

- CHANGELOG.md
- test_unstructured/partition/pdf_image/test_image.py
- test_unstructured/partition/pdf_image/test_pdf.py
- test_unstructured/partition/test_strategies.py
- unstructured/__version__.py
- unstructured/partition/pdf.py
- unstructured/partition/strategies.py
Closes #2323.
- update logic to return "hi_res" if either `extract_images_in_pdf` or `extract_element_types` is set
- refactor: remove unused `file` parameter from `determine_pdf_or_image_strategy()`
```
elements = partition_pdf(
filename="example-docs/embedded-images-tables.pdf",
extract_element_types=["Image"],
extract_to_payload=True,
)
image_elements = [el for el in elements if el.category == ElementType.IMAGE]
print(image_elements)
```
> Fix: element extraction not working when using "auto" strategy for pdf

- CHANGELOG.md
- test_unstructured/partition/test_api.py
- unstructured/__version__.py
- unstructured/partition/api.py
Closes #2340 
We need to make sure the custom url is passed to our client. The client constructor takes the base url, so for compatibility we can continue to take the full url and strip off the path.
To verify, run the api locally and confirm you can make calls to it.
```
make run-web-app
from unstructured.partition.api import partition_via_api
filename = "example-docs/layout-parser-paper.pdf"
partition_via_api(filename=filename, api_url="http://localhost:8000")
```
> fix: Fix api_url param to partition_via_api

- CHANGELOG.md
- test_unstructured/documents/test_html.py
- test_unstructured/partition/epub/test_epub.py
- test_unstructured/partition/pypandoc/test_rtf.py
- test_unstructured/partition/test_auto.py
- test_unstructured/partition/test_html_partition.py
- test_unstructured_ingest/expected-structured-output/Sharepoint-with-permissions/Shared Documents/ideas-page.html.json
- test_unstructured_ingest/expected-structured-output/Sharepoint/Shared Documents/ideas-page.html.json
- test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/1540126.json
- test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/1605928.json
- test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/1605942.json
- test_unstructured_ingest/expected-structured-output/gcs/ideas-page.html.json
- test_unstructured_ingest/expected-structured-output/gcs/nested-1/nested/ideas-page.html.json
- test_unstructured_ingest/expected-structured-output/gcs/nested-2/nested/ideas-page.html.json
- unstructured/__version__.py
- unstructured/documents/html.py
Fixes #2339
Fixes to HTML partitioning introduced with v0.11.0 removed the use of `tabulate` for forming the HTML placed in `HTMLTable.text_as_html`. This had several benefits, but part of `tabulate`'s behavior was to make row-length (cell-count) uniform across the rows of the table.
Lacking this prior uniformity produced a downstream problem reported in
On closer inspection, the method used to "harvest" cell-text was producing more text-nodes than there were cells and was sensitive to where whitespace was used to format the HTML. It also "moved" text to different columns in certain rows.
Refine the cell-text gathering mechanism to get exactly one text string for each row cell, eliminating whitespace formatting nodes and producing strict correspondence between the number of cells in the …
> fix(html): unequal row lengths in HTMLTable.text_as_html

- CHANGELOG.md
- test_unstructured/chunking/test_base.py
- unstructured/__version__.py
- unstructured/chunking/base.py
Reviewer: This PR probably reviews faster commit-by-commit. Each of the commits is groomed and focuses on a separate clear aspect of this implementation.
This  PR adds inter-chunk overlap capability to chunking. It does not yet expose it via the API.
Inter-chunk overlap is overlap between whole pre-chunks, prior to any text-splitting required for oversized chunks. Contrast with intra-chunk overlap implemented in the prior PR which implements overlap on these latter text-splitting boundaries.
Inter-chunk overlap is disabled by default since a pre-chunk already has a "clean" semantic boundary (composed of whole elements) and adding overlap there introduces noise from the adjacent context. If the user wants inter-chunk overlap they must specify `overlap_all=True` in the options. Inter-chunk …
> feat(chunking): add inter-chunk overlap

- test_unstructured_ingest/dest/azure-cognitive-search.sh
This PR:
- updates ingest azure cognitive search destination connector test to move into a new service.
- changes response parsing logic in the test.
> chore: update ingest azure cognitive search endpoint

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/ingest/interfaces.py
- unstructured/ingest/pipeline/source.py
The session handler variable can be anything, because it's specific to the SDK being used for the connector. This can break the serialization depending on what that is. To avoid this all together, the session handler itself is not serialized. Instead, it needs to be recreated if an object is serialized and then deserialized.
> bug: omit session handler from serialization to avoid mp issues

- CHANGELOG.md
- test_unstructured_ingest/dest/weaviate.sh
- unstructured/__version__.py
- unstructured/ingest/cli/cmds/weaviate.py
- unstructured/ingest/connector/weaviate.py
This PR handles two things:
* Fixes the serialization of the weaviate destination connector since the client content breaks serialization when present due to `TypeError: cannot pickle '_thread.lock' object`.
* Set finer auth control rather than generic dictionary on the CLI and access config.
> bug: weaviate serialization broken

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/ingest/enhanced_dataclass/core.py
The current approach injects the redacted text for all sensitive fields regardless of if they have a value or not. This updates the code to only replace the value with the redacted text if the value exists.
> bug: don't redact text when serialization if not value

- test_unstructured_ingest/dest/pinecone.sh
This PR updates Pinecone index creation in the ingest test due to a recent update in Pinecone API.
Due to a change in Pinecone API, it is not allowed anymore to specify both number of replicas and number of pods:
`Cannot specify both replicas and pods`
We solve it by removing the replica specification while sending the index creation request.
```
Creating index ingest-test-28418
Index creation success: 201
```
> chore(ingest): update pinecone index creation specifications

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/ingest/connector/pinecone.py
This fixes the serialization of the Pinecone destination connector. Presence of the PineconeIndex object breaks serialization due to TypeError: cannot pickle '_thread.lock' object. This removes that object before serialization.
> fix: pinecone serialization issue

- docs/source/ingest/destination_connectors/data/elasticsearch_elements_mappings.json
- scripts/elasticsearch-test-helpers/destination_connector/test-ingest-elasticsearch-output.py
- test_unstructured_ingest/dest/elasticsearch.sh
Currently in the Elasticsearch Destination ingest test we are writing the embeddings to a "float" type field. In order to leverage this field for similarity search it should be mapped as "dense_vector" with the respective dimensions assigned.
This PR updates that mapping and adds a test query to validate that this works as expected.
> test: update test Elasticsearch mappings to validate embedding search

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/ingest/cli/cmds/elasticsearch.py
- unstructured/ingest/connector/elasticsearch.py
* set required=False to all write config options
* update num_processes to default to 1 since that will always work
> chore: make Elasticsearch Destination connector write settings optional

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/ingest/connector/elasticsearch.py
This fixes the serialization of the Elasticsearch destination connector. Presence of the _client object breaks serialization due to TypeError: cannot pickle '_thread.lock' object. This removes that object before serialization.
> fix: elasticsearch serialization issue 

- CHANGELOG.md
- docs/requirements.txt
- requirements/base.in
- requirements/base.txt
- requirements/build.txt
- requirements/dev.txt
- requirements/extra-markdown.txt
- requirements/extra-paddleocr.txt
- requirements/extra-pdf-image.txt
- requirements/huggingface.txt
- requirements/ingest/chroma.txt
- requirements/ingest/embed-aws-bedrock.txt
- requirements/ingest/embed-huggingface.txt
- requirements/ingest/embed-openai.txt
- requirements/ingest/gcs.txt
- requirements/ingest/google-drive.txt
- requirements/test.txt
- unstructured/__version__.py
Replacement for #2311 since python 3.8 was dropped as a supported version.
Unstructured-client added `api_key_auth` as a param to `UnstructuredClient` in [version 0.9.0](https://github.com/Unstructured-IO/unstructured-python-client/commit/8c93115c926765efe95c4e2a4e6bdf739fce41ad).
This pins the version of `unstructured-client` so users do not receive `TypeError: UnstructuredClient.__init__() got an unexpected keyword argument 'api_key_auth'`
> pin unstructured-client

- CHANGELOG.md
- test_unstructured_ingest/dest/chroma.sh
- unstructured/__version__.py
- unstructured/chunking/__init__.py
- unstructured/chunking/base.py
- unstructured/chunking/basic.py
- unstructured/chunking/title.py
- unstructured/ingest/cli/interfaces.py
- unstructured/ingest/interfaces.py
There are several public interface points for chunking and they all provide a default for arguments like `max_charactes`. These defaults are provided by literal values. Keeping these synchronized has become a problem.
Declare constant values for chunking argument default values and use those wherever a non-trivial default is used in an end-user facing API function.
> rfctr(chunking): add chunking arg constants

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/ingest/connector/sql.py
This fixes the serialization of the Elasticsearch destination connector. Presence of the _client object breaks serialization due to TypeError: cannot pickle '_thread.lock' object. This removes that object before serialization.
> fix: postgres destination connector serialization

- Dockerfile
Propagating the openssl revert made in the base image: https://github.com/Unstructured-IO/base-images/pull/13
Note that I messed up and wrote over the existing 9.2-9 image. Any current prs will need to rebase in order to get a working dockerfile.
> chore: Update base image

- CHANGELOG.md
- test_unstructured/partition/test_lang.py
- unstructured/__version__.py
- unstructured/partition/lang.py
This refactor removes `_convert_to_standard_langcode` and replaces it with calling `_get_iso639_language_object` with a string slice.
Use of TESSERACT_LANGUAGES_AND_CODES, which was added to `_convert_to_standard_langcode` previously, is moved to the relevant part where `_convert_to_standard_langcode` was previously called.
If/else statements replace the list comprehension for readability and `langdetect_langs.append("zho")` replaces `_convert_to_standard_langcode("zh")` since that always returned `"zho"`.
> refactor: use _get_iso639_language_object

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/ingest/connector/chroma.py
This fixes the serialization of the ChromaDB destination connector. Presence of the _collection object breaks serialization due to TypeError: cannot pickle 'module' object. This removes that object before serialization.
> fix: chroma destination connector serialization

- docs/requirements.txt
Fix sphinx-build error
> ERROR: Could not find a version that satisfies the requirement alabaster==0.7.16 (from -r docs/requirements.txt (line 7)) (from versions: 0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.7.7, 0.7.8, 0.7.9, 0.7.10, 0.7.11, 0.7.12, 0.7.13)
Changelog: 
* pin alabaster version to 0.7.13
> Fixed sphinx-build error by pinning alabaster=-0.7.13

- CHANGELOG.md
- setup.py
- unstructured/__version__.py
setup.py is currently pointing to the wrong location for the databricks-volumes extra requirements. This PR updates to point to the correct location.
Tested by installing from local source with `pip install .`
> fix: path to databricks-volumes requirements

- CHANGELOG.md
- test_unstructured/file_utils/test_filetype.py
- unstructured/__version__.py
- unstructured/file_utils/filetype.py
Closes #2412. Adds support for YAML MIME types and treats them as plain text. In response to `500` errors that the API currently returns if the MIME type is `text/yaml`.
> fix: treat yaml files as plain text

- CHANGELOG.md
- docs/source/best_practices/table_extraction_pdf.rst
- docs/source/conf.py
- docs/source/index.rst
- docs/source/ingest/destination_connectors/databricks_volumes.rst
- unstructured/__version__.py
To test:
> cd docs && make html
Change logs:
* Updates the best practice for table extraction to use `skip_infer_table_types` instead of `pdf_infer_table_structure`.
* Fixed CSS issue with a duplicate search box.
* Fixed RST warning message
* Fixed typo on the Intro page.
> Docs updates

- CHANGELOG.md
- test_unstructured_ingest/unit/test_sql_conform_dict.py
- unstructured/__version__.py
- unstructured/ingest/connector/sql.py
Formatting of link_texts was breaking metadata storage. Turns out it didn't need any conforming and came in correctly from json.
> fix: link_texts was breaking postgres destination connector

- CHANGELOG.md
- test_unstructured/partition/pdf_image/test_pdf.py
- unstructured/__version__.py
- unstructured/partition/pdf.py
Closes #2480.
- fixed an error introduced by PR [#2347](https://github.com/Unstructured-IO/unstructured/pull/2347) - https://github.com/Unstructured-IO/unstructured/pull/2347/files#diff-cefa2d296ae7ffcf5c28b5734d5c7d506fbdb225c05a0bc27c6b755d5424ffdaL373
- updated `test_partition_pdf_with_model_name()` to test more model names
The updated test function `test_partition_pdf_with_model_name()` should work on this branch, but fails on the `main` branch.
> fix: `partition_pdf()` not working when using chipper model with file

- CHANGELOG.md
- Makefile
- setup.py
- unstructured/__version__.py
I accidentally added Vectara to setup and makefile. But there are no dependencies for Vectara
This removes Vectara from those files.
> bug: remove vectara requirements

- CHANGELOG.md
- example-docs/eml/signed-doc.p7s
- test_unstructured/partition/test_auto.py
- test_unstructured/partition/test_email.py
- unstructured/__version__.py
- unstructured/documents/elements.py
- unstructured/file_utils/filetype.py
- unstructured/partition/email.py
Closes #2489, which reported an inability to process `.p7s` files. PR implements two changes:
- If the user selected content type for the email is not available and there is another valid content type available, fall back to the other valid content type.
- For signed message, extract the signature and add it to the metadata
```python
filename = "example-docs/eml/signed-doc.p7s"
elements = partition(filename=filename) # should get a message about fall back logic
print(elements[0]) # "This is a test"
elements[0].metadata.to_dict() # Will see the signature
```
> enhancement: process `.p7s` files with `partition_email`

- CHANGELOG.md
- test_unstructured/partition/xlsx/test_xlsx.py
- unstructured/__version__.py
- unstructured/partition/xlsx.py
**Reviewers:** It may be faster to review each of the three commits separately since they are groomed to only make one type of change each (typing, docstrings, test-cleanup).
**Summary**
There are a cluster of bugs in `partition_xlsx()` that all derive from flaws in the algorithm we use to detect "subtables". These are encountered when the user wants to get multiple document-elements from each worksheet, which is the default (argument `find_subtable = True`).
These commits clean up typing, lint, and other non-behavior-changing aspects of the code in preparation for installing a new algorithm that correctly identifies and partitions contiguous sub-regions of an Excel worksheet into distinct elements.
This is a summary of the failure cases. There are a few other cases …
> rfctr(xlsx): cleaning in prep for XLSX algorithm replacement

- requirements/base.txt
- requirements/dev.txt
- requirements/extra-csv.txt
- requirements/extra-paddleocr.txt
- requirements/extra-pdf-image.txt
- requirements/extra-xlsx.txt
- requirements/huggingface.txt
- requirements/ingest/chroma.txt
- requirements/ingest/confluence.txt
- requirements/ingest/databricks-volumes.txt
- requirements/ingest/delta-table.txt
- requirements/ingest/embed-aws-bedrock.txt
- requirements/ingest/embed-huggingface.txt
- requirements/ingest/embed-openai.txt
- requirements/ingest/gcs.txt
- requirements/ingest/google-drive.txt
- requirements/ingest/jira.txt
- requirements/ingest/notion.txt
- requirements/ingest/pinecone.txt
- requirements/ingest/qdrant.txt
- requirements/ingest/salesforce.txt
- requirements/ingest/slack.txt
- requirements/test.txt
- test_unstructured_ingest/evaluation-metrics.sh
- test_unstructured_ingest/test-ingest-src.sh
The current `test-ingest-src.sh` and `evaluation-metrics` do not allow passing the `EXPORT_DIR` (`OUTPUT_ROOT` in `evaluation-metrics`). It is currently saving at the current working directory (`unstructured/test_unstructured_ingest`). When running the eval from `core-product`, all outputs is now saved at `core-product/upstream-unstructured/test_unstructured_ingest` which is undesirable. 
This PR modifies two scripts to accommodate such behavior:
1. `test-ingest-src.sh` - assign `EVAL_OUTPUT_ROOT` to the value set within the environment if exist, or the current working directory if not. Then calls to run `evaluation-metrics.sh`.
2. `evaluation-metrics.sh` - accepting param from `test-ingest-src.sh` if exist, or to the value set within the environment if exist, or the current directory if …
> feat: modify test-ingest-src and evaluation-metrics to allow EXPORT_DIR

- docs/source/apis/api_sdks.rst
`files` should be `fileName` as noted in https://github.com/Unstructured-IO/unstructured-js-client/issues/24
> Fix a parameter name in the js-client example usage

- CHANGELOG.md
- pyproject.toml
- test_unstructured/partition/test_json.py
- unstructured/__version__.py
- unstructured/partition/email.py
- unstructured/partition/json.py
- unstructured/partition/xml.py
**Summary**
For whatever reason, the `@add_chunking_strategy` decorator was not present on `partition_json()`. This broke the only way to accomplish a "chunking-only" workflow using the REST API. This PR remedies that problem.
> fix(json): partition_json() does not chunk

- CHANGELOG.md
- test_unstructured/chunking/test_base.py
- test_unstructured/chunking/test_title.py
- unstructured/__version__.py
- unstructured/chunking/__init__.py
- unstructured/chunking/base.py
- unstructured/chunking/basic.py
- unstructured/chunking/title.py
- unstructured/ingest/cli/interfaces.py
- unstructured/ingest/interfaces.py
**Summary**
In order to accommodate customized chunkers other than those directly provided by `unstructured`, some further modularization is necessary such that a new chunker can be added as a "plug-in" without modifying the `unstructured` library code.
This PR is the straightforward refactoring required for this process like typing changes. There are also some other small changes we've been meaning to make like making all chunking options accept `None` to represent their default value so the broad field of callers (e.g. ingest, unstructured-api, SDK) don't need to determine and set default values for chunking arguments leading to diverging defaults.
Isolating these "noisy" but easy to accept changes in this preparatory PR reduces the noise in the more substantive changes to follow.
> rfctr(chunking): preparation for plug-in chunkers, Part I

- CHANGELOG.md
- test_unstructured/chunking/test_base.py
- test_unstructured/chunking/test_basic.py
- test_unstructured/chunking/test_title.py
- unstructured/__version__.py
- unstructured/chunking/base.py
- unstructured/chunking/basic.py
- unstructured/chunking/title.py
**Summary**
A pluggable chunking strategy needs its own local set of chunking options that subclasses a base-class in `unstructured`.
Extract distinct `_ByTitleChunkingOptions` and `_BasicChunkingOptions` for the existing two chunking strategies and move their strategy-specific option setting and validation to the respective subclass.
This was also a good opportunity for us to clean up a few odds and ends we'd been meaning to.
Might be worth looking at the commits individually as they are cohesive incremental steps toward the goal.
> rfctr(chunking): extract strategy-specific chunking options

- CHANGELOG.md
- test_unstructured/partition/test_api.py
- unstructured/__version__.py
- unstructured/partition/api.py
The purpose of this PR is to support using the same type of parameters as `partition_*()` when using `partition_via_api()`. This PR works together with `unsturctured-api` [PR #368](https://github.com/Unstructured-IO/unstructured-api/pull/368).
**Note:** This PR will support extracting image blocks("Image", "Table") via partition_via_api().
- update `partition_via_api()` to convert all list type parameters to JSON formatted strings before passing them to the unstructured client SDK
- add a unit test function to test extracting image blocks via `parition_via_api()`
- add a unit test function to test list type parameters passed to API via unstructured client sdk
```
from unstructured.partition.api import partition_via_api
elements = partition_via_api( …
```
> feat: pass list type parameters via client sdk

- CHANGELOG.md
- test_unstructured_ingest/expected-structured-output/Sharepoint-with-permissions/Shared Documents/fake-text.txt.json
- test_unstructured_ingest/expected-structured-output/Sharepoint-with-permissions/Shared Documents/ideas-page.html.json
- test_unstructured_ingest/expected-structured-output/Sharepoint-with-permissions/Shared Documents/permissions-fake-text.docx.json
- test_unstructured_ingest/expected-structured-output/Sharepoint-with-permissions/Shared Documents/stanley-cups.xlsx.json
- test_unstructured_ingest/expected-structured-output/Sharepoint/Shared Documents/fake-text.txt.json
- test_unstructured_ingest/expected-structured-output/Sharepoint/Shared Documents/ideas-page.html.json
- test_unstructured_ingest/expected-structured-output/Sharepoint/Shared Documents/permissions-fake-text.docx.json
- test_unstructured_ingest/expected-structured-output/Sharepoint/Shared Documents/stanley-cups.xlsx.json
- test_unstructured_ingest/unit/test_sharepoint.py
- unstructured/__version__.py
- unstructured/ingest/connector/sharepoint.py
We are seeing occurrences of inconsistency in the timestamps returned by office365.sharepoint when fetching created and modified dates. Furthermore, in future versions of this library, a datetime object will be returned rather than a string. 
- This adds logic to guarantee SharePoint dates will be properly formatted as ISO, regardless of the format provided by the sharepoint library.
- Bumps timestamp format output to include timezone offset (as we do with others)
Unit test added to validate this datetime handling across various formats.
> fix: handling of varied SharePoint date formats

- CHANGELOG.md
- docs/requirements.txt
- docs/source/examples/chroma.rst
- requirements/build.txt
- unstructured/__version__.py
Closes  #2577
Testing:
```
cnn_lite_url = "https://lite.cnn.com/"
elements = partition_html(url=cnn_lite_url)
links = []
for element in elements:
if element.metadata.link_urls:
relative_link = element.metadata.link_urls[0][1:]
if relative_link.startswith("2024"):
links.append(f"{cnn_lite_url}{relative_link}")
print(links)
```
> fix documentation html links example

- CHANGELOG.md
- test_unstructured/chunking/test_dispatch.py
- unstructured/__version__.py
- unstructured/chunking/__init__.py
- unstructured/chunking/basic.py
- unstructured/chunking/dispatch.py
- unstructured/partition/csv.py
- unstructured/partition/doc.py
- unstructured/partition/docx.py
- unstructured/partition/email.py
- unstructured/partition/epub.py
- unstructured/partition/html.py
- unstructured/partition/image.py
- unstructured/partition/json.py
- unstructured/partition/md.py
- unstructured/partition/msg.py
- unstructured/partition/odt.py
- unstructured/partition/org.py
- unstructured/partition/pdf.py
- unstructured/partition/ppt.py
- unstructured/partition/pptx.py
- unstructured/partition/rst.py
- unstructured/partition/rtf.py
- unstructured/partition/text.py
- unstructured/partition/xlsx.py
- unstructured/partition/xml.py
**Summary**
This is the final step in adding pluggable chunking-strategies. It introduces the `chunk()` function to replace calls to strategy-specific chunkers in the `@add_chunking_strategy` decorator. The `chunk()` function then uses a mapping of chunking-strategy names (e.g. "by_title", "basic") to chunking functions (chunkers) to dispatch the chunking call. This allows other chunkers to be added at runtime rather than requiring a code change, which is what "pluggable" chunkers is.
**Additional Information**
- Move the `@add_chunking_strategy` to the new `chunking.dispatch` module since it coheres strongly with that operation, but publish it from `chunking(.__init__)` (as it was before) so users don't couple to the way we organize the chunking sub-package. Also remove the third level …
> rfctr(chunking): extract chunking-strategy dispatch

- .github/workflows/ci.yml
- Makefile
- scripts/check-extras.sh
- setup.py
Currently the requirements associated with an extra in the `setup.py` is being dynamically generated using the `load_requirements()` method in the same file. This is being passed in all the `.in` files which then get read line by line to generate the requirements associated with an extra. Unless the `.in` file itself has a version pin, this will never respect the `.txt` files being generated by `pip-compile`. This fix updates all the inputs to `load_requirements()` to use the `.txt` files themselves.
> BUGFIX: fix dependencies in setup.py

- CHANGELOG.md
- test_unstructured/metrics/test_table_structure.py
- unstructured/__version__.py
- unstructured/metrics/evaluate.py
The current way table structure metrics are computed does not cover cases when none table is found and all stats are empty.
This PR fixes this + adds some hardenning tests for table eval processor.
> fix: table evaluation metrics fix calculations when no tables found in predictions

- CHANGELOG.md
- test_unstructured/partition/test_common.py
- test_unstructured/partition/xlsx/test_xlsx.py
- unstructured/__version__.py
- unstructured/partition/common.py
**Summary**
Fixes: #2308
**Additional context**
Through a somewhat deep call-chain, partitioning a file-like object (e.g. io.BytesIO) having its `.name` attribute set to a path not pointing to an actual file on the local filesystem would raise `FileNotFoundError` when the last-modified date was being computed for the document.
This scenario is a legitimate partitioning call, where `file.name` is used downstream to describe the source of, for example, a bytes payload downloaded from the network.
**Fix**
- explicitly check for the existence of a file at the given path before accessing it to get its modified date. Return `None` (already a legitimate return value) when no such file exists.
- Generally clean up the implementations.
- Add unit tests that exercise all cases.
> fix: raises on file-like object with .name not a valid path

- scripts/version-sync.sh
Fix SC2324 shellcheck warning by adding -i to indicate var type of integer and tidy up the formatting.
> fix: declare -i [SC2324 shellcheck]

- .github/workflows/ci.yml
- .github/workflows/docker-publish.yml
- scripts/version-sync.sh
The docker-publish github actions workflow builds amd and arm images of the repository and tests them before publishing. These tests have been failing since [this commit](https://github.com/Unstructured-IO/unstructured/commit/ee8b0f93dcba5adb2e4e032346fbaafbe0f45e54) with an error `UNS_API_KEY environment variable not set`.
The issue is that [this line](https://github.com/Unstructured-IO/unstructured/blob/b27ad9b6aa4cb29d5d3194cb1f1a0bf1fbaab30b/.github/workflows/docker-publish.yml#L62) in the workflow is actually blowing away the value assigned to the file in the previous line
* Update line that was overwriting the assignment of UNS_API_KEY to the uns_test_env_file in the docker-publish workflow to leverage the `>>` operator so that UNSTRUCTURED_HF_TOKEN assignment is only appended.
* …
> fix: docker-publish build test missing key error

- CHANGELOG.md
- test_unstructured/chunking/test_base.py
- test_unstructured_ingest/expected-structured-output/local-single-file-basic-chunking/handbook-1p.docx.json
- unstructured/__version__.py
- unstructured/chunking/base.py
**Summary**
Add `metadata.is_continuation = True` to metadata of second-and-later text-split chunks formed from an oversized non-table element. Previously this metadata was only present on text-split `TableChunk` elements.
This enables downstream filtering of intentionally redundant metadata on chunk elements that may not be desired for all purposes.
> feat(chunking): composite text gets is_continuation

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/chunking/base.py
- unstructured/chunking/basic.py
- unstructured/chunking/title.py
**Summary**
Use omnibus `kwargs` dict for `ChunkingOptions` state rather than explicit option parameters.
While articulating explicit options for `ChunkingOptions` and its (now several) sub-classes provides some type-safety, it induces a large amount of redundancy which complicates updates to the base class and especially patches to the base class from client code that adds custom chunkers.
In particular, it makes custom chunkers brittle to any new attributes added to `ChunkingOptions` (the base class).
Use a single omnibus `kwargs` argument to `ChunkingOptions` and its subclasses allowing each to pull out the options it is interested in and happily ignore the rest.
The type safety provided by explicit parameters and types is only afforded to the single place the …
> rfctr(chunking): simplify chunking opts construction

- .pre-commit-config.yaml
- CHANGELOG.md
- Makefile
- pyproject.toml
- test_unstructured/unit_utils.py
- unstructured/__version__.py
- unstructured/documents/elements.py
**Summary**
Some typing modernization in `elements.py` which will get changes to add the `orig_elements` metadata field.
Also some additions to `unit_util.py` to enable simplified mocking that will be required in the next PR.
> rfctr: prepare for adding metadata.orig_elements field

- CHANGELOG.md
- Makefile
- test_unstructured/chunking/test_base.py
- test_unstructured/chunking/test_basic.py
- test_unstructured/chunking/test_title.py
- unstructured/__version__.py
- unstructured/chunking/base.py
- unstructured/chunking/basic.py
- unstructured/chunking/title.py
- unstructured/documents/elements.py
- unstructured/staging/weaviate.py
**Summary**
Add `include_orig_elements: bool = True` as a new chunking option. This PR does not implement _adding_ original elements to chunks, only accepting this parameter as a chunking option and assigning `True` to it as a default value when it is omitted as a keyword argument.
Note this will need to be added in other repositories as well in order to fully support this new option by all access methods. In particular it will need to be added in `unstructured-api` in order to become available via the SDKs.
> feat(chunking): add include_orig_elements chunking option

- CHANGELOG.md
- test_unstructured/chunking/test_base.py
- test_unstructured/chunking/test_basic.py
- test_unstructured/chunking/test_title.py
- unstructured/__version__.py
- unstructured/chunking/base.py
- unstructured/documents/elements.py
**Summary**
Add the actual behavior to populate `.metadata.orig_elements` during chunking, when so instructed by the `include_orig_elements` option.
The underlying structures to support this, namely the `.metadata.orig_elements` field and the `include_orig_elements` chunking option, were added in closely prior PRs. This PR adds the behavior to actually populate that metadata field during chunking when the option is set.
> feat(chunking): add .orig_elements behavior to chunking

- CHANGELOG.md
- test_unstructured/metrics/test_evaluate.py
- unstructured/metrics/evaluate.py
- unstructured/metrics/table/table_eval.py
Creates a compounding metric to represent table structure score. It is an average of existing row and col index and content score.
This PR adds a new property to `unstructured.metrics.table_eval.TableEvaluation`: `composite_structure_acc`, which is computed from the element level row and column index and content accuracy scores. This new metric is meant to offer a single number to represent the performance of table structure extraction model/algorithms. 
This PR also refactors the eval computation logic so it uses a constant `table_eval_metrics` instead of hard coding the name of the metrics in multiple places in the code.
> Feat: single table structure eval metric

- CHANGELOG.md
- test_unstructured/chunking/test_title.py
- unstructured/__version__.py
- unstructured/chunking/title.py
Minor refactor after conversation with @scanny
Updates docstring and how chunking options are accessed. `self._kwargs.get()` should only be used in the `lazyproperty` definition of an instance's attribute. Other calls should use `self.<attribute>`
> refactor title.py

- CHANGELOG.md
- unstructured/ingest/evaluate.py
The `get_mean_grouping_command` currently does not take `export_name` as param. Add the param for better naming use case.
> refactor: get_mean_grouping command takes in export_name

- CHANGELOG.md
- docs/source/apis/api_parameters.rst
- docs/source/core/chunking.rst
- docs/source/metadata.rst
- test_unstructured/documents/test_elements.py
- test_unstructured/staging/test_base.py
- test_unstructured_ingest/expected-structured-output/local-single-file-basic-chunking/handbook-1p.docx.json
- unstructured/documents/elements.py
- unstructured/staging/base.py
**Summary**
This final PR in the "orig_elements" series adds the needful such that `.metadata.orig_elements`, when present on a chunk (element), is serialized to JSON when the chunk is serialized, for instance, to be used in an HTTP response payload.
It also provides for deserializing such a JSON payload into chunks that contain the `.orig_elements` metadata.
Note that `.metadata.orig_elements` is always `Optional[list[Element]]` when in memory. However, those original elements are serialized as Base64-encoded gzipped JSON and are in that form (str) when present as JSON or as "element-dicts" which is an intermediate serialization/deserialization format. That is, serialization is `Element -> dict -> JSON` and deserialization is `JSON -> dict -> Element` and …
> feat(chunking): add metadata.orig_elements serde

- CHANGELOG.md
- test_unstructured/partition/xlsx/test_xlsx.py
- unstructured/__version__.py
- unstructured/partition/xlsx.py
**Summary**
As an initial step in reducing the complexity of the monolithic `partition_xlsx()` function, extract all argument-handling to a separate `_XlsxPartitionerOptions` object which can be fully covered by isolated unit tests.
This code was from a prior XLSX bug-fix branch that did not get committed because of time constraints. I wanted to revisit it here because I need the benefits of this as part of some new work on PPTX that will require a separate options object that can be passed to delegate objects.
This approach was incubated in the chunking context and has produced a lot of opportunities there to decompose the logic into smaller components that are more understandable and isolated-test-able, without having to pass an extended list of option values in …
> rfctr(xlsx): extract _XlsxPartitionerOptions

- .github/workflows/ci.yml
CI fails every time on test_ingest_src (3.11) and test_ingest_dst (3.11) on what looks like a pip-install problem `(ModuleNotFoundError: No module named 'click')`. The error is exactly the same place every time.
- https://github.com/Unstructured-IO/unstructured/actions/runs/8622028071/job/23632669423
- https://github.com/Unstructured-IO/unstructured/actions/runs/8623541446
- https://github.com/Unstructured-IO/unstructured/actions/runs/8623056382
...
This PR skips the Python `3.11` ingest tests since the most important one is `3.10` anyway.
> build(ci): skip `python 3.11` in CI ingest jobs

- CHANGELOG.md
- test_unstructured/partition/pptx/test_pptx.py
- unstructured/__version__.py
- unstructured/partition/pptx.py
**Summary**
As we move to adding pluggable sub-partitioners, `partition_pptx()` will need to become sensitive to the `strategy` argument, in particular when it is set to "hi_res". Up until now there were no expensive operations (inference, OCR, etc.) incurred while partitioning PPTX so this argument was ignored.
After this PR, `partition_pptx()` still won't do anything with that value, other than pass it along to `_PptxPartitionerOptions` for safe-keeping, but now its ready for use by a `PicturePartitioner` (to come in a subsequent PR).
> feat(pptx): partition_pptx() accepts strategy arg

- CHANGELOG.md
- test_unstructured/partition/docx/test_docx.py
- test_unstructured/partition/pdf_image/test_pdf.py
- test_unstructured/partition/pptx/test_pptx.py
- test_unstructured/partition/test_auto.py
- unstructured/__version__.py
- unstructured/partition/auto.py
- unstructured/partition/common.py
- unstructured/partition/doc.py
- unstructured/partition/docx.py
- unstructured/partition/pdf.py
- unstructured/partition/ppt.py
- unstructured/partition/pptx.py
- unstructured/partition/xlsx.py
This small change will be useful for users who partition only fragments of their PDF documents. 
It's a small step towards addressing this issue: https://github.com/Unstructured-IO/unstructured/issues/2461
Related PRs:
* https://github.com/Unstructured-IO/unstructured/pull/2842
* https://github.com/Unstructured-IO/unstructured/pull/2673
> Introduce `start_page` argument to partitioning functions that assign `element.metadata.page_number`

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/partition/pdf_image/ocr.py
- unstructured/partition/utils/ocr_models/ocr_interface.py
- unstructured/partition/utils/ocr_models/paddle_ocr.py
- unstructured/partition/utils/ocr_models/tesseract_ocr.py
**Summary**
In preparation for using OCR for partitioners other than PDF, clean up typing in the OCR module.
> rfctr: improve typing in OCR modules

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/partition/pdf.py
- unstructured/partition/utils/config.py
This PR aims to add an environment variable to control the capture of embedded links in `partition_pdf()` for `fast` strategy.
Related PR: https://github.com/Unstructured-IO/unstructured/pull/2537
> feat: `partition_pdf()` add an environment variable to control the capture of embedded links

- CHANGELOG.md
- test_unstructured/partition/test_auto.py
- unstructured/__version__.py
- unstructured/partition/auto.py
Currently, `file_and_type_from_url()` does not correctly handle the `Content-Type` header. Specifically, it assumes that the header contains only the mime-type (e.g. `text/html`), however, [RFC 9110](https://www.rfc-editor.org/rfc/rfc9110#field.content-type) allows for additional directives — specifically the `charset` — to be returned in the header. This leads to a `ValueError` when loading a URL with a response Content-Type header such as `text/html; charset=UTF-8`.
To reproduce the issue:
```python
url = "https://arstechnica.com/space/2024/04/nasa-still-doesnt-understand-root-cause-of-orion-heat-shield-issue/"
partition(url=url)
```
Which will result in the following exception:
```python
{
"name": "ValueError",
"message": "Invalid file. …
```
> fix: parse URL response Content-Type according to RFC 9110

- CHANGELOG.md
- test_unstructured/partition/docx/test_doc.py
- test_unstructured/partition/pptx/test_ppt.py
- unstructured/__version__.py
- unstructured/partition/ppt.py
**Summary**
Make tests for DOC and PPT formats more concise and readable in preparation for adding one or two.
> rfctr: tidy up ppt+doc tests

- CHANGELOG.md
- test_unstructured/partition/docx/test_doc.py
- unstructured/__version__.py
- unstructured/partition/docx.py
- unstructured/partition/pptx.py
- unstructured/utils.py
**Summary**
A crude and OS-specific mechanism was used to detect when a path represented a temp-file. Change that to be robust across operating systems and localized configurations. The specific problem was for DOC files but this PR fixes it for PPT too which was prone to the same problem.
> fix(test): Remedy macOS-only test failure not triggered by CI

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/partition/api.py
- unstructured/partition/auto.py
- unstructured/partition/common.py
- unstructured/partition/csv.py
- unstructured/partition/doc.py
- unstructured/partition/email.py
- unstructured/partition/epub.py
- unstructured/partition/html.py
- unstructured/partition/image.py
- unstructured/partition/lang.py
- unstructured/partition/md.py
- unstructured/partition/msg.py
- unstructured/partition/odt.py
- unstructured/partition/org.py
- unstructured/partition/pdf.py
- unstructured/partition/pdf_image/inference_utils.py
- unstructured/partition/rst.py
- unstructured/partition/rtf.py
- unstructured/partition/text.py
- unstructured/partition/text_type.py
- unstructured/partition/tsv.py
- unstructured/partition/utils/sorting.py
- unstructured/partition/xml.py
**Summary**
Remedy the persistent type errors when importing `unstructured`. Give the partitioner type annotations a general scrubbing while we're at it.
> rfctr improve partitioner typing

- CHANGELOG.md
- test_unstructured/partition/utils/ocr_models/test_ocr_interface.py
- unstructured/__version__.py
- unstructured/partition/pdf.py
- unstructured/partition/pdf_image/ocr.py
- unstructured/partition/utils/ocr_models/ocr_interface.py
- unstructured/partition/utils/ocr_models/tesseract_ocr.py
**Summary**
File-types other than PDF need to use OCR on extracted images. Extract `OCRAgent.get_agent()` such that any file-type partitioner can use it without risking dependency on PDF-only extras.
> rfctr: extract OCRAgent.get_agent() out of PDF subtree

- CHANGELOG.md
- test_unstructured/partition/pdf_image/test_pdf_image_utils.py
- unstructured/__version__.py
- unstructured/partition/pdf_image/pdf_image_utils.py
This PR adds the ability to get the ratio of `cid` characters in embedded text extracted by `pdfminer`. This PR is the second part of moving `cid` related code from `unstructured-inference` to `unstructured` and works together with https://github.com/Unstructured-IO/unstructured-inference/pull/342.
> feat: `parition_pdf()` add ability to get `cid` ratio

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/partition/image.py
- unstructured/partition/pdf.py
Make the `filename` and `file` params for `partition_image` and `partition_pdf` match the other partitioners
> fix param types for partition_image and _pdf

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/metrics/evaluate.py
Changes introduced [in this PR](https://github.com/Unstructured-IO/unstructured/pull/2977) have been overwritten by mistake after merging https://github.com/Unstructured-IO/unstructured/pull/2973 - git did not detect a conflict there due to redesign in evaluate.py
> Quickfix: re-apply skip accuracy calculation enhancement

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/partition/pdf.py
The `links` param in `partition_pdf` was never used by the partitioner, but added when that metadata element was created. This removes the unused parameter since `links` are extracted during partitioning.
> remove unused links param

- CHANGELOG.md
- test_unstructured/partition/docx/test_docx.py
- unstructured/__version__.py
- unstructured/partition/docx.py
**Summary**
Noisy but trivial changes to `partition_docx()` environs and tests in preparation for DOCX image extraction. These changes are extracted here so they don't distract on the changes of substance to follow in the next PR.
> rfctr(docx): improve typing etc. in prep for docx image extraction

- CHANGELOG.md
- test_unstructured/partition/docx/test_doc.py
- unstructured/__version__.py
**Summary**
Organize DOC tests into related groups with markers. This makes it easier to assess coverage and find tests related to particular behaviors.
This is in preparation for adding tests related to DOC image extraction.
No code changes, purely line-block moves.
- Move module-level fixtures to the bottom.
- Organize tests into related groups with markers.
> rfctr(doc): organize test_doc.py

- CHANGELOG.md
- test_unstructured/partition/docx/test_docx.py
- unstructured/__version__.py
- unstructured/partition/docx.py
**Reviewers:** Probably easier to review first and second commits separately as the first one adds all the new code and tests (without installing it), and the second one installs it into the partitioner along with the required changes to code and tests.
**Summary**
Enable communication of partitioning options to sub-partitioners, in particular to the pluggable `PicturePartitioner` coming in a closely subsequent PR to implement image-extraction and OCR for DOCX, DOC, and ODT formats.
In general, validation of partitioning options as well as assigning default values and computing derived partitioning settings can be extracted from partitioners into a neatly encapsulated separate object. This simplifies the core partitioning code by removing the noise associated with …
> rfctr(docx): extract DocxPartitionerOptions

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/partition/doc.py
- unstructured/partition/pptx.py
**Summary**
Remedy disk-space leak where `partition_doc()` would leave a copy of each `.doc` file passed as a file-like object on disk.
`partition_doc()` creates a temporary file in which it writes each source-document provided as a file-like object. This file is not deleted and disk consumption grows without bound.
The `convert_office_doc()` function used to convert DOC->DOCX uses a command-line program provided with LibreOffice to convert do the conversion. Because this command-line program operates in a different memory space, the source file cannot be passed as an in-memory object and needs to be on the filesystem. When the DOC file is passed as a file-like object, it is written to disk so the conversion program has access to it. It is not deleted afterward.
Fix …
> fix(doc): fix disk-space leak

- CHANGELOG.md
- test_unstructured/partition/docx/test_docx.py
- unstructured/__version__.py
- unstructured/partition/docx.py
**Summary**
The behavior of an image sub-partitioner can be partially determined by the partitioning strategy, for example whether it is "hi_res" or "fast". Add this parameter to `partition_docx()` so it can pass it along to `DocxPartitionerOptions` which will make it available to any image sub-partitioners.
> feat(docx): add strategy parameter to partition_docx()

- CHANGELOG.md
- pyproject.toml
- unstructured/__version__.py
- unstructured/nlp/patterns.py
- unstructured/partition/email.py
**Summary**
Avoid `SyntaxWarning` and/or `SyntaxError` messages when importing `unstructured.nlp.patterns` by using raw strings (`"r"` prefix) for regex patterns which may contain `\x` character sequences not recognized by the Python parser for normal strings.
Fixes: #2495
> fix: use raw strings for regex patterns

- CHANGELOG.md
- typings/pypandoc/__init__.pyi
- unstructured/__version__.py
- unstructured/partition/docx.py
- unstructured/partition/odt.py
Remedy disk-space leak where `partition_odt()` would leave an on-disk copy of each `.odt` file passed as a file-like object.
`partition_odt()` creates a temporary file in which it writes each source-document provided as a file-like object. This file is not deleted and disk consumption grows without bound.
The `convert_and_partition_docx()` function used to convert ODT->DOCX uses `pandoc` (a command-line program) to do the conversion. Because this command-line program operates in a different memory space, the source file cannot be passed as an in-memory object and needs to be on the filesystem. When the ODT source-document is passed as a file-like object, it is written to disk so the conversion program has access to it. It is not deleted afterward.
Fix this by writing the temporary source …
> fix(odt): fix disk-space leak in partition_odt()

- CHANGELOG.md
- test_unstructured/partition/docx/test_doc.py
- test_unstructured/partition/odt/test_odt.py
- test_unstructured/unit_utils.py
- unstructured/__version__.py
- unstructured/partition/doc.py
- unstructured/partition/odt.py
**Summary**
Because DOCX now supports the `strategy` argument to control aspects of image extraction, `partition_doc()` and `partition_odt()` will need to support it to because they delegate partitioning to `partition_docx()`. This will allow image extraction to work the same way for those two additional document-types.
> feat(docx): add strategy parameter to DOC and ODT

- test_unstructured/partition/test_api.py
A `partition_via_api` test that only runs on `main` was [failing](https://github.com/Unstructured-IO/unstructured/actions/runs/9159429513/job/25181600959) with the following output, likely due to the change in the default behavior for `skip_infer_table_types`. This PR explicitly sets the `skip_infer_table_types` param to avoid the failure..
```python
=========================== short test summary info ============================
FAILED test_unstructured/partition/test_api.py::test_partition_via_api_with_no_strategy - AssertionError: assert 'Zejiang Shen® (<), Ruochen Zhang?, Melissa Dell®, Benjamin Charles Germain Lee?, Jacob Carlson®, and Weining Li®' != 'Zejiang Shen® (<), Ruochen Zhang?, Melissa Dell®, Benjamin Charles Germain Lee?, Jacob Carlson®, and Weining Li®'
+  where 'Zejiang …
```
> fix: set `skip_infer_tables` explicitly in `test_partition_via_api_with_no_strategy`

- CHANGELOG.md
- pyproject.toml
- test_unstructured/partition/docx/test_docx.py
- unstructured/__version__.py
**Summary**
I preparation for adding DOCX pluggable image extraction, organize a few of the DOCX tests to be parallel to very similar tests for the DOC and ODT partitioners.
> rfctr(docx): organize docx tests

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/partition/xml.py
Closes #3078. Sets `resolve_entities=False` for parsing XML with `lxml` in `partition_xml` to avoid text being dynamically injected into the document.
`pytest test_unstructured/partition/test_xml.py` continues to pass with the update.
> fix: set `resolve_entities=False` in `partition_xml`

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/documents/elements.py
A couple of parameters needed for DOCX image extraction were not added as parameters to the `ElementMetadata` constructor when they were added as known fields.
Also repair a couple gaps in alphabetical ordering cause by recent additions.
> fix: add missing params to ElementMetadata

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/partition/common.py
- unstructured/partition/utils/ocr_models/paddle_ocr.py
- unstructured/partition/utils/ocr_models/tesseract_ocr.py
- change some info level logging for per page processing into detail level logging on trace logger
- replace the try block in `document_to_element_list` to use `getattr` instead and add comment on the reason why sometimes `type` attribute may not exist for an element
> chore: reduce excessive logging

- docs/source/404.rst
Makes a custom 404 page that's the same as `index.html`, so any path shows the URL for the new docs.
> docs: make 404 pages same as index

- README.md
- setup.py
Updates documentation references in the README to point to https://docs.unstructured.io and cleans up a few sections of the README. Specifically:
- Removes an old API announcement
- Removes the section mentioning Chipper as a beta feature. Chipper is only available through the SaaS API.
Also adds a Python 3.12 tag to `setup.py` since we now support Python 3.12.
> docs: cleanup readme; add python 3.12

- CHANGELOG.md
- unstructured/partition/utils/config.py
- unstructured/partition/utils/ocr_models/google_vision_ocr.py
The Google Vision API allows for [configuration of the API endpoint](https://cloud.google.com/vision/docs/ocr#regionalization), to select if the data should be sent to the US or the EU. This PR adds an environment variable (`GOOGLEVISION_API_ENDPOINT`) to configure it.
> feat: configure googlevision api endpoint

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/ingest/logger.py
In some environments, such as Google Colab, loggers have a root handling that did not mask sensitive values. As a result, secrets such as API keys appeared in the logs. The PR removes root handlers when they exist to ensure sensitive values are handler properly.
Run the following in a Colab notebook. You should see two log outputs, one with the API key masked and one with it exposed.
```
!pip install unstructured
```
```python
import logging
import json
from unstructured.ingest.interfaces import (
ChunkingConfig,
EmbeddingConfig,
PartitionConfig,
ProcessorConfig,
ReadConfig,
)
partition_config = PartitionConfig(
partition_by_api=True,
api_key="super secret",
)
from unstructured.ingest.logger import ingest_log_streaming_init
ingest_log_streaming_init(logging.INFO)
logger = …
```
> fix: remote root handlers when they exist

- Makefile
This PR changes two `python` commands in `Makefile` to use `python3` to be consistent with other make commands. This makes it more explicit on which python to use when the makefile is used outside of a controlled virtualenv where only one python exists.
> chore: use python3 consistently in makefile

- CHANGELOG.md
- test_unstructured/documents/test_html.py
- unstructured/__version__.py
- unstructured/documents/html.py
- unstructured/documents/xml.py
- unstructured/partition/common.py
- unstructured/partition/html.py
**Summary**
In preparation for further work on HTMLDocument, organize the organic growth in `documents/tests_html.py` and improving typing and expression.
**Reviewers:** Commits are groomed and review is probably eased by going commit-by-commit
> rfctr(html): organize and improve HTMLDocument tests

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/ingest/v2/cli/base/cmd.py
- unstructured/ingest/v2/cli/cmds/__init__.py
- unstructured/ingest/v2/cli/cmds/weaviate.py
- unstructured/ingest/v2/cli/interfaces.py
- unstructured/ingest/v2/interfaces/connector.py
- unstructured/ingest/v2/interfaces/downloader.py
- unstructured/ingest/v2/interfaces/upload_stager.py
- unstructured/ingest/v2/interfaces/uploader.py
- unstructured/ingest/v2/pipeline/steps/stage.py
- unstructured/ingest/v2/processes/connectors/local.py
- unstructured/ingest/v2/processes/connectors/weaviate.py
Add weaviate output connector to those supported in the new v2 ingest framework. Some fixes were needed to the upoad stager step as this was the first connector moved over that leverages this part of the pipeline.
> feat: migrate weaviate connector to new framework

- CHANGELOG.md
- test_unstructured/documents/test_html.py
- unstructured/__version__.py
- unstructured/documents/html.py
**Summary**
Make `._find_articles()` and `._find_main` into `._articles` and `._main` properties on HTMLDocument, respectively.
After prior refactorings, these two functions now each require only `self` and can become `@lazyproperty`s on `HTMLDocument`. This ensures they are computed at most once. In addition, their close relationship to `HTMLDocument` is indicated by their membership as methods rather than "loose" functions.
> rfctr(html): promote HTMLDoc candidate methods

- CHANGELOG.md
- test_unstructured/partition/test_html.py
- unstructured/__version__.py
- unstructured/documents/elements.py
- unstructured/documents/html.py
- unstructured/file_utils/filetype.py
- unstructured/partition/common.py
- unstructured/partition/html.py
**Summary**
Remove use of `partition.common.document_to_element_list()` by `HTMLDocument`. The transitive coupling with layout-inference through this shared function have been the source of frustration and a drain on engineering time and there's no compelling reason for the two to share this code.
`partition_html()` uses `partition.common.document_to_element_list()` to get finalized elements from `HTMLDocument` (pages). This gives rise to a very nasty coupling between `DocumentLayout`, used by `unstructured_inference`, and `HTMLDocument`. `document_to_element_list()` has evolved to work for both callers, but they share very few common characteristics with each other.
This coupling is bad news for us and also, importantly, for the inference and page layout folks …
> rfctr(html): break coupling to DocumentLayout

- .github/actions/base-cache/action.yml
- .github/actions/base-ingest-cache/action.yml
- .github/workflows/ci.yml
- .github/workflows/release-version-alert.yml
**Summary**
Silence the long list of warnings we get in CI from using Node 16 actions by updating to Node 20 versions.
> ci: update to Node 20 actions

- CHANGELOG.md
- setup.cfg
- test_unstructured/documents/test_html.py
- test_unstructured/partition/test_html.py
- unstructured/__version__.py
- unstructured/documents/html.py
- unstructured/documents/html_elements.py
- unstructured/partition/html.py
**Summary**
Pagination of HTML documents is currently unused. The `Page` class and concept were deeply embedding in the legacy organization of HTML partitioning code due to the legacy `Document` (= pages of elements) domain model. Remove this concept from the code such that elements are available directly from the partitioner.
- Pagination can be re-added later if we decide we want it again. A re-implementation would be much simpler and much lower impact to the structure of the code and introduce much less additional complexity, similar to the approach we take in `partition_docx()`.
> rfctr(html): drop page concept

- CHANGELOG.md
- test_unstructured_ingest/expected-structured-output/dropbox/handbook-1p.docx.json
- test_unstructured_ingest/expected-structured-output/dropbox/nested-1/ideas-page.html.json
- test_unstructured_ingest/expected-structured-output/dropbox/nested-2/ideas-page.html.json
- test_unstructured_ingest/expected-structured-output/dropbox/science-exploration-1p.pptx.json
- test_unstructured_ingest/test-ingest-src.sh
- unstructured/__version__.py
- unstructured/ingest/v2/processes/connectors/fsspec/dropbox.py
The Dropbox source connector currently raises exceptions when indexing files due to two issues: a path formatting idiosyncrasy of the Dropbox library and a divergence in the definition of the Dropbox libraries fs.info method, expecting a 'url' parameter rather than 'path'. 
* add a `/` prefix to file path used by DropboxIndexer
* override the fsspec sterilize_info method in DropboxIndexer to call `self.fs.info` with `url` rather than `path`; to accommodate for the fact that `dropboxdrivefs` diverges with this signature
* remove `dropbox.sh` from ignored source tests
* update test fixtures (now that the dropbox connector has been fixed and not skipped)
`dropbox.sh` source ingest test now succeeds (and is no longer ignored)
> fix: dropbox source connector file path bugs

- .github/workflows/ci.yml
- requirements/base.txt
- requirements/deps/constraints.txt
- requirements/dev.txt
- requirements/extra-pdf-image.txt
- requirements/huggingface.txt
- requirements/ingest/chroma.txt
- requirements/ingest/confluence.txt
- requirements/ingest/embed-aws-bedrock.txt
- requirements/ingest/embed-huggingface.txt
- requirements/ingest/embed-openai.txt
- requirements/ingest/embed-vertexai.txt
- requirements/ingest/embed-voyageai.txt
- requirements/ingest/jira.txt
- requirements/ingest/slack.txt
- requirements/test.txt
Version bumps for the week of 2024-06-17. There is a now a pin on `numpy` due to a breaking change in the latest version that we'll need to investigate and remove in a subsequent PR.
> build(deps): version bumps for 2024-06-17

- CHANGELOG.md
- test_unstructured/partition/test_common.py
- test_unstructured/partition/test_doc.py
- test_unstructured/partition/test_epub.py
- test_unstructured/partition/test_odt.py
- test_unstructured/partition/test_org.py
- test_unstructured/partition/test_rst.py
- test_unstructured/partition/test_rtf.py
- typings/pypandoc/__init__.pyi
- unstructured/__version__.py
- unstructured/file_utils/file_conversion.py
- unstructured/partition/common.py
- unstructured/partition/doc.py
- unstructured/partition/epub.py
- unstructured/partition/html.py
- unstructured/partition/odt.py
- unstructured/partition/org.py
- unstructured/partition/rst.py
- unstructured/partition/rtf.py
**Summary**
Remove `unstructured.partition.html.convert_and_partition_html()`. Move file-type conversion (to HTML) responsibility to each brokering partitioner that uses that strategy and let them call `partition_html()` for themselves with the result.
Rationale:
- `partition_html()` does not want or need to know which partitioners might broker partitioning to it.
- Different brokering partitioners have their own methods to convert their format to HTML and quirks that may be involved for their format. Avoid coupling them so they can evolve independently.
- The core of the conversion work is already encapsulated in `unstructured.partition.common.convert_file_to_html_text_using_pandoc()`.
- `convert_and_partition_html()` represents an additional brokering layer with …
> rfctr(html): drop convert_and_partition_html()

- CHANGELOG.md
- test_unstructured/partition/pdf_image/test_pdf.py
- test_unstructured/partition/pdf_image/test_pdf_image_utils.py
- unstructured/__version__.py
- unstructured/partition/pdf.py
- unstructured/partition/pdf_image/pdf_image_utils.py
The Issue:
When extracting images from pdfs, we use the metadata page number to index into a list of the images. However, the metadata page number can now be changed via `starting_page_number`. To get the true page index, we need to subtract this value.
Testing:
Run this snippet in a python shell. Before the fix, this throws an IndexError. On this branch, it will return the elements.
```
filename = "example-docs/layout-parser-paper-with-table.pdf"
partition(filename, strategy="hi_res", extract_image_block_types=["Image", "Table"], starting_page_number=20)
```
> fix: fix `IndexError` when partioning a pdf with `starting_page_number`

- CHANGELOG.md
- Dockerfile-amd64
- unstructured/__version__.py
This PR aims to fix a `test_dockerfile` job [failure](https://github.com/Unstructured-IO/unstructured/actions/runs/9613636416/job/26517074221?pr=3234) in CI after `base-images` repo update.
> fix: update base image SHA for amd64 wolfi

- CHANGELOG.md
- test_unstructured/partition/test_auto.py
- unstructured/__version__.py
- unstructured/partition/auto.py
**Summary**
Remedy gap where `strategy` argument passed to `partition()` was not forwarded to `partition_doc()` or `partition_odt()` and so was not making its way to `partition_docx()`.
> fix(auto): partition() passes strategy to DOC,ODT

- CHANGELOG.md
- test_unstructured/partition/test_docx.py
- unstructured/__version__.py
- unstructured/partition/docx.py
**Summary**
The `python-docx` error `docx.opc.exceptions.PackageNotFoundError` arises both when no file exists at the given path and when the file exists but is not a ZIP archive (and so is not a DOCX file).
This ambiguity is unwelcome when diagnosing the error as the two possible conditions generally indicate a different course of action to resolve the error.
Add detailed validation to `DocxPartitionerOptions` to distinguish these two and provide more precise exception messages.
- `python-pptx` shares the same OPC-Package (file) loading code used by `python-docx`, so the same ambiguity will be present in `python-pptx`.
- It would be preferable for this distinguished exception behavior to be upstream in `python-docx` and `python-pptx`. If we're willing to take the …
> feat(docx): differentiate no-file from not-ZIP

- README.md
Adds links to the serverless api. README updates look like the following:
> docs: add link to serverless api in readme

- CHANGELOG.md
- test_unstructured/partition/html/test_parser.py
- typings/lxml/etree/__init__.pyi
- typings/lxml/etree/_cleanup.pyi
- unstructured/__version__.py
- unstructured/partition/html/parser.py
**Note**
This refines the new HTML parser but _does not install it_. This is why no changes to ingest test expectations or other unit-tests are required here. Installing the new parser will happen in the next PR #3218.
**Summary**
The initial version of the parser (purposely) raised on a block element nested inside a phrasing element. While such nesting is not valid according to the HTML Standard, it is accepted by the browser and does happen in the wild.
The refinements here handle this situation similarly to how the browser does, breaking phrasing at the block element boundaries and starting it up again after the block element.
Unfortunately this adds complexity to the parser, but it makes the parser robust against pretty much any HTML we're likely to encounter and partitions it …
> rfctr(html): refine HTML parser

- test_unstructured_ingest/test-ingest-src.sh
Disable sharepoint ingest test to unblock development. We need to re-enable this test when the sharepoint credentials are updated.
> ci: disable sharepoint ingest test

- CHANGELOG.md
- requirements/extra-paddleocr.in
- requirements/extra-paddleocr.txt
- unstructured/__version__.py
- Bump unstructured.paddleocr to `2.8.0.1` which removed `lmdb` dependency due to license issue.
> build(deps): bump unstructured.paddleocr 2.8.0.1

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/nlp/tokenize.py
**Summary**
The implementation of `tempfile.NamedTemporaryFile` on Windows Python is problematic in certain situations.
In particular, it raises `PermissionError` when attempting to access the temporary file by name rather than just by the file-descriptor returned by the context-manager.
Remedy this situation by using `tempfile.TemporaryDirectory` instead and using a file name of our choosing. The temporary directory is deleted with all its contents when the context manager closes so the effect is the same and does not produce the error on Windows.
> fix(nltk): remedy Windows temp-file problem

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/ingest/v2/processes/connectors/__init__.py
- unstructured/ingest/v2/processes/connectors/mongodb.py
- unstructured/ingest/v2/processes/connectors/pinecone.py
- unstructured/ingest/v2/processes/connectors/sharepoint.py
- unstructured/ingest/v2/processes/connectors/singlestore.py
Looks like some connectors were never added to the registry explicitly since that change was introduced. All of them are now updated.
> bugfix: conform all connectors to be added to registry

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/ingest/v2/processes/connectors/google_drive.py
At times, the google drive response doens't have some of the metadata we're grabbing to populate the `FileData` metadata. This is fine, but without the added safegaurds, this can cause a `KeyError`.
> bugfix: google drive connector metadata safegaurds

- CHANGELOG.md
- test_unstructured_ingest/expected-structured-output/box/handbook-1p.docx.json
- test_unstructured_ingest/expected-structured-output/box/nested-1/ideas-page.html.json
- test_unstructured_ingest/expected-structured-output/box/nested-1/nested-2/ideas-page.html.json
- test_unstructured_ingest/expected-structured-output/box/science-exploration-1p.pptx.json
- test_unstructured_ingest/expected-structured-output/dropbox/handbook-1p.docx.json
- test_unstructured_ingest/expected-structured-output/dropbox/nested-1/ideas-page.html.json
- test_unstructured_ingest/expected-structured-output/dropbox/nested-2/ideas-page.html.json
- test_unstructured_ingest/expected-structured-output/dropbox/science-exploration-1p.pptx.json
- test_unstructured_ingest/expected-structured-output/gcs/ideas-page.html.json
- test_unstructured_ingest/expected-structured-output/gcs/nested-1/fake-text.txt.json
- test_unstructured_ingest/expected-structured-output/gcs/nested-1/nested/ideas-page.html.json
- test_unstructured_ingest/expected-structured-output/gcs/nested-2/fake-text.txt.json
- test_unstructured_ingest/expected-structured-output/gcs/nested-2/nested/ideas-page.html.json
- test_unstructured_ingest/expected-structured-output/gcs/nested-2/stanley-cups.xlsx.json
- unstructured/__version__.py
- unstructured/ingest/v2/processes/connectors/fsspec/fsspec.py
If the id value exists in the stats response from fsspec, save it as a `file_id` field in the metadata being persisted on each element.
> feat: save file id for all fsspec connectors if present

- CHANGELOG.md
- example-docs/eml/family-day.eml
- test_unstructured/partition/test_email.py
- unstructured/__version__.py
- unstructured/partition/email.py
Currently, the email partitioner removes only `=\n` characters during the clearing process. However, email content sometimes contains `=\r\n` characters, especially when read from file-like objects such as `SpooledTemporaryFile` (the file type used in our API). This PR updates the email partitioner to remove both `=\n` and `=\r\n` characters during the clearing process.
```
filename = "example-docs/eml/family-day.eml"
elements = partition_email(
filename=filename,
)
print(f"From filename: {elements[3].text}")
with open(filename, "rb") as test_file:
spooled_temp_file = tempfile.SpooledTemporaryFile()
spooled_temp_file.write(test_file.read())
spooled_temp_file.seek(0)
elements = partition_email(file=spooled_temp_file)
print(f"From spooled_temp_file: {elements[3].text}")
```
**Results:**
- …
> enhancement: improve text clearing process in `email` partitioning

- CHANGELOG.md
- test_unstructured/file_utils/test_model.py
- test_unstructured/partition/test_auto.py
- unstructured/__version__.py
- unstructured/file_utils/filetype.py
- unstructured/file_utils/model.py
- unstructured/partition/auto.py
**Summary**
Replace conditional explicit import of partitioner modules in `.partition.auto` with the new `_PartitionerLoader` class. This avoids unbound variable warnings and is much less noisy.
`_PartitionerLoader` makes use of the new `FileType` property `.importable_package_dependencies` to determine whether all required packages are importable before dispatching the file to its partitioner. It uses `FileType.extra_name` to form a helpful error message when a dependency is not installed, so the caller knows which `pip install` extra to specify to remedy the error.
`PartitionerLoader` uses the `FileType` properties `.partitioner_module_qname` and `partitioner_function_name` to load
the partitioner once its dependencies are verified. Loaded partitioners are cached with module lifetime …
> rfctr(auto): add _PartitionerLoader

- CHANGELOG.md
- requirements/deps/constraints.txt
- requirements/extra-pdf-image.txt
- requirements/huggingface.txt
- requirements/ingest/chroma.txt
- requirements/ingest/embed-aws-bedrock.txt
- requirements/ingest/embed-huggingface.txt
- requirements/ingest/embed-openai.txt
- requirements/ingest/embed-vertexai.txt
- requirements/ingest/embed-voyageai.txt
- requirements/ingest/gcs.txt
- requirements/ingest/pinecone.txt
- test_unstructured_ingest/dest/chroma.sh
- unstructured/__version__.py
- unstructured/ingest/connector/pinecone.py
- unstructured/ingest/v2/processes/connectors/pinecone.py
the pinecone python package moved their importing of PineconeApiException
Chroma `sleep` added because even thought there is a `wait`, there is still some sort of timing issue.
> bugfix [OSS-67]: update import of pinecone exception

- CHANGELOG.md
- requirements/ingest/embed-huggingface.in
- requirements/ingest/embed-huggingface.txt
- unstructured/__version__.py
- unstructured/embed/huggingface.py
Similar to https://github.com/Unstructured-IO/unstructured/pull/3433.
This PR aims to update `HuggingFaceEmbeddingEncoder` to use `HuggingFaceEmbeddings` from `langchain_huggingface` package instead of the deprecated version from `langchain-community`. This resolves the deprecation warning and ensures compatibility with future versions of langchain.
```
from unstructured.documents.elements import Text
from unstructured.embed.huggingface import HuggingFaceEmbeddingConfig, HuggingFaceEmbeddingEncoder
embedding_encoder = HuggingFaceEmbeddingEncoder(
config=HuggingFaceEmbeddingConfig()
)
elements = embedding_encoder.embed_documents(
elements=[Text("This is sentence 1"), Text("This is sentence 2")],
)
query = "This is the query"
query_embedding = embedding_encoder.embed_query(query=query) …
```
> fix: update HuggingFaceEmbeddingEncoder to use `langchain_huggingface` instead of `langchain-community`

- CHANGELOG.md
- test_unstructured/file_utils/test_filetype.py
- unstructured/file_utils/filetype.py
**Summary**
The `content_type` argument received by `partition()` from the API is sometimes unreliable for MS-Office 2007+ MIME-types. What we've observed is that it gets the MS-Office bit right but falls down on distinguishing PPTX from DOCX or XLSX.
Confirmation of these types is simple, fast, and reliable. Confirm all MS-Office `content_type` argument values asserted by callers of `detect_filetype()` and correct swapped values.
> fix(file): confirm or correct asserted DOCX, PPTX, and XLSX content types

- CHANGELOG.md
- example-docs/not-unstructured-payload.json
- test_unstructured/file_utils/test_filetype.py
- test_unstructured/partition/test_auto.py
- unstructured/__version__.py
- unstructured/file_utils/filetype.py
- unstructured/file_utils/model.py
**Summary**
A DOC, PPT, or XLS file sent to partition() as a file-like object is misidentified as a MSG file and raises an exception in python-oxmsg (which is used to process MSG files).
**Fix**
DOC, PPT, XLS, and MSG are all Microsoft OLE-based files, aka. Compound File Binary Format (CFBF). These can be reliably distinguished by inspecting magic bytes in certain locations. `libmagic` is unreliable at this or doesn't try, reporting the generic `"application/x-ole-storage"` which corresponds to the "container" CFBF format (vaguely like a Microsoft Zip format) that all these document types are stored in.
Unconditionally use `filetype.guess_mime()` provided by the `filetype` package that is part of the base unstructured install. Unlike `libmagic`, this package reliably detects the …
> fix(file): fix OLE-based file-type auto-detection

- CHANGELOG.md
- test_unstructured_ingest/test-ingest-dest.sh
- unstructured/__version__.py
- unstructured/ingest/README.md
- unstructured/ingest/__init__.py
Any time `unstructed.ingest` is imported, this deprecation warning gets emitted:
```
DeprecationWarning: unstructured.ingest will be removed in a future version
```
> feat: Add deprecation warning on import of any ingest code

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/partition/pdf_image/pdfminer_processing.py
- unstructured/partition/pdf_image/pdfminer_utils.py
This PR addresses an issue in `pdfminer` library's embedded image extraction process. Previously, some extracted "images" were incorrect, including embedded text elements, resulting in oversized bounding boxes. This update refines the extraction process to focus on actual images with more accurate, smaller bounding boxes. 
PDF: [test_pdfminer_text_extraction.pdf](https://github.com/user-attachments/files/16448213/test_pdfminer_text_extraction.pdf)
```
elements = partition_pdf(
filename="test_pdfminer_text_extraction",
strategy=strategy,
languages=["chi_sim"],
analysis=True,
)
```
**Results**
- this `PR`
- `main` branch
> Improve pdfminer embedded image extraction in `pdf` partitioning

- CHANGELOG.md
- Dockerfile
- Makefile
- requirements/deps/constraints.txt
- requirements/extra-pdf-image.in
- requirements/extra-pdf-image.txt
- requirements/extra-pptx.txt
- requirements/ingest/embed-aws-bedrock.txt
- requirements/ingest/embed-huggingface.txt
- requirements/ingest/embed-openai.txt
- requirements/ingest/embed-vertexai.txt
- requirements/ingest/embed-voyageai.txt
- requirements/ingest/singlestore.txt
- requirements/test.txt
- test_unstructured/partition/pdf_image/test_analysis.py
- test_unstructured/partition/pdf_image/test_ocr.py
- test_unstructured/partition/pdf_image/test_pdf.py
- unstructured/__version__.py
- unstructured/chunking/base.py
- unstructured/ingest/connector/notion/helpers.py
- unstructured/ingest/v2/pipeline/steps/chunk.py
- unstructured/ingest/v2/pipeline/steps/embed.py
- unstructured/ingest/v2/pipeline/steps/partition.py
- unstructured/partition/pdf.py
- unstructured/partition/utils/constants.py
- unstructured/partition/utils/ocr_models/tesseract_ocr.py
- unstructured/utils.py
A second attempt at https://github.com/Unstructured-IO/unstructured/pull/3360, this PR removes unstructured's dependency on its own fork of `pytesseract`. (The original reason for the fork, the addition of `run_and_get_multiple_output`, was removed [here](https://github.com/madmaze/pytesseract/releases/tag/v0.3.12).)
> Remove unstructured.pytesseract fork

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/partition/pdf_image/pdf_image_utils.py
Closes [#3503](https://github.com/Unstructured-IO/unstructured/issues/3503).
This PR prevents creation of `figures` directory for saving image blocks (`Image`, `Table`) when `extract_image_block_to_payload` parameter is set to True
```
elements = partition_image(
filename="example-docs/img/embedded-images-tables.jpg",
strategy="hi_res",
extract_image_block_types=["Image", "Table"],
extract_image_block_to_payload=True,
)
```
**Results:**
- `Main` Branch: `figures` directory is created.
- `PR`: `figures` directory is not created.
> Refactor image block extraction in `pdf` partitioning

- CHANGELOG.md
- requirements/deps/constraints.txt
- requirements/extra-pdf-image.in
- requirements/extra-pdf-image.txt
- unstructured/__version__.py
Closes #3521.
This PR resolves an installation error with `pytesseract>=0.3.12` that occurred during `pip install unstructured[pdf]==0.15.3`.
**Run following command in main branch and this PR**
```
pip uninstall -y pytesseract && pip install ".[pdf]"
```
**Results**
- `main` branch
```
INFO: pip is looking at multiple versions of unstructured[pdf] to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement pytesseract>=0.3.12; extra == "pdf" (from unstructured[pdf]) (from versions: 0.1, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.2, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.2.8, 0.2.9, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.3.10)
ERROR: No matching …
```
> fix: `pytesseract>=0.3.12` installation error while installing `pdf` extra

- CHANGELOG.md
- docker/rockylinux-9.2/Dockerfile
- requirements/base.txt
- unstructured/__version__.py
- unstructured/nlp/tokenize.py
This PR aims to roll back `nltk` to `3.8.1` which bumped to `3.8.2` in https://github.com/Unstructured-IO/unstructured/pull/3512 because `3.8.2` is no longer available in PyPI due to some issues(https://github.com/nltk/nltk/issues/3301)
> build: downgrade `nltk` version

- CHANGELOG.md
- Makefile
- requirements/extra-pdf-image.in
- requirements/extra-pdf-image.txt
- test_unstructured/partition/pdf_image/test_image.py
- test_unstructured/partition/pdf_image/test_ocr.py
- test_unstructured/partition/pdf_image/test_pdf.py
- unstructured/__version__.py
- unstructured/partition/strategies.py
- unstructured/partition/utils/constants.py
- unstructured/partition/utils/ocr_models/tesseract_ocr.py
This PR reverts `pytesseract` dependency to `unstructured.pytesseract` fork due to the unavailability of some recent release versions of `pytesseract` on PyPI. 
This PR also addresses an issue encountered during the publication of `unstructured==0.15.4` to PyPI. The error was due to the fact that PyPI does not allow direct dependencies from Version Control System URLs like GitHub in the `install_requires` or `extras_require` sections of the `setup.py` file.
> feat: replace `pytesseract` with `unstructured.pytesseract` fork

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/nlp/tokenize.py
Closes #3543.
This PR addresses an issue with the NLTK data download process. Previously, when downloading NLTK data, a nested "nltk_data" directory was created within the parent "nltk_data" directory if the parent directory already existed. This redundant directory structure led to two significant problems:
- errors in checking if data had already been downloaded, potentially causing redundant downloads in subsequent calls.
- failures in loading models from the downloaded NLTK data due to incorrect path resolution.
This fix modifies the NLTK data download logic to prevent creation of unnecessary nested directories. If the download path ends with "nltk_data" and that directory already exists, we now use the existing directory instead of creating a new nested one.
CI should pass.
> fix: `nltk` data download path to prevent redundant nested directories

- CHANGELOG.md
- test_unstructured/partition/test_docx.py
- unstructured/__version__.py
- unstructured/partition/docx.py
**Summary**
Eliminate historical "idiosyncracies" of `table.metadata.text_as_html` HTML introduced by `partition_docx()`. Produce minified `.text_as_html` consistent with that formed by chunking.
- nested tables appear as their extracted text in the parent cell (no nested `<table>` elements in `.text_as_html`).
- DOCX `.text_as_html` is minified (no extra whitespace or thead, tbody, tfoot elements).
> rfctr(docx): DOCX emits std minified .text_as_html

- CHANGELOG.md
- test_unstructured/file_utils/test_filetype.py
- unstructured/__version__.py
- unstructured/file_utils/filetype.py
**Summary**
Do not assume MSG format when an OLE "container" file cannot be differentiated into DOC, PPT, XLS, or MSG. Fall back to extention-based identification in that case.
DOC, MSG, PPT, and XLS are all OLE files. An OLE file is, very roughly, a Microsoft-proprietary Zip format which "contains" a filesystem of discrete files and directories.
An OLE "container" is easily identified by inspecting the first 8 bytes of the file, so all we need to do is differentiate between the four subtypes we can process. The `filetype` module does a good job of this but it not perfect and does not identify MSG files.
Previously we assumed MSG format when none of DOC, PPT, or XLS was detected, but we discovered that `filetype` is not completely reliable at detecting these types. …
> fix(file): no default OLE subtype

- CHANGELOG.md
- requirements/extra-pdf-image.txt
- requirements/ingest/chroma.txt
- requirements/ingest/clarifai.txt
- requirements/ingest/embed-aws-bedrock.txt
- requirements/ingest/embed-huggingface.txt
- requirements/ingest/embed-mixedbreadai.txt
- requirements/ingest/embed-openai.txt
- requirements/ingest/embed-vertexai.txt
- requirements/ingest/embed-voyageai.txt
- requirements/ingest/gcs.txt
- requirements/ingest/google-drive.txt
- test_unstructured/file_utils/test_file_conversion.py
- test_unstructured/partition/test_email.py
- test_unstructured/staging/test_base.py
- test_unstructured/unit_utils.py
- unstructured/__version__.py
- unstructured/file_utils/file_conversion.py
- unstructured/partition/common.py
- unstructured/partition/email.py
- unstructured/partition/pdf_image/ocr.py
- unstructured/partition/pdf_image/pdf_image_utils.py
- unstructured/partition/pdf_image/pdfminer_utils.py
- unstructured/partition/ppt.py
Fix disk space leaks and Windows errors when accessing file.name on a NamedTemporaryFile
Uses of `NamedTemporaryFile(..., delete=False)` and/or uses of `file.name` of NamedTemporaryFile have been replaced with TemporaryFileDirectory to avoid a known issue: 
- https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile 
- https://github.com/Unstructured-IO/unstructured/issues/3390
The first 7 commits each address an individual occurrence of the issue if reviewers want to review commit-by-commit.
> bug: fix file_conversion disk leak

- test_unstructured/partition/test_api.py
Fix API tests (really more like integration tests) that run only on main. Also use less compute intensive files to speedup test time and remove a useless test.
Tests in `test_unstructured/partition/test_api.py` pass, temporarily running outside of main per per screenshot:
https://github.com/Unstructured-IO/unstructured/actions/runs/10754098974/job/29824415513
> chore: fix tests breaking on main

- scripts/user/process-pdf-parallel-through-api.sh
- scripts/user/split-pdf.sh
- scripts/user/unstructured-get-json.sh
Adds the bash script `process-pdf-parallel-through-api.sh` that allows splitting up a PDF into smaller parts (splits) to be processed through the API concurrently, and is re-entrant. If any of the parts splits fail to process, one can attempt reprocessing those split(s) by rerunning the script.
Note: requires the `qpdf` command line utility.
The below command line output shows the scenario where just one split had to be reprocessed through the API to create the final `layout-parser-paper_combined.json` output.
```
$ BATCH_SIZE=20 PDF_SPLIT_PAGE_SIZE=6 STRATEGY=hi_res \
./scripts/user/process-pdf-parallel-through-api.sh example-docs/pdf/layout-parser-paper.pdf
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0 …
```
> feat: utility script to process large PDFs through the API by script

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/metrics/table/table_alignment.py
It looks like we puts columns when we meant rows in one of the table metrics. @pravin-unstructured  flagged this.
> fix: Table metric typo

- CHANGELOG.md
- test_unstructured/partition/pdf_image/test_pdf.py
- test_unstructured/partition/pdf_image/test_pdfminer_processing.py
- test_unstructured/partition/pdf_image/test_pdfminer_utils.py
- test_unstructured/partition/test_auto.py
- test_unstructured_ingest/expected-structured-output/azure/Core-Skills-for-Biomedical-Data-Scientists-2-pages.pdf.json
- test_unstructured_ingest/expected-structured-output/biomed-api/65/11/main.PMC6312790.pdf.json
- test_unstructured_ingest/expected-structured-output/biomed-api/75/29/main.PMC6312793.pdf.json
- test_unstructured_ingest/expected-structured-output/biomed-path/07/07/sbaa031.073.PMC7234218.pdf.json
- test_unstructured_ingest/expected-structured-output/google-drive/recalibrating-risk-report.pdf.json
- test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper.pdf.json
- test_unstructured_ingest/expected-structured-output/s3/2023-Jan-economic-outlook.pdf.json
- test_unstructured_ingest/expected-structured-output/s3/Silent-Giant-(1).pdf.json
- test_unstructured_ingest/expected-structured-output/s3/page-with-formula.pdf.json
- test_unstructured_ingest/expected-structured-output/s3/recalibrating-risk-report.pdf.json
- unstructured/__version__.py
- unstructured/partition/pdf_image/pdfminer_processing.py
- unstructured/partition/pdf_image/pdfminer_utils.py
- unstructured/partition/utils/config.py
This PR implements splitting of `pdfminer` elements (`groups of text chunks`) into smaller bounding boxes (`text lines`). This implementation prevents loss of information from the object detection model and facilitates more effective removal of duplicated `pdfminer` text. This PR also addresses #3430.
> feat: improve pdfminer element processing

- .github/workflows/docker-publish.yml
- CHANGELOG.md
- unstructured/__version__.py
Reverts the CI change in #3624 and reenables the `arm64` build and publish steps.
> fix: reenable arm64 build

- .github/actions/base-cache/action.yml
- .github/actions/base-ingest-cache/action.yml
- .github/workflows/ci.yml
- Makefile
- test_unstructured_ingest/test-ingest-src.sh
This PR adds the requirement files for base and extras for the ingest cache's hash key.
- The current workflow uses only the ingest requirements to generate hash key for the gitaction cache
- Sometimes only base or extra requirements (like extra-pdf.txt) updated but not any ingest requirements -> this would mean the ingest test would fetch a cache with outdated non-ingest dependencies
- When we generate new ingest cache we actually do check first base and extra requirements and generate a base env before layer on top the ingest dependencies.
- This PR allows the ingest step to recognize changes to non-ingest dependency changes and trigger new cache generation when either ingest or base/extra requirement files changes.
This PR also bumps the setup python action version in cache actions; it …
> add requirements files to ingest cache hash key

- CHANGELOG.md
- test_unstructured/documents/test_elements.py
- unstructured/__version__.py
- unstructured/documents/elements.py
This PR fixes an occasional `KeyError` when calling `assign_and_map_hash_ids`. 
- This happens when the input `elements` has duplicated element instances or metadata.
- When there are duplications the logic to iterate through all elements and map their parent ids will raise an error when an already mapped parent id is up for mapping.
- The fix adds a logic to check if the parent id exists in `old_to_new_mapping` and if it doesn't we skip mapping it
This PR adds a unit test on this case and the test would fail without the fix.
> fix: fix occasional key error when mapping parent id

- CHANGELOG.md
- scripts/elasticsearch-test-helpers/destination_connector/elasticsearch_elements_mappings.json
- scripts/opensearch-test-helpers/destination_connector/opensearch_elements_mappings.json
- scripts/singlestore-test-helpers/schema.sql
- scripts/sql-test-helpers/create-pgvector-schema.sql
- scripts/sql-test-helpers/create-sqlite-schema.sql
- scripts/weaviate-test-helpers/elements.json
- test_unstructured/chunking/test_base.py
- test_unstructured/chunking/test_title.py
- test_unstructured/documents/test_elements.py
- test_unstructured/partition/test_text.py
- test_unstructured/staging/test_base.py
- test_unstructured_ingest/files/azure_cognitive_index_schema.json
- test_unstructured_ingest/unit/connector/test_sql_conform_dict.py
- unstructured/__version__.py
- unstructured/chunking/base.py
- unstructured/documents/elements.py
- unstructured/file_utils/filetype.py
- unstructured/ingest/connector/azure_cognitive_search.py
- unstructured/ingest/connector/sql.py
- unstructured/ingest/connector/weaviate.py
- unstructured/ingest/v2/processes/connectors/azure_cognitive_search.py
- unstructured/ingest/v2/processes/connectors/sql.py
- unstructured/ingest/v2/processes/connectors/weaviate.py
- unstructured/staging/base.py
- unstructured/staging/weaviate.py
**Summary**
Step 2 in prep for pluggable auto-partitioners, remove `regex_metadata` field from `ElementMetadata`.
- "regex-metadata" was an experimental feature that didn't pan out.
- It's implemented by one of the post-partitioning metadata decorators, so get rid of it as part of the cleanup before consolidating those decorators.
> rfctr(part): prepare for pluggable auto-partitioners 2

- CHANGELOG.md
- test_unstructured/partition/common/test_metadata.py
- unstructured/__version__.py
- unstructured/partition/common/metadata.py
**Summary**
Refine `@apply_metadata()` replacement decorator. Note it has not been installed yet.
- Apply `metadata_last_modified` arg with the `@apply_metadata()` decorator. No need for redundant processing in each partitioner.
- Add "unique-ify" step to fix any cases where the same `Element` or `ElementMetadata` instance was used more than once in the element stream. This prevents unexpected "multi-mutation" in downstream processes.
- Apply "global" metadata items before computing hash-ids. In particular, `.metadata.filename` is used in the hash computation and will produce different results if that's not already settled.
- Compute hash-ids _before_ computing `.metadata.parent_id`. This removes the need for mapping UUID element-ids to their hash counterpart and doing a fixup of …
> rfctr(meta): refine @apply_metadata() decorator

- CHANGELOG.md
- test_unstructured/partition/test_csv.py
- test_unstructured/partition/test_doc.py
- test_unstructured/partition/test_docx.py
- test_unstructured/partition/test_odt.py
- unstructured/__version__.py
- unstructured/partition/csv.py
- unstructured/partition/doc.py
- unstructured/partition/docx.py
- unstructured/partition/odt.py
**Summary**
Install new `@apply_metadata()` on CSV and DOCX and remove decoration from DOC and ODT.
- Working in alphabetical order and keeping PR size manageable, replace use of `@process_metadata()` and `@add_metadata_with_filetype()` decorators with `@apply_metadata()` on principal partitioners (those that do not delegate to other partitioners.
- Remove all decorators from delegating partitioners (DOC and ODT in this case); this removes the "double-decorating".
> rfctr(part): remove double-decoration 1

- CHANGELOG.md
- test_unstructured/partition/test_ppt.py
- test_unstructured/partition/test_pptx.py
- test_unstructured/partition/test_xlsx.py
- test_unstructured/partition/test_xml.py
- unstructured/__version__.py
- unstructured/partition/csv.py
- unstructured/partition/pptx.py
- unstructured/partition/tsv.py
- unstructured/partition/xlsx.py
- unstructured/partition/xml.py
**Summary**
Install new `@apply_metadata()` on PPTX, TSV, XLSX, and XML and remove decoration from PPT.
- Alphabetical order turns out to be hard, so this is the remaining "easy" delegating partitioner and the remaining principal partitioners.
- Replace use of `@process_metadata()` and `@add_metadata_with_filetype()` decorators with `@apply_metadata()` on principal partitioners (those that do not delegate to other partitioners.
- Remove all decorators from delegating partitioners (PPT in this case); this removes the "double-decorating".
> rfctr(part): remove double-decoration 2

- CHANGELOG.md
- test_unstructured/metrics/test_element_type.py
- test_unstructured/partition/test_email.py
- test_unstructured/partition/test_msg.py
- test_unstructured_ingest/expected-structured-output/outlook/21be155fb0c95885.eml.json
- test_unstructured_ingest/expected-structured-output/outlook/497eba8c81c801c6.eml.json
- test_unstructured_ingest/expected-structured-output/outlook/4a16a411f162ebbb.eml.json
- test_unstructured_ingest/expected-structured-output/salesforce/EmailMessage/02sHu00001efErPIAU.eml.json
- test_unstructured_ingest/expected-structured-output/salesforce/EmailMessage/02sHu00001efErQIAU.eml.json
- unstructured/__version__.py
- unstructured/partition/email.py
- unstructured/partition/msg.py
**Summary**
Remove double-decoration from EML and MSG.
- These needed to wait to the end because `partition_email()` and `partition_msg()` can use any other partitioner for one of their attachments.
> rfctr(part): remove double-decoration 5

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/partition/ppt.py
Somehow this slipped through the earlier PR removing double-decoration from PPTX.
Remove the decorators from PPT (because it is a delegating partitioner) and let the decorators on the proxy partitioner (`partition_pptx()`) do the needful.
> rfctr(ppt): remove double-decoration

- requirements/deps/constraints.txt
- 0.26.0 breaks tests and reason is unknown
- 0.26.0 introduces async request but the sync version interface still exists
> chore: pin upper limit for unstructured-client

- CHANGELOG.md
- requirements/base.in
- test_unstructured/partition/common/test_common.py
- test_unstructured/partition/test_pptx.py
- unstructured/__version__.py
- unstructured/partition/common/common.py
- unstructured/partition/pptx.py
**Summary**
Eliminate historical "idiosyncracies" of `table.metadata.text_as_html` HTML introduced by `partition_pptx()`. Produce minified `.text_as_html` consistent with that formed by chunking.
- PPTX `.metadata.text_as_html` is minified (no extra whitespace or thead, tbody, tfoot elements).
- `table.text` is clean-concatenated-text (CCT) of table.
- Last use of `tabulate` library is removed and that dependency is removed from `base.in`.
> rfctr(pptx): minify HTML and table.text is cct

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/partition/pdf_image/pdfminer_processing.py
This PR rounds the floating point number associated with coordinates in `pdfminer_processing.py`. This helps to eliminate machine precision caused randomness in bounding box overlap detection. Currently the rounding is set to the nearest machine precision for `np.float32` using `np.finfo(float)`, which yields resolution = `1e-15`.
We should reduce the rounding to only 6 digits after floating point since the data type `float32` has a resolution of only `1e-6`. However it would break tests. A followup is required to tune the threshold values in `pdfminer_processing.py` so that it works with `1e-6` resolution.
> feat: round numbers to reduce undeterministic behavior

- CHANGELOG.md
- test_unstructured/metrics/test_text_extraction.py
- unstructured/__version__.py
- unstructured/metrics/text_extraction.py
This ticket  ensures that CCT metric will not be sensitive to differences in whitespace (including newline).
All whitespaces in string are changed to single space `" "` in both GT and PRED before the metric is computed.
Additional changes in CHANGELOG due to auto-formatting.
> Ml 384/whitespaces in cct

- CHANGELOG.md
- test_unstructured/documents/unstructured_json_output/example.json
- test_unstructured/partition/html/test_html_to_ontology_parsing.py
- test_unstructured/partition/html/test_html_to_unstructured_and_back_parsing.py
- unstructured/__version__.py
- unstructured/documents/ontology.py
- unstructured/partition/html/transformations.py
- the "value" attribute from <input/> tag will be taken into account and processed as "text" in ontology
- the tables will now be parsed without any ids and classes - we have different reasons behind that, for example, embeddings with ids and classes can lose some semantic value. Also, more tokens = more expensive LLM call
-  cleaned to_html, created to_text for OntologyElement
> ML-405/ML-427 - OntologyElement improvements

- CHANGELOG.md
- scripts/user/u-tables-inspect.sh
- unstructured/__version__.py
Fixes formatting in CHANGELOG.md where most of the page was bold and indented. (verify the branch version here: https://github.com/Unstructured-IO/unstructured/blob/crag/tables-tweak/CHANGELOG.md)
Bonus tweak: u-table-inspect.sh is more robust to adding borders for visualizations
> chore: fix CHANGELOG formatting

- CHANGELOG.md
- test_unstructured/metrics/test_element_type.py
- test_unstructured/partition/html/test_partition.py
- test_unstructured/partition/test_auto.py
- unstructured/__version__.py
- unstructured/partition/auto.py
- unstructured/partition/epub.py
- unstructured/partition/html/partition.py
- unstructured/partition/org.py
- unstructured/partition/rst.py
- unstructured/partition/rtf.py
**Summary**
Prepare auto-partitioning for pluggable partitioners.
Move toward a uniform partitioner call signature in `auto/partition()` such that a custom or override partitioner can be registered without requiring code changes.
The central job of `auto/partition()` is to detect the file-type of the given file and use that to dispatch partitioning to the corresponding partitioner function e.g. `partition_pdf()` or `partition_docx()`. 
In the existing code, each partitioner function is called with parameters "hand-picked" from the available parameters passed to the `partition()` function. This is unnecessary and couples those partitioners tightly with the dispatch function. The desired state is that all available arguments are passed as `kwargs` and the partitioner …
> rfctr: prep for pluggable partitioners

- .github/workflows/ci.yml
- .grype.yaml
- CHANGELOG.md
- unstructured/__version__.py
**Summary**
CVE-2024-11053 https://curl.se/docs/CVE-2024-11053.html (severity Low) was published on Dec 11, 2024 and began failing CI builds on open-core on Dec 13, 2024 when it appeared in `grype` apparently misclassified as a critical vulnerability.
The severity reported on the CVE is "Low" so it should not fail builds. Add a `.grype.yaml` file to ignore this CVE until grype is updated.
> fix: add .grype.yaml

- CHANGELOG.md
- pyproject.toml
- requirements/test.in
- requirements/test.txt
- test_unstructured/partition/pdf_image/test_pdf.py
- test_unstructured/partition/test_docx.py
- test_unstructured/partition/test_pptx.py
- test_unstructured/partition/test_xlsx.py
- unstructured/__version__.py
- unstructured/partition/html/transformations.py
**Summary**
Remove pin on `ruff` linter and fix the handful of lint errors a newer version catches.
> build: remove ruff version upper bound

- CHANGELOG.md
- test_unstructured/file_utils/test_filetype.py
- unstructured/__version__.py
- unstructured/file_utils/filetype.py
**Summary**
Fixes a bug where a CSV file with asserted content-type `application/vnd.ms-excel` was incorrectly identified as an XLS file and failed partitioning.
The `content_type` argument to partitioning is often authored by the client system (e.g. Unstructured SDK) and is both unreliable and outside the control of the user. In this case the `.csv -> XLS` mapping is correct for certain purposes (Excel is often used to load and edit CSV files) but not for partitioning, and the user has no readily available way to override the mapping.
XLS files as well as seven other common binary file types can be efficiently detected 100% of the time (at least 99.999%) using code we already have in the file detector.
- Promote this direct-inspection strategy to be tried first.
- …
> fix: refine filetype detection

- .github/workflows/ingest-test-fixtures-update-pr.yml
- CHANGELOG.md
- test_unstructured/partition/test_auto.py
- test_unstructured_ingest/expected-structured-output/azure/spring-weather.html.json
- unstructured/__version__.py
- unstructured/partition/auto.py
This PR fixes a bug when using `partition` to partition an email with image attachments with hi_res and allow table structure inference -> the partitioning of the image would encounter a value error: `got multiple values for keyword argument 'infer_table_structure'`.
This is because pass `kwargs` into partition "other" types of files in this [block](https://github.com/Unstructured-IO/unstructured/blob/50ea6fe7fc324efa09398898dc35d0cd4e78b1cf/unstructured/partition/auto.py#L270-L280) `infer_table_structure` is packaged into `partitioning_kwargs`. Then for email at least when there are attachments that can be partitioned with `hi_res` we pass that dict of `kwargs` right back into `partition` entry -> so when we get [here](https://github.com/Unstructured-IO/unstructured/blob/50ea6fe7fc324efa0 …
> fix: fix multiple values for infer_table_structure

- CHANGELOG.md
- requirements/base.in
- requirements/base.txt
- unstructured/__version__.py
- unstructured/file_utils/ndjson.py
- unstructured/partition/ndjson.py
- unstructured/staging/base.py
Avoid using the ndjson dependency due to the limiting license that exists on it
> bugfix/drop use of ndjson dep, use local code

- CHANGELOG.md
- test_unstructured/partition/pdf_image/test_pdf_image_utils.py
- test_unstructured_ingest/expected-structured-output/google-drive/fake.docx.json
- test_unstructured_ingest/expected-structured-output/google-drive/nested/fake.docx.json
- test_unstructured_ingest/expected-structured-output/google-drive/recalibrating-risk-report.pdf.json
- test_unstructured_ingest/expected-structured-output/google-drive/test-drive-doc.docx.json
- test_unstructured_ingest/expected-structured-output/jira-diff/1/10000.json
- test_unstructured_ingest/expected-structured-output/jira-diff/JCTP2/10009.json
- unstructured/__version__.py
- unstructured/partition/pdf_image/pdf_image_utils.py
This PR allows element types with CamelCase names to be extractable using `extract_image_block_types` variable.
Before: specify `extract_image_block_types=["NarrativeText"]` (or any casing for `NarrativeText`) would raise a warning that it doesn't match any available types and not image would be extracted for this element type
Now: specify `extract_image_block_types=["NarrativeText"]` would extract images for this element type
```python
f = "example-docs/pdf/embedded-images-tables.pdf"
elements = partition(f, strategy="hi_res", extract_image_block_types=["narrativetext"])
```
Without this PR no figures would be extracted. With this PR a local folder would be created to contain images of the narrative text elements in path like …
> feat: allow extraction of camel cased element type names

- CHANGELOG.md
- test_unstructured/file_utils/test_filetype.py
- test_unstructured/file_utils/test_model.py
- test_unstructured/partition/test_auto.py
- unstructured/__version__.py
- unstructured/file_utils/model.py
The purpose of this PR is to enable registering new file types dynamically.
The PR enables this through 2 primary functions:
1. `unstructured.file_utils.model.create_file_type` This registers the new `FileType` enum which enables the rest of unstructured to understand a new type of file
2. `unstructured.file_utils.model.register_partitioner` Decorator that enables registering a partitioner function to run for a file type.
> Enable dynamic file type registration

- CHANGELOG.md
- test_unstructured/partition/pdf_image/test_ocr.py
- unstructured/__version__.py
- unstructured/partition/utils/ocr_models/tesseract_ocr.py
- `lxml` is a much faster library than `bs4` when the input data is regular
- since the hOCR data is guaranteed to be regular (programmatically generated) we don't need `bs4` here to parse the data
- `lxml` improves parsing speed by about 10x
Example runtime profiling locally using the same `hocr` data from 1 page pdf, where `agent.hocr_to_dataframe_bs4` is the current method on main and `agent.hocr_to_dataframe` is the PR's method.
> feat: use lxml instead of bs4 to parse hOCR data

- CHANGELOG.md
- test_unstructured/partition/html/test_html_to_ontology_parsing.py
- unstructured/__version__.py
- unstructured/partition/html/transformations.py
Ticket: https://unstructured-ai.atlassian.net/browse/ML-942
The following uncompressed HTML document can be used to test the transformation using the `partition_html` function from the VLM partitioner.
[recalibrating-risk-report.pdf.json.html.zip](https://github.com/user-attachments/files/19330528/recalibrating-risk-report.pdf.json.html.zip)
> Image within div or span with no text is annotated as Image

- .gitignore
- CHANGELOG.md
- scripts/user/unstructured-get-json.sh
- unstructured/__version__.py
- unstructured/partition/html/convert.py
* script now supports:
* the --vlm flag, to process the document with the VLM strategy
* optionally takes --vlm-model, --vlm-provider args
* optionally also writes .html outputs by converting unstructured .json output
* optionally opens those .html outputs in a browser
Tested with:
```
unstructured-get-json.sh --write-html --open-html --fast                                                                layout-parser-paper-p2.pdf
unstructured-get-json.sh --write-html --open-html --hi-res                                                              layout-parser-paper-p2.pdf
unstructured-get-json.sh --write-html --open-html --ocr-only                                                            layout-parser-paper-p2.pdf
unstructured-get-json.sh --write-html --open-html --vlm …
```
> feat: convenience unstructured-get-json.sh update

- .github/workflows/ingest-test-fixtures-update-pr.yml
This should allow the `Ingest Test Fixtures Update PR` workflow to also update expected html outputs.
E.g., before the change, the .html files would be left unmodified:
https://github.com/Unstructured-IO/unstructured/actions/runs/14234877547/job/39892334672
> chore: add html path to ingest-test-fixtures-update-pr

- CHANGELOG.md
- test_unstructured/partition/pdf_image/test_pdf_image_utils.py
- unstructured/__version__.py
- unstructured/partition/pdf_image/pdf_image_utils.py
When I tried to partition a PNG file and extract images, I got an error from Pillow:
```
WARNING  unstructured:pdf_image_utils.py:230 Image Extraction Error: Skipping the failed image
Traceback (most recent call last):
File "/Users/austin/.pyenv/versions/unstructured/lib/python3.10/site-packages/PIL/JpegImagePlugin.py", line 666, in _save
rawmode = RAWMODE[im.mode]
KeyError: 'RGBA'
```
The issue is that a PNG has an additional layer that cannot be saved off in jpeg format. We can fix this with a quick conversion. I added a png test case that is now passing with this fix.
> fix: Fix for Pillow error when extracting PNG images

- CHANGELOG.md
- test_unstructured/partition/test_json.py
- test_unstructured/partition/test_ndjson.py
- unstructured/partition/json.py
- unstructured/partition/ndjson.py
Adds validation if `json` / `ndjson` are not valid unstructured schema.
Manually tested serverless API with example json:
```
test_length = [] = 200
test_invalid = [{"invalid": "schema"}] = 422
test_invalid_ndjson ={"hi": "there"} = 422
test_chunk = [{"type":"Header","element_id":"a23fdadef9277f217563e217ebd074d5" ... = 200
```
> fix: throw validation error when json is passed with invalid unstructured json

- CHANGELOG.md
- unstructured/partition/api.py
This PR resolves the deprecation warnings of the `logger` library:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
> fix: resolve warnings of logger library

- .gitignore
- scripts/image/test-all-outbound-connectivity-scenarios.sh
- scripts/image/test-outbound-connectivity.sh
Sample output. The key thing here is the modes `offline` (meaning set HF_HUB_ONLINE=1 AND DO_NOT_TRACK=true) results in no outbound connections. This also is true if the locally cached models are removed, the last scenario of `offline-and-missing-models`)
```
$ ./test-all-outbound-connectivity-scenarios.sh 
>>> Removing leftover sut_* containers…
Container: 543ac4b14370a18d790a2035e206e8c445754b825ec8b2887f4246f7404299c7  (scenario baseline)
tcpdump running on interface eth0...
>>> Running Python workload (capturing stdout/stderr)…
[INFO] partitioning /app/example-docs/ideas-page.html
<snip>
Python finished.  Log saved to /r/unstructured/scripts/image/python-output/offline-and-missing-models.log
pcap saved to /r/unstructured/scripts/image/pcaps/offline-and-missing-models.pcap …
```
> chore: script to verify unstructured image outbound connectivity

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/metrics/table/table_extraction.py
This small PR fixes the bs4 deprecation warnings which you can find in the [CI logs](https://github.com/Unstructured-IO/unstructured/actions/runs/15491657572/job/43729960936#step:3:2615):
```python
/app/unstructured/metrics/table/table_extraction.py:53: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
/app/unstructured/metrics/table/table_extraction.py:57: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
```
> Migrate to modern bs4 interface

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/documents/elements.py
- unstructured/partition/html/convert.py
In scenarios where there is a large amount of data that represents the document rather than individual elements in the document, it may be preferable to specify this in a single location rather than duplicating the data across all elements (as we do for smaller metadata like filename or filetype)
This PR adds DocumentData element type which can be used to uniquely capture this data.
> feat: add DocumentData type

- CHANGELOG.md
- test_unstructured/documents/unstructured_json_output/example.json
- test_unstructured/documents/unstructured_json_output/example_full_doc.json
- test_unstructured/documents/unstructured_json_output/example_with_alternative_text.json
- test_unstructured/documents/unstructured_json_output/example_with_inline_fields.json
- test_unstructured/partition/html/test_html_to_ontology_parsing.py
- test_unstructured/partition/html/test_html_to_unstructured_and_back_parsing.py
- unstructured/__version__.py
- unstructured/documents/ontology.py
This PR fixes an issue where header/footer content in html are not partitioned as `unstructured` `Header` or `Footer` element types. Rather they are either `UncategorizedText` or taking on the type of the nested structure inside the header/footer. E.g., `<header class="Header"><h1 class="Title">Header Title</h1></header>` would be partitioned as a `Title` instead of `Header`.
This behavior is because we treat header and footer as layout, i.e., containers, in the ontology definition. As a result, during parsing we [unwrap](https://github.com/Unstructured-IO/unstructured/blob/ec209c6b5f9f24b4aabfa3bc8145ab896e7afd66/unstructured/partition/html/transformations.py#L361-L378) the container and parse the contents as if they are from the main text even though they are still part of …
> fix: fix header and footer not parsed as Header/Footer types

- CHANGELOG.md
- pyproject.toml
- requirements/base.txt
- requirements/deps/constraints.txt
- requirements/extra-csv.txt
- requirements/extra-docx.txt
- requirements/extra-markdown.txt
- requirements/extra-odt.txt
- requirements/extra-paddleocr.txt
- requirements/extra-pdf-image.txt
- requirements/extra-pptx.txt
- requirements/extra-xlsx.txt
- requirements/huggingface.txt
- requirements/test.txt
- scripts/pip-compile.sh
- setup.py
- test_unstructured/partition/common/test_common.py
- test_unstructured/partition/pdf_image/test_image.py
- test_unstructured/partition/pdf_image/test_pdf.py
- test_unstructured/partition/pdf_image/test_pdf_image_utils.py
- unstructured/__version__.py
Dropped variables that said we support Python 3.9 in `setup.py`, as well as any remaining references to Python 3.9.
I also checked the pins and removed several that don't seem necessary any more.
> build: drop remaining Python 3.9 refs

- CHANGELOG.md
- unstructured/__version__.py
- unstructured/partition/utils/config.py
- unstructured/partition/utils/ocr_models/ocr_interface.py
OCR agents used unlimited caching, causing excessive memory usage. Each cached OCR agent consumes different amounts of memory, but can easily consume ~800MB.
Add `OCR_AGENT_CACHE_SIZE` environment variable to limit cached OCR agents per process.
- **Default**: 1 cached agent
- **Configurable**: Set to 0 to disable caching, or higher for more languages
> Add OCR_AGENT_CACHE_SIZE environment variable

- CHANGELOG.md
- test_unstructured/file_utils/test_encoding.py
- unstructured/__version__.py
- unstructured/file_utils/encoding.py
Replace UnicodeDecodeError with UnprocessableEntityError in encoding detection to avoid logging entire file contents. UnicodeDecodeError.object automatically stores complete input data, causing memory issues with large files in logging and error reporting systems.
> fix: replace UnicodeDecodeError to prevent large payload logging
