unstructured/__version__.py

Bumpy `__version__.py` to match `CHANGELOG`.

chore: Bump __version__.py version to match CHANGELOG

---

setup.py

This PR add long description to the package.
The description is taked from README.md

docs: Added long description to PyPi

---

CHANGELOG.md
README.md

Addresses https://github.com/Unstructured-IO/unstructured/issues/56 and add Colab notebook with examples from README.
You can add a comment for a block to suggest changes for the Colab notebook.

docs: add Colab notebook line in README

---

CHANGELOG.md
docs/source/bricks.rst
requirements/base.txt
requirements/huggingface.txt
setup.py
test_unstructured/staging/test_argilla.py
unstructured/__version__.py
unstructured/staging/argilla.py

Resolves https://github.com/Unstructured-IO/community/issues/26

feat: Implement Argilla staging brick

---

requirements/dev.in
requirements/dev.txt
setup.py

Bumps the `jupyter-core` library to address vulnerabilities from the security scans.

build(deps): Bump jupyter-core library

---

CHANGELOG.md
unstructured/__version__.py

Bump to version 0.3.0 to prep for release

release: bump to version 0.3.0

---

docs/requirements.txt
requirements/base.txt
requirements/build.in
requirements/build.txt
requirements/dev.txt
requirements/huggingface.txt
requirements/local-inference.txt
requirements/test.txt

Attempt to knock out all dependabot stuff at once.

chore: update all deps

---

Makefile
docs/requirements.txt
requirements/base.txt
requirements/build.txt
requirements/dev.txt
requirements/huggingface.txt
requirements/test.txt

build(deps): weekly dependency bump

---

.github/dependabot.yml
CHANGELOG.md
docs/requirements.txt
requirements/base.txt
requirements/build.txt
requirements/dev.txt
requirements/huggingface.txt
requirements/local-inference.txt
requirements/test.in
requirements/test.txt
test_unstructured/staging/test_base_staging.py
test_unstructured/staging/test_huggingface.py
unstructured/__version__.py
unstructured/partition/email.py
unstructured/partition/text.py

Bumps dependencies and decreases the frequency of dependabot updates.

build(deps): weekly dependency update; reduce dependabot frequency

---

CHANGELOG.md
Ingest.md
unstructured/__version__.py

Cut a release that has the unstructured-ingest command line included in the unstructured package.
Bonus tweak to the Ingest checklist.

build: new release

---

CHANGELOG.md
Makefile
scripts/setup_ubuntu.sh
scripts/version-sync.sh
unstructured/__version__.py

Added Ubuntu setup script.
In a fresh environment, run the script with
```shell
./setup_ubuntu.sh <account name>
```
...where `<account name>` is the name of the user account you are setting up for.
After installation and restarting the shell, you should have the `pyenv` command available. `pyenv versions` should show that version 3.8.15 is installed.
Check that poppler is installed with `pdftoppm -h`.
Check that tesseract is installed with `tesseract`.

feat: add ubuntu setup script

---

CHANGELOG.md
requirements/base.txt
requirements/build.txt
requirements/dev.txt
requirements/huggingface.txt
requirements/ingest-github.txt
requirements/ingest-reddit.txt
requirements/ingest-s3.txt
requirements/local-inference.txt
test_unstructured_ingest/test-ingest-github.sh
unstructured/__version__.py

Also skip the github ingest test 90% of the time in CI for now until creds are added.

build(deps): make pip-compile

---

examples/sec-sentiment-analysis/sec-sentiment-analysis.ipynb

docs: update sec-sentiment-analysis.ipynb

---

Dockerfile
Makefile
README.md
scripts/docker-build.sh

https://unstructured-ai.atlassian.net/browse/CORE-742
Steps to run:
```
(unstructured) ➜  unstructured git:(amanda/add-Dockerfile) make docker-build
(unstructured) ➜  unstructured git:(amanda/add-Dockerfile) make docker-start-bash
docker run --platform linux/amd64 -ti --rm unstructured-dev:latest
[notebook-user@6cf610cd9177 ~]$ python3
Python 3.8.15 (default, Mar 10 2023, 21:05:24)
[GCC 7.3.1 20180303 (Red Hat 7.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from unstructured.partition.text import partition_text
[nltk_data] Downloading package punkt to /home/notebook-
[nltk_data]     user/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data] …
```

chore: adding Dockerfile and make commands for building/running

---

README.md

Closes [CORE-749](https://unstructured-ai.atlassian.net/browse/CORE-749)
[CORE-749]: https://unstructured-ai.atlassian.net/browse/CORE-749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: update readme with notes about pulling and running the public Docker image.

---

unstructured/nlp/patterns.py

Simplifies the regex expression a touch and allows the pattern to expand to additional whitespace/newlines.

feat: update paragraph pattern regex

---

CHANGELOG.md
docs/requirements.txt
docs/source/bricks.rst
examples/sec-sentiment-analysis/fetch.py
requirements/base.txt
requirements/build.txt
requirements/dev.txt
requirements/huggingface.txt
requirements/ingest-azure.txt
requirements/ingest-github.txt
requirements/ingest-gitlab.txt
requirements/ingest-google-drive.txt
requirements/ingest-reddit.txt
requirements/ingest-s3.txt
requirements/ingest-wikipedia.txt
requirements/local-inference.txt
requirements/test.in
requirements/test.txt
test_unstructured/partition/test_html_partition.py
unstructured/__version__.py
unstructured/partition/html.py

Also adds pytest-mock requirement, those fixtures are nice to have!
Implements issue/feature https://github.com/Unstructured-IO/unstructured/issues/396 .

feat: add ability to pass headers in partition_html

---

.github/workflows/create_issue.yml

Added a link back to the original Github issue from which the Jira issue was created for tracking purposes.

chore: add github link to autogenerated issue

---

docs/source/installing.rst

XML/HTML Depenedencies -> XML/HTML Dependencies

fix: typo in installing docs

---

docs/source/bricks.rst

This PR should fix this format problem:

fix: formatting error

---

scripts/ingest-test-fixtures-update.sh

Adds the Slack ingest test script to the fixture update script.
Used to update the fixtures for #485

fix: add slack to fixture update script

---

docs/source/installing.rst

Seems like there was a small typo on the main installation command.

docs: Updated the installation command

---

README.md

Updates the `README` to reflect the new installation pattern for `detectron2`.

docs: update detectron2 instructions in readme

---

CHANGELOG.md
test_unstructured/partition/test_auto.py
test_unstructured_ingest/expected-structured-output/azure-blob-storage/IRS-form-1987.png.json
unstructured/__version__.py
unstructured/partition/auto.py
unstructured/partition/image.py
unstructured/partition/pdf.py

Fix the problem that `strategy`  is not passed down from `partition` to`partition_image`. Add some doc string nit.
```
filename = "example-docs/english-and-korean.png"
elements = partition(filename=filename, ocr_languages="eng+kor", strategy="ocr_only")
print(elements[3].text)
```

Fix: Pass `strategy` parameter down from `partition` for `partition_image`

---

docs/source/bricks.rst

Issue 652: sorting functions in bricks.rst in alphabetical order
Difference between additions and deletions is due to removing empty lines for consistency
Newly documented partition_rst included

docs: sort functions in bricks.rst in alphabetical order v2

---

test_unstructured_ingest/expected-structured-output/google-drive-output/117qrVqiCoR5EjYMsDHGdy3UMkEtKr9Q8-test-drive-doc.docx.json
test_unstructured_ingest/expected-structured-output/google-drive-output/1SpQuE7jHz9nMt5hfQXsiok1SgIdRYX5o-fake.docx.json
test_unstructured_ingest/expected-structured-output/google-drive-output/1cTKXAreuj-wYmL38nFnqKvz3X8UKcaMC-foo.txt.json

test: add google drive ingest test <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/azure-blob-storage/Core-Skills-for-Biomedical-Data-Scientists-2-pages.pdf.json
test_unstructured_ingest/expected-structured-output/azure-blob-storage/IRS-form-1987.pdf.json
test_unstructured_ingest/expected-structured-output/azure-blob-storage/IRS-form-1987.png.json
test_unstructured_ingest/expected-structured-output/azure-blob-storage/rfc854.txt.json
test_unstructured_ingest/expected-structured-output/azure-blob-storage/spring-weather.html.json
test_unstructured_ingest/expected-structured-output/biomed-ingest-output-api/65/11/main.PMC6312790.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-ingest-output-api/75/29/main.PMC6312793.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-ingest-output-path/07/07/sbaa031.073.PMC7234218.pdf.json
test_unstructured_ingest/expected-structured-output/discord-ingest-channel/1099442333440802930.json
test_unstructured_ingest/expected-structured-output/discord-ingest-channel/1099601456321003600.json
test_unstructured_ingest/expected-structured-output/github-downloadify/LICENSE.txt.json
test_unstructured_ingest/expected-structured-output/github-downloadify/test.html.json
test_unstructured_ingest/expected-structured-output/google-drive-output/117qrVqiCoR5EjYMsDHGdy3UMkEtKr9Q8-test-drive-doc.docx.json
test_unstructured_ingest/expected-structured-output/google-drive-output/1SpQuE7jHz9nMt5hfQXsiok1SgIdRYX5o-fake.docx.json
test_unstructured_ingest/expected-structured-output/google-drive-output/1cTKXAreuj-wYmL38nFnqKvz3X8UKcaMC-foo.txt.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/azure/Core-Skills-for-Biomedical-Data-Scientists-2-pages.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/biomed-api/65/11/main.PMC6312790.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/biomed-api/75/29/main.PMC6312793.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/biomed-path/07/07/sbaa031.073.PMC7234218.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/s3/small-pdf-set/2023-Jan-economic-outlook.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/s3/small-pdf-set/Silent-Giant-(1).pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/s3/small-pdf-set/recalibrating-risk-report.pdf.json
test_unstructured_ingest/expected-structured-output/s3-small-batch/small-pdf-set/2023-Jan-economic-outlook.pdf.json
test_unstructured_ingest/expected-structured-output/s3-small-batch/small-pdf-set/Silent-Giant-(1).pdf.json
test_unstructured_ingest/expected-structured-output/s3-small-batch/small-pdf-set/recalibrating-risk-report.pdf.json
test_unstructured_ingest/expected-structured-output/slack-ingest-channel/C052BGT7718.json

feat: coordinate systems <- Ingest test fixtures update

---

scripts/docker-build.sh
scripts/docker-smoke-test.sh
scripts/install-pandoc.sh
scripts/performance/benchmark-local.sh
scripts/performance/benchmark.sh
scripts/performance/get-stats-name.sh
scripts/performance/profile.sh
scripts/setup_al2.sh
scripts/setup_ubuntu.sh
scripts/shellcheck.sh
scripts/version-sync.sh

Update all bash scripts with #!/bin/bash to use /usr/bin/env bash.

chore: update all bash scripts to use shebang: /usr/bin/env bash

---

test_unstructured_ingest/expected-structured-output/google-cloud-storage/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/google-cloud-storage/nested-1/fake-text.txt.json
test_unstructured_ingest/expected-structured-output/google-cloud-storage/nested-1/nested/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/google-cloud-storage/nested-2/fake-text.txt.json
test_unstructured_ingest/expected-structured-output/google-cloud-storage/nested-2/nested/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/google-cloud-storage/nested-2/stanley-cups.xlsx.json

Potter/google cloud storage <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/s3-small-batch/small-pdf-set/2023-Jan-economic-outlook.pdf.json
test_unstructured_ingest/expected-structured-output/s3-small-batch/small-pdf-set/recalibrating-risk-report.pdf.json

enhancement: clean pdf elements <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/azure-blob-storage/rfc854.txt.json
test_unstructured_ingest/expected-structured-output/parameterized-ingest-output/example-docs/english-and-korean.png.json

enhancement: `max_partition` kwarg for limiting element size <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/parameterized-ingest-output/example-docs/english-and-korean.png.json

fix: ignore escaped commas in CSV checks <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/parameterized-ingest-output/example-docs/english-and-korean.png.json

DRAFT fix: parameterized ingest test overwriting <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/discord/1099442333440802930.json
test_unstructured_ingest/expected-structured-output/discord/1099601456321003600.json
test_unstructured_ingest/expected-structured-output/slack/C052BGT7718.json

chore: refactor ingest tests <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/biomed-ingest-output-api/65/11/main.PMC6312790.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-ingest-output-api/75/29/main.PMC6312793.pdf.json
test_unstructured_ingest/expected-structured-output/s3-small-batch/small-pdf-set/2023-Jan-economic-outlook.pdf.json
test_unstructured_ingest/expected-structured-output/s3-small-batch/small-pdf-set/recalibrating-risk-report.pdf.json

Ingest test fest bump inference <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/elasticsearch/movies/0-31261b6f.json
test_unstructured_ingest/expected-structured-output/elasticsearch/movies/1-31261b6f.json
test_unstructured_ingest/expected-structured-output/elasticsearch/movies/2-31261b6f.json
test_unstructured_ingest/expected-structured-output/elasticsearch/movies/3-31261b6f.json
test_unstructured_ingest/expected-structured-output/elasticsearch/movies/4-31261b6f.json
test_unstructured_ingest/expected-structured-output/elasticsearch/movies/5-31261b6f.json
test_unstructured_ingest/expected-structured-output/elasticsearch/movies/6-31261b6f.json
test_unstructured_ingest/expected-structured-output/elasticsearch/movies/7-31261b6f.json
test_unstructured_ingest/expected-structured-output/elasticsearch/movies/8-31261b6f.json
test_unstructured_ingest/expected-structured-output/elasticsearch/movies/9-31261b6f.json

feat: elasticsearch connector <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/onedrive/01PNIS7JCNIOIR45BLBJELOZBFUEL6JA7X-fake-text.json
test_unstructured_ingest/expected-structured-output/onedrive/01PNIS7JFPYSDZSASXNZDIDEQU2GKVOTKZ-stanley-cups.json
test_unstructured_ingest/expected-structured-output/onedrive/01PNIS7JHT77TO3JE2GBBLVBH2A7AXG7HT-ideas-page.json

feat: Adds OneDrive connector <- Ingest test fixtures update

---

CHANGELOG.md
Dockerfile
unstructured/__version__.py

New base image with security patches

---

test_unstructured_ingest/expected-structured-output/local-single-file/english-and-korean.png.json

fix: local connector output filename when a single file is being processed <- Ingest test fixtures update

---

unstructured/file_utils/encoding.py
unstructured/file_utils/file_conversion.py
unstructured/file_utils/filetype.py
unstructured/file_utils/metadata.py
unstructured/partition/api.py
unstructured/partition/auto.py
unstructured/partition/common.py
unstructured/partition/csv.py
unstructured/partition/doc.py
unstructured/partition/docx.py
unstructured/partition/email.py
unstructured/partition/epub.py
unstructured/partition/html.py
unstructured/partition/json.py
unstructured/partition/md.py
unstructured/partition/msg.py
unstructured/partition/odt.py
unstructured/partition/org.py
unstructured/partition/ppt.py
unstructured/partition/pptx.py
unstructured/partition/rst.py
unstructured/partition/rtf.py
unstructured/partition/text.py
unstructured/partition/tsv.py
unstructured/partition/xlsx.py
unstructured/partition/xml.py

Changed type `IO` to `IO[bytes]`
fix for [887](https://github.com/Unstructured-IO/unstructured/issues/877)

changed type IO to IO[bytes]

---

test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/azure/IRS-form-1987.pdf.json

fix: better extractable check <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/confluence/MFS/1212417.json
test_unstructured_ingest/expected-structured-output/confluence/MFS/229477.json
test_unstructured_ingest/expected-structured-output/confluence/MFS/229532.json
test_unstructured_ingest/expected-structured-output/confluence/MFS/229546.json
test_unstructured_ingest/expected-structured-output/confluence/MFS/229560.json
test_unstructured_ingest/expected-structured-output/confluence/MFS/229574.json
test_unstructured_ingest/expected-structured-output/confluence/testteamsp/1540126.json
test_unstructured_ingest/expected-structured-output/confluence/testteamsp/1605859.json
test_unstructured_ingest/expected-structured-output/confluence/testteamsp/1605928.json
test_unstructured_ingest/expected-structured-output/confluence/testteamsp/1605942.json
test_unstructured_ingest/expected-structured-output/confluence/testteamsp/1605956.json
test_unstructured_ingest/expected-structured-output/confluence/testteamsp/1605989.json
test_unstructured_ingest/expected-structured-output/confluence/~64083457896d10ebd4738661/65628.json
test_unstructured_ingest/expected-structured-output/confluence/~7120205368eedfcecd43e18b25b2221316ee6f/1212628.json
test_unstructured_ingest/expected-structured-output/confluence/~7120205368eedfcecd43e18b25b2221316ee6f/1277964.json

feat: confluence connector <- Ingest test fixtures update

---

CHANGELOG.md
unstructured/__version__.py

In order for some recent bug fixes to be available to the api, cutting a new release.

Set the version to 0.8.1

---

docs/source/connectors.rst
docs/source/index.rst

Solves issue #653 by adding a connectors section to https://unstructured-io.github.io/unstructured/

docs: Adds connectors' documentation

---

test_unstructured_ingest/expected-structured-output/azure/spring-weather.html.json
test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/1605956.json
test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/229477.json
test_unstructured_ingest/expected-structured-output/confluence-diff/testteamsp/1605859.json
test_unstructured_ingest/expected-structured-output/confluence-diff/testteamsp/1605989.json
test_unstructured_ingest/expected-structured-output/confluence-diff/testteamsp/1802252.json
test_unstructured_ingest/expected-structured-output/confluence-diff/~64083457896d10ebd4738661/65627.json
test_unstructured_ingest/expected-structured-output/confluence-diff/~64083457896d10ebd4738661/65628.json
test_unstructured_ingest/expected-structured-output/confluence-diff/~7120205368eedfcecd43e18b25b2221316ee6f/2130016.json
test_unstructured_ingest/expected-structured-output/gcs/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/gcs/nested-1/nested/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/gcs/nested-2/nested/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/github/test.html.json

feat: track links from anchor tags in `partition_html` <- Ingest test fixtures update

---

CHANGELOG.md
test_unstructured/file_utils/test_filetype.py
test_unstructured/partition/test_auto.py
test_unstructured/partition/test_json.py
unstructured/__version__.py
unstructured/file_utils/filetype.py
unstructured/partition/auto.py
unstructured/partition/json.py

Simplifies JSON detection, adds a function to detect if a JSON is processable, and adds new tests.

refactor: simplifies JSON detection and add tests

---

test_unstructured_ingest/expected-structured-output/outlook/21be155fb0c95885.eml.json
test_unstructured_ingest/expected-structured-output/outlook/497eba8c81c801c6.eml.json
test_unstructured_ingest/expected-structured-output/outlook/4a16a411f162ebbb.eml.json

chore: rename Element's "date" field to "last_modified" <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/azure/spring-weather.html.json
test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/1540126.json
test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/1605928.json
test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/1605942.json
test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/1605956.json
test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/229477.json
test_unstructured_ingest/expected-structured-output/confluence-diff/testteamsp/1605859.json
test_unstructured_ingest/expected-structured-output/confluence-diff/testteamsp/1605989.json
test_unstructured_ingest/expected-structured-output/confluence-diff/testteamsp/1802252.json
test_unstructured_ingest/expected-structured-output/confluence-diff/~64083457896d10ebd4738661/65627.json
test_unstructured_ingest/expected-structured-output/confluence-diff/~64083457896d10ebd4738661/65628.json
test_unstructured_ingest/expected-structured-output/confluence-diff/~7120205368eedfcecd43e18b25b2221316ee6f/2130016.json
test_unstructured_ingest/expected-structured-output/gcs/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/gcs/nested-1/nested/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/gcs/nested-2/nested/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/outlook/497eba8c81c801c6.eml.json

Feat/965 track emphasized text html <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/dropbox/handbook-1p.docx.json
test_unstructured_ingest/expected-structured-output/dropbox/nested-1/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/dropbox/nested-2/ideas-page.html.json

chore: add Dropbox secrets to CI environments <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/box/nested-1/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/box/nested-2/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/dropbox/nested-1/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/dropbox/nested-2/ideas-page.html.json

feat: track emphasized text in `partition_html` <- Ingest test fixtures update

---

CHANGELOG.md
test_unstructured/documents/test_html.py
test_unstructured/partition/test_html_partition.py
test_unstructured_ingest/expected-structured-output/azure/spring-weather.html.json
test_unstructured_ingest/expected-structured-output/box/nested-1/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/box/nested-2/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/1540126.json
test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/1605928.json
test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/1605942.json
test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/1605956.json
test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/229477.json
test_unstructured_ingest/expected-structured-output/confluence-diff/testteamsp/1605859.json
test_unstructured_ingest/expected-structured-output/confluence-diff/testteamsp/1605989.json
test_unstructured_ingest/expected-structured-output/confluence-diff/testteamsp/1802252.json
test_unstructured_ingest/expected-structured-output/confluence-diff/~64083457896d10ebd4738661/65627.json
test_unstructured_ingest/expected-structured-output/confluence-diff/~64083457896d10ebd4738661/65628.json
test_unstructured_ingest/expected-structured-output/confluence-diff/~7120205368eedfcecd43e18b25b2221316ee6f/2130016.json
test_unstructured_ingest/expected-structured-output/dropbox/nested-1/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/dropbox/nested-2/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/gcs/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/gcs/nested-1/nested/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/gcs/nested-2/nested/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/outlook/497eba8c81c801c6.eml.json
unstructured/documents/elements.py
unstructured/documents/html.py
unstructured/documents/xml.py
unstructured/partition/common.py
unstructured/staging/weaviate.py

feat: track emphasized text in `partition_html`

---

test_unstructured_ingest/expected-structured-output/azure/spring-weather.html.json

fix: remove default encoding for ingest <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/elasticsearch/movies/0-31261b6f.json
test_unstructured_ingest/expected-structured-output/elasticsearch/movies/1-31261b6f.json
test_unstructured_ingest/expected-structured-output/elasticsearch/movies/2-31261b6f.json
test_unstructured_ingest/expected-structured-output/elasticsearch/movies/3-31261b6f.json
test_unstructured_ingest/expected-structured-output/elasticsearch/movies/4-31261b6f.json
test_unstructured_ingest/expected-structured-output/elasticsearch/movies/5-31261b6f.json
test_unstructured_ingest/expected-structured-output/elasticsearch/movies/6-31261b6f.json
test_unstructured_ingest/expected-structured-output/elasticsearch/movies/7-31261b6f.json
test_unstructured_ingest/expected-structured-output/elasticsearch/movies/8-31261b6f.json
test_unstructured_ingest/expected-structured-output/elasticsearch/movies/9-31261b6f.json

Klaijan/auto paragraph grouper <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper.pdf.json

null <- Ingest test fixtures update

---

examples/chroma-news-of-the-day/README.md
examples/chroma-news-of-the-day/news-of-the-day.ipynb
examples/chroma-news-of-the-day/requirements.txt

Adds an example notebook book showing how to use Unstructured + Chroma + LangChain to summarize the news of the day.

docs: news of the day (chroma + langchain)

---

test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper.pdf.json

Chore[ingest]: adding parameter --partition-pdf-infer-table-structure <- Ingest test fixtures update

---

CHANGELOG.md
test_unstructured/documents/test_elements.py
test_unstructured/documents/test_email_elements.py
unstructured/__version__.py
unstructured/documents/elements.py
unstructured/documents/email_elements.py
unstructured/staging/label_box.py

Addresses #1071
I followed how NoID() is used as a value for element_id by analogy.

added UUID option for element_id arg in element constructor

---

test_unstructured_ingest/expected-structured-output/notion/122b2c22-996b-435b-9de2-ee0e9d2b04bc.json
test_unstructured_ingest/expected-structured-output/notion/438dbc49-2e06-4f01-8031-bf283be58a60.json
test_unstructured_ingest/expected-structured-output/notion/4695ea53-f2b3-45b4-8638-2212fd054d73.json
test_unstructured_ingest/expected-structured-output/notion/5481f29c-799a-4d7b-93ce-b11bcaede531.json
test_unstructured_ingest/expected-structured-output/notion/60377009-e6b2-47f3-a8ff-f159fd8b69f5.json
test_unstructured_ingest/expected-structured-output/notion/898538f2-26e1-4de7-81e6-354045d4d007.json
test_unstructured_ingest/expected-structured-output/notion/8db7ccc9-0a9c-4168-94c3-f997e60cb8cf.json
test_unstructured_ingest/expected-structured-output/notion/9e20be3d-cbe0-4e28-ad46-2170d40a8d37.json
test_unstructured_ingest/expected-structured-output/notion/b2a12157-721e-4207-b3b7-527762b782c2.json
test_unstructured_ingest/expected-structured-output/notion/c47a4566-4c7a-488b-ac2a-1292ee507fcb.json
test_unstructured_ingest/expected-structured-output/notion/d3d87fc6-61cc-4bb5-89ed-e9dff0df1526.json
test_unstructured_ingest/expected-structured-output/notion/dfcbe584-30b1-4551-b533-e6a5759af842.json
test_unstructured_ingest/expected-structured-output/notion/feccfcd4-8ca0-4638-8212-1a5726461029.json
test_unstructured_ingest/expected-structured-output/notion/fee2149e-6240-4431-8e98-a04a2e460a66.json

Roman/notion tests <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/Sharepoint/Shared Documents/ideas-page.json
test_unstructured_ingest/expected-structured-output/azure/spring-weather.html.json
test_unstructured_ingest/expected-structured-output/box/handbook-1p.docx.json
test_unstructured_ingest/expected-structured-output/box/nested-1/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/box/nested-2/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/dropbox/handbook-1p.docx.json
test_unstructured_ingest/expected-structured-output/dropbox/nested-1/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/dropbox/nested-2/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/gcs/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/gcs/nested-1/nested/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/gcs/nested-2/nested/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/github/test.html.json
test_unstructured_ingest/expected-structured-output/google-drive/117qrVqiCoR5EjYMsDHGdy3UMkEtKr9Q8-test-drive-doc.docx.json
test_unstructured_ingest/expected-structured-output/outlook/497eba8c81c801c6.eml.json

Feat/1060 update metadata fields <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/azure/IRS-form-1987.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-api/65/11/main.PMC6312790.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-api/75/29/main.PMC6312793.pdf.json
test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper.pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/2023-Jan-economic-outlook.pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/Silent-Giant-(1).pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/recalibrating-risk-report.pdf.json

build(deps): bump unstructured-inference==0.5.13 <- Ingest test fixtures update

---

CHANGELOG.md
requirements/constraints.in
requirements/extra-pdf-image.txt
requirements/ingest-confluence.txt
test_unstructured_ingest/expected-structured-output/azure/IRS-form-1987.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-api/65/11/main.PMC6312790.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-api/75/29/main.PMC6312793.pdf.json
test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper.pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/2023-Jan-economic-outlook.pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/Silent-Giant-(1).pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/recalibrating-risk-report.pdf.json
unstructured/__version__.py

* Bump unstructured-inference==0.5.13:
- Fix extracted image elements being included in layout merge, addresses the issue
where an entire-page image in a PDF was not passed to the layout model when using hi_res.

build(deps): bump unstructured-inference==0.5.13

---

test_unstructured_ingest/expected-structured-output/azure/IRS-form-1987.png.json

Klaijan/partition image tiff (branch from 6d6be99) <- Ingest test fixtures update

---

CHANGELOG.md
requirements/constraints.in
requirements/extra-pdf-image.txt

Pulls in @newelh's fix:
https://github.com/Unstructured-IO/unstructured-inference/pull/184

build(deps): bump unstructured-inference==0.5.16

---

test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/s3/small-pdf-set/recalibrating-risk-report.pdf.json

Feat/1136 elements ordering for pdf <- Ingest test fixtures update

---

CHANGELOG.md
requirements/build.in
requirements/constraints.in
requirements/extra-pdf-image.txt
requirements/test.txt
unstructured/__version__.py

Pulls in @awalker4's tesseract enhancement: https://github.com/Unstructured-IO/unstructured-inference/pull/185

build: bump unstructured-inference==0.5.17, cut release

---

test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/1540126.json
test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/1605928.json
test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/1605942.json
test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/1605956.json
test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/229477.json
test_unstructured_ingest/expected-structured-output/confluence-diff/testteamsp/1605859.json
test_unstructured_ingest/expected-structured-output/confluence-diff/testteamsp/1605989.json
test_unstructured_ingest/expected-structured-output/confluence-diff/testteamsp/1802252.json

uncomment confluence diff ingest test <- Ingest test fixtures update

---

CHANGELOG.md
test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/1540126.json
test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/1605928.json
test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/1605942.json
test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/1605956.json
test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/229477.json
test_unstructured_ingest/expected-structured-output/confluence-diff/testteamsp/1605859.json
test_unstructured_ingest/expected-structured-output/confluence-diff/testteamsp/1605989.json
test_unstructured_ingest/expected-structured-output/confluence-diff/testteamsp/1802252.json
test_unstructured_ingest/test-ingest.sh
unstructured/__version__.py

Uncomment confluence-diff ingest test to:
- see if the test has consistent results
- keep testing the confluence connector

uncomment confluence diff ingest test

---

test_unstructured_ingest/expected-structured-output/Sharepoint/Shared Documents/fake-text.json
test_unstructured_ingest/expected-structured-output/Sharepoint/Shared Documents/ideas-page.json
test_unstructured_ingest/expected-structured-output/Sharepoint/Shared Documents/stanley-cups.json
test_unstructured_ingest/expected-structured-output/Sharepoint/SitePages/Home.json
test_unstructured_ingest/expected-structured-output/Sharepoint/SitePages/This-is-a-title.json

feat: serialize ingest docs as json <- Ingest test fixtures update

---

CHANGELOG.md
unstructured/__version__.py

attempting to break the cycle of multiple 'release' commits.

chore: switch to non-release dev version

---

test_unstructured_ingest/expected-structured-output/azure/Core-Skills-for-Biomedical-Data-Scientists-2-pages.pdf.json
test_unstructured_ingest/expected-structured-output/azure/IRS-form-1987.pdf.json
test_unstructured_ingest/expected-structured-output/azure/IRS-form-1987.png.json
test_unstructured_ingest/expected-structured-output/biomed-api/65/11/main.PMC6312790.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-api/75/29/main.PMC6312793.pdf.json
test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper.pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/2023-Jan-economic-outlook.pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/Silent-Giant-(1).pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/recalibrating-risk-report.pdf.json

enhancement: entire page OCR output included with hi_res <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/jira-diff/1/10000.json
test_unstructured_ingest/expected-structured-output/jira-diff/1/10001.json
test_unstructured_ingest/expected-structured-output/jira-diff/1/10002.json
test_unstructured_ingest/expected-structured-output/jira-diff/1/10013.json
test_unstructured_ingest/expected-structured-output/jira-diff/JCTP2/10006.json
test_unstructured_ingest/expected-structured-output/jira-diff/JCTP2/10009.json
test_unstructured_ingest/expected-structured-output/jira-diff/JCTP2/10010.json
test_unstructured_ingest/expected-structured-output/jira-diff/JCTP2/10012.json
test_unstructured_ingest/expected-structured-output/jira-diff/JCTP2/10015.json
test_unstructured_ingest/expected-structured-output/jira-diff/JCTP3/10014.json

feat: jira connector (cloud) <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/Sharepoint/Shared Documents/ideas-page.json
test_unstructured_ingest/expected-structured-output/azure/spring-weather.html.json
test_unstructured_ingest/expected-structured-output/box/nested-1/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/box/nested-2/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/dropbox/nested-1/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/dropbox/nested-2/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/gcs/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/gcs/nested-1/nested/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/gcs/nested-2/nested/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/github/test.html.json
test_unstructured_ingest/expected-structured-output/local-single-file-with-encoding/fake-html-cp1252.html.json
test_unstructured_ingest/expected-structured-output/notion/122b2c22-996b-435b-9de2-ee0e9d2b04bc.json
test_unstructured_ingest/expected-structured-output/notion/438dbc49-2e06-4f01-8031-bf283be58a60.json
test_unstructured_ingest/expected-structured-output/notion/4695ea53-f2b3-45b4-8638-2212fd054d73.json
test_unstructured_ingest/expected-structured-output/notion/5481f29c-799a-4d7b-93ce-b11bcaede531.json
test_unstructured_ingest/expected-structured-output/notion/60377009-e6b2-47f3-a8ff-f159fd8b69f5.json
test_unstructured_ingest/expected-structured-output/notion/898538f2-26e1-4de7-81e6-354045d4d007.json
test_unstructured_ingest/expected-structured-output/notion/8db7ccc9-0a9c-4168-94c3-f997e60cb8cf.json
test_unstructured_ingest/expected-structured-output/notion/b2a12157-721e-4207-b3b7-527762b782c2.json
test_unstructured_ingest/expected-structured-output/notion/c47a4566-4c7a-488b-ac2a-1292ee507fcb.json
test_unstructured_ingest/expected-structured-output/notion/d3d87fc6-61cc-4bb5-89ed-e9dff0df1526.json
test_unstructured_ingest/expected-structured-output/notion/dfcbe584-30b1-4551-b533-e6a5759af842.json
test_unstructured_ingest/expected-structured-output/notion/feccfcd4-8ca0-4638-8212-1a5726461029.json

fix: split on para breaks in `partition_html`. <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/Sharepoint/Shared Documents/ideas-page.json
test_unstructured_ingest/expected-structured-output/azure/spring-weather.html.json
test_unstructured_ingest/expected-structured-output/box/nested-1/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/box/nested-2/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/1540126.json
test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/1605928.json
test_unstructured_ingest/expected-structured-output/dropbox/nested-1/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/dropbox/nested-2/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/gcs/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/gcs/nested-1/nested/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/gcs/nested-2/nested/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/github/test.html.json

fix: separate elements by `<br>` tag in `partition_html` <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/azure/rfc854.txt.json
test_unstructured_ingest/expected-structured-output/azure/spring-weather.html.json
test_unstructured_ingest/expected-structured-output/box/science-exploration-1p.pptx.json
test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/1605942.json
test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/229477.json
test_unstructured_ingest/expected-structured-output/confluence-diff/testteamsp/1605859.json
test_unstructured_ingest/expected-structured-output/dropbox/science-exploration-1p.pptx.json
test_unstructured_ingest/expected-structured-output/google-drive/1SpQuE7jHz9nMt5hfQXsiok1SgIdRYX5o-fake.docx.json
test_unstructured_ingest/expected-structured-output/jira-diff/1/10000.json
test_unstructured_ingest/expected-structured-output/jira-diff/1/10002.json
test_unstructured_ingest/expected-structured-output/local-single-file-with-encoding/fake-html-cp1252.html.json
test_unstructured_ingest/expected-structured-output/notion/b2a12157-721e-4207-b3b7-527762b782c2.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/azure/Core-Skills-for-Biomedical-Data-Scientists-2-pages.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/azure/IRS-form-1987.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/biomed-api/65/11/main.PMC6312790.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/biomed-api/75/29/main.PMC6312793.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/biomed-path/07/07/sbaa031.073.PMC7234218.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/s3/small-pdf-set/2023-Jan-economic-outlook.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/s3/small-pdf-set/Silent-Giant-(1).pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/s3/small-pdf-set/recalibrating-risk-report.pdf.json
test_unstructured_ingest/expected-structured-output/slack/C052BGT7718.json

Klaijan/improve is_possible_narrative_text and is_possible_title <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/biomed-api/65/11/main.PMC6312790.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-api/75/29/main.PMC6312793.pdf.json
test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper.pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/2023-Jan-economic-outlook.pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/Silent-Giant-(1).pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/recalibrating-risk-report.pdf.json

build(deps): PDF images, unstructured-inference==0.5.23 <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/azure/Core-Skills-for-Biomedical-Data-Scientists-2-pages.pdf.json
test_unstructured_ingest/expected-structured-output/azure/IRS-form-1987.pdf.json
test_unstructured_ingest/expected-structured-output/azure/IRS-form-1987.png.json
test_unstructured_ingest/expected-structured-output/biomed-api/65/11/main.PMC6312790.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-api/75/29/main.PMC6312793.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-path/07/07/sbaa031.073.PMC7234218.pdf.json
test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper.pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/2023-Jan-economic-outlook.pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/Silent-Giant-(1).pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/recalibrating-risk-report.pdf.json

enhancement: backup text categorization <- Ingest test fixtures update

---

CHANGELOG.md
Dockerfile
unstructured/__version__.py

Updated versions of:
Tesseract
Leptonica
Pandoc
Testing:
`make docker-build`
`make docker-test`

Updating deps from base image

---

test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/s3/small-pdf-set/2023-Jan-economic-outlook.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/s3/small-pdf-set/recalibrating-risk-report.pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/Silent-Giant-(1).pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/recalibrating-risk-report.pdf.json

fix: avoid PDF sorting error on negative coords <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/box/handbook-1p.docx.json.json

refactor languages parameter for pdf partition functions <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/box/handbook-1p.docx.json.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/Silent-Giant-(1).pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/recalibrating-risk-report.pdf.json

feat: improved chipper elements mapping and new category_depth metadata <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/Silent-Giant-(1).pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/recalibrating-risk-report.pdf.json

feat: improved chipper elements mapping and new title_depth metadata <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/azure/Core-Skills-for-Biomedical-Data-Scientists-2-pages.pdf.json
test_unstructured_ingest/expected-structured-output/azure/rfc854.txt.json
test_unstructured_ingest/expected-structured-output/biomed-api/65/11/main.PMC6312790.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-api/75/29/main.PMC6312793.pdf.json
test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper.pdf.json
test_unstructured_ingest/expected-structured-output/local-single-file/english-and-korean.png.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/azure/Core-Skills-for-Biomedical-Data-Scientists-2-pages.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/biomed-api/65/11/main.PMC6312790.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/biomed-api/75/29/main.PMC6312793.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/s3/small-pdf-set/2023-Jan-economic-outlook.pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/2023-Jan-economic-outlook.pdf.json

Klaijan/pdf numbered list <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/biomed-api/65/11/main.PMC6312790.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-api/75/29/main.PMC6312793.pdf.json
test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper.pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/2023-Jan-economic-outlook.pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/Silent-Giant-(1).pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/recalibrating-risk-report.pdf.json

chore: bump `unstructured-inference` to `0.6.1` <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/biomed-api/65/11/main.PMC6312790.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-api/75/29/main.PMC6312793.pdf.json
test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper.pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/2023-Jan-economic-outlook.pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/Silent-Giant-(1).pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/recalibrating-risk-report.pdf.json
test_unstructured_ingest/expected-structured-output/salesforce/Campaign/701Hu000001eX9EIAU.json
test_unstructured_ingest/expected-structured-output/salesforce/Campaign/701Hu000001eX9FIAU.json
test_unstructured_ingest/expected-structured-output/salesforce/Campaign/701Hu000001eX9GIAU.json
test_unstructured_ingest/expected-structured-output/salesforce/Campaign/701Hu000001eX9HIAU.json

feat: introduce language detection function for text partitioning function <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/Sharepoint/Shared Documents/stanley-cups.xlsx.json
test_unstructured_ingest/expected-structured-output/azure/Core-Skills-for-Biomedical-Data-Scientists-2-pages.pdf.json
test_unstructured_ingest/expected-structured-output/azure/IRS-form-1987.pdf.json
test_unstructured_ingest/expected-structured-output/azure/IRS-form-1987.png.json
test_unstructured_ingest/expected-structured-output/biomed-api/65/11/main.PMC6312790.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-api/75/29/main.PMC6312793.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-path/07/07/sbaa031.073.PMC7234218.pdf.json
test_unstructured_ingest/expected-structured-output/box/handbook-1p.docx.json
test_unstructured_ingest/expected-structured-output/box/science-exploration-1p.pptx.json
test_unstructured_ingest/expected-structured-output/dropbox/handbook-1p.docx.json
test_unstructured_ingest/expected-structured-output/dropbox/science-exploration-1p.pptx.json
test_unstructured_ingest/expected-structured-output/gcs/nested-2/stanley-cups.xlsx.json
test_unstructured_ingest/expected-structured-output/google-drive/117qrVqiCoR5EjYMsDHGdy3UMkEtKr9Q8-test-drive-doc.docx.json
test_unstructured_ingest/expected-structured-output/google-drive/1SpQuE7jHz9nMt5hfQXsiok1SgIdRYX5o-fake.docx.json
test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper.pdf.json
test_unstructured_ingest/expected-structured-output/onedrive/utic-test-ingest-fixtures/tests-example.xls.json
test_unstructured_ingest/expected-structured-output/outlook/21be155fb0c95885.eml.json
test_unstructured_ingest/expected-structured-output/outlook/497eba8c81c801c6.eml.json
test_unstructured_ingest/expected-structured-output/outlook/4a16a411f162ebbb.eml.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/2023-Jan-economic-outlook.pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/Silent-Giant-(1).pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/recalibrating-risk-report.pdf.json
test_unstructured_ingest/expected-structured-output/salesforce/Campaign/701Hu000001eX9EIAU.json
test_unstructured_ingest/expected-structured-output/salesforce/Campaign/701Hu000001eX9FIAU.json
test_unstructured_ingest/expected-structured-output/salesforce/Campaign/701Hu000001eX9GIAU.json
test_unstructured_ingest/expected-structured-output/salesforce/Campaign/701Hu000001eX9HIAU.json
test_unstructured_ingest/expected-structured-output/salesforce/EmailMessage/02sHu00001efErPIAU.json
test_unstructured_ingest/expected-structured-output/salesforce/EmailMessage/02sHu00001efErQIAU.json
test_unstructured_ingest/expected-structured-output/slack/C052BGT7718.json

feat/add sources from unstructured inference <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/azure/Core-Skills-for-Biomedical-Data-Scientists-2-pages.pdf.json
test_unstructured_ingest/expected-structured-output/azure/IRS-form-1987.pdf.json
test_unstructured_ingest/expected-structured-output/azure/IRS-form-1987.png.json
test_unstructured_ingest/expected-structured-output/biomed-api/65/11/main.PMC6312790.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-api/75/29/main.PMC6312793.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-path/07/07/sbaa031.073.PMC7234218.pdf.json
test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/biomed-api/65/11/main.PMC6312790.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/biomed-api/75/29/main.PMC6312793.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/biomed-path/07/07/sbaa031.073.PMC7234218.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/s3/small-pdf-set/2023-Jan-economic-outlook.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/s3/small-pdf-set/Silent-Giant-(1).pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/s3/small-pdf-set/recalibrating-risk-report.pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/2023-Jan-economic-outlook.pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/Silent-Giant-(1).pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/recalibrating-risk-report.pdf.json

Feat/1233 xycut pre post processing <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/azure/Core-Skills-for-Biomedical-Data-Scientists-2-pages.pdf.json
test_unstructured_ingest/expected-structured-output/azure/IRS-form-1987.png.json
test_unstructured_ingest/expected-structured-output/biomed-api/65/11/main.PMC6312790.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-api/75/29/main.PMC6312793.pdf.json
test_unstructured_ingest/expected-structured-output/jira-diff/JCTP2/10010.json
test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper.pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/2023-Jan-economic-outlook.pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/Silent-Giant-(1).pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/recalibrating-risk-report.pdf.json

chore: bump inference to 0.6.6 <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/azure/Core-Skills-for-Biomedical-Data-Scientists-2-pages.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-api/65/11/main.PMC6312790.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-api/75/29/main.PMC6312793.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-path/07/07/sbaa031.073.PMC7234218.pdf.json
test_unstructured_ingest/expected-structured-output/jira-diff/JCTP2/10010.json
test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper.pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/2023-Jan-economic-outlook.pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/Silent-Giant-(1).pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/recalibrating-risk-report.pdf.json

Yuming/refactor ocr <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/jira-diff/JCTP2/10010.json

ci: add retry to elastic search ingest test <- Ingest test fixtures update

---

CHANGELOG.md
unstructured/__version__.py
unstructured/ingest/processor.py

Change partition kwarg from ocr_languages -> languages
Closes out https://github.com/Unstructured-IO/unstructured/issues/1588

roman/update language kwarg partition ingest 

---

test_unstructured_ingest/expected-structured-output/azure/Core-Skills-for-Biomedical-Data-Scientists-2-pages.pdf.json
test_unstructured_ingest/expected-structured-output/azure/IRS-form-1987.pdf.json
test_unstructured_ingest/expected-structured-output/azure/IRS-form-1987.png.json
test_unstructured_ingest/expected-structured-output/biomed-api/65/11/main.PMC6312790.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-api/75/29/main.PMC6312793.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-path/07/07/sbaa031.073.PMC7234218.pdf.json
test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper.pdf.json
test_unstructured_ingest/expected-structured-output/notion/898538f2-26e1-4de7-81e6-354045d4d007.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/2023-Jan-economic-outlook.pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/Silent-Giant-(1).pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/recalibrating-risk-report.pdf.json

feat: change default hi_res model to yolox quantized <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/Sharepoint/Shared Documents/stanley-cups.xlsx.json
test_unstructured_ingest/expected-structured-output/gcs/nested-2/stanley-cups.xlsx.json
test_unstructured_ingest/expected-structured-output/notion/898538f2-26e1-4de7-81e6-354045d4d007.json
test_unstructured_ingest/expected-structured-output/onedrive/utic-test-ingest-fixtures/tests-example.xls.json

Klaijan/xlsx sub tables <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/azure/Core-Skills-for-Biomedical-Data-Scientists-2-pages.pdf.json
test_unstructured_ingest/expected-structured-output/azure/IRS-form-1987.pdf.json
test_unstructured_ingest/expected-structured-output/azure/IRS-form-1987.png.json
test_unstructured_ingest/expected-structured-output/biomed-api/65/11/main.PMC6312790.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-api/75/29/main.PMC6312793.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-path/07/07/sbaa031.073.PMC7234218.pdf.json
test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper.pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/2023-Jan-economic-outlook.pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/Silent-Giant-(1).pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/recalibrating-risk-report.pdf.json

Fix/1209 tweak xycut ordering output <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/azure/Core-Skills-for-Biomedical-Data-Scientists-2-pages.pdf.json
test_unstructured_ingest/expected-structured-output/azure/IRS-form-1987.pdf.json
test_unstructured_ingest/expected-structured-output/azure/IRS-form-1987.png.json
test_unstructured_ingest/expected-structured-output/biomed-api/65/11/main.PMC6312790.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-api/75/29/main.PMC6312793.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-path/07/07/sbaa031.073.PMC7234218.pdf.json
test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper.pdf.json
test_unstructured_ingest/expected-structured-output/notion/8db7ccc9-0a9c-4168-94c3-f997e60cb8cf.json
test_unstructured_ingest/expected-structured-output/notion/fee2149e-6240-4431-8e98-a04a2e460a66.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/2023-Jan-economic-outlook.pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/Silent-Giant-(1).pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/recalibrating-risk-report.pdf.json

Chore: support entire page OCR with `ocr_mode` and `ocr_languages` <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/azure/Core-Skills-for-Biomedical-Data-Scientists-2-pages.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-api/65/11/main.PMC6312790.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-api/75/29/main.PMC6312793.pdf.json
test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper.pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/2023-Jan-economic-outlook.pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/Silent-Giant-(1).pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/recalibrating-risk-report.pdf.json

Refactor: support entire page OCR with `ocr_mode` and `ocr_languages` <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/google-drive/117qrVqiCoR5EjYMsDHGdy3UMkEtKr9Q8-test-drive-doc.docx.json
test_unstructured_ingest/expected-structured-output/google-drive/1SpQuE7jHz9nMt5hfQXsiok1SgIdRYX5o-fake.docx.json
test_unstructured_ingest/expected-structured-output/google-drive/1cTKXAreuj-wYmL38nFnqKvz3X8UKcaMC-foo.txt.json
test_unstructured_ingest/test-ingest-google-drive.sh

just upping the version on the google drive tests
probably an internal google change and not a human change.
[https://github.com/googleapis/google-api-python-client/blob/7df5db27b136225b7bfb2cad041242316f55511d/tests/data/drive.json#L319
](url)
```
"version": {
"type": "string",
"description": "A monotonically increasing version number for the file. This reflects every change made to the file on the server, even those not visible to the user.",
"format": "int64"
},
```

up version of google drive tests

---

docs/source/introduction/key_concepts.rst

Fixes #1502
Here I have replaced `stream_connectors.html` with `source_connectors.html`.

Doc : replace link `upstream connectors` with `source connectors`

---

CHANGELOG.md
unstructured/partition/pdf.py

Fix github issue https://github.com/Unstructured-IO/unstructured/issues/1686

fix: initialize uri before try-except

---

test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper-with-table.jpg.json

roman/cli infer table arg <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/Sharepoint/Shared Documents/fake-text.txt.json
test_unstructured_ingest/expected-structured-output/Sharepoint/Shared Documents/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/Sharepoint/Shared Documents/stanley-cups.xlsx.json

feat: rbac ingestion for sharepoint <- Ingest test fixtures update

---

CHANGELOG.md
unstructured/__version__.py
unstructured/utils.py

Allow to slice on further metrics

Add more params for scarf

---

test_unstructured_ingest/expected-structured-output/local-single-file/UDHR_first_article_all.txt.json
test_unstructured_ingest/expected-structured-output/outlook/21be155fb0c95885.eml.json

default to None for languages <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/dropbox/handbook-1p.docx.json

fix: #1461 Footer should appear at section start <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/azure/IRS-form-1987.png.json
test_unstructured_ingest/expected-structured-output/biomed-api/65/11/main.PMC6312790.pdf.json
test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper-with-table.jpg.json
test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper.pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/2023-Jan-economic-outlook.pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/Silent-Giant-(1).pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/recalibrating-risk-report.pdf.json

feat: improve natural reading order by filtering OCR results <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/s3/small-pdf-set/page-with-formula.pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/page-with-formula.pdf.json

Klaijan/feat: cct-ci <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/s3/small-pdf-set/page-with-formula.pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/page-with-formula.pdf.json

A single page PDF file was added to the s3 location used in the s3 ingest test. This PR just adds the expected output .json's file for that added file. (no code changes).

chore: update ingest-test-fixtures with new doc

---

.github/workflows/ingest-test-fixtures-update-pr.yml

Add `test_unstructured_ingest/metrics` path for evaluation metrics master file.

build: ingest fixtures workflow to include metrics dir

---

.github/workflows/ingest-test-fixtures-update-pr.yml

Reference: https://github.com/marketplace/actions/create-pull-request#add-specific-paths

chore: fix paths in ingest-test-fixtures-update-pr.yml

---

test_unstructured_ingest/expected-structured-output/dropbox/test-input/handbook-1p.docx.json
test_unstructured_ingest/expected-structured-output/dropbox/test-input/nested-1/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/dropbox/test-input/nested-2/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/dropbox/test-input/science-exploration-1p.pptx.json
test_unstructured_ingest/expected-structured-output/local-single-file-with-encoding/fake-html-cp1252.html.json
test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper-with-table.jpg.json
test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper.pdf.json
test_unstructured_ingest/expected-structured-output/local-single-file/UDHR_first_article_all.txt.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/azure/Core-Skills-for-Biomedical-Data-Scientists-2-pages.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/azure/IRS-form-1987.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/biomed-api/65/11/main.PMC6312790.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/biomed-api/75/29/main.PMC6312793.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/biomed-path/07/07/sbaa031.073.PMC7234218.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/s3/small-pdf-set/2023-Jan-economic-outlook.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/s3/small-pdf-set/Silent-Giant-(1).pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/s3/small-pdf-set/page-with-formula.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/s3/small-pdf-set/recalibrating-risk-report.pdf.json

local connector metadata and deserialization fix <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/biomed-api/65/11/main.PMC6312790.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-api/75/29/main.PMC6312793.pdf.json
test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper.pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/2023-Jan-economic-outlook.pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/recalibrating-risk-report.pdf.json

feat: clean pdfminer elements inside tables <- Ingest test fixtures update

---

.github/workflows/ci.yml
.github/workflows/ingest-test-fixtures-update-pr.yml
CHANGELOG.md
unstructured/__version__.py

Fixed some syntax errors in the update ingest CI job causing it to always fail

Fix ingest test CI job

---

test_unstructured_ingest/metrics/aggregate-scores-cct.tsv
test_unstructured_ingest/metrics/aggregate-scores-element-type.tsv
test_unstructured_ingest/metrics/all-docs-cct.tsv
test_unstructured_ingest/metrics/all-docs-element-type-frequency.tsv

Klaijan/build: element type frequency evaluation metrics workflow in ci <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/azure/IRS-form-1987.pdf.json

refactor: `partition_pdf()` for `ocr_only` strategy <- Ingest test fixtures update

---

CHANGELOG.md
test_unstructured_ingest/test-ingest.sh
unstructured/__version__.py
unstructured/documents/elements.py

Closes: #1892 (check the issue for more info)

bugfix: ingest pipeline with chunking and embedding does not persist data to the embedding step

---

CHANGELOG.md

Removes duplicated entries in changelog

chore: changelog repair

---

CHANGELOG.md

Per https://github.com/Unstructured-IO/unstructured/commit/a2af72bb79d94941f867d93dfeaed9c4a5d510f7 , these changes were part of 0.10.26.

chore: moar changelog repair

---

CHANGELOG.md
unstructured/__version__.py
unstructured/ingest/pipeline/pipeline.py

move check for download only after source node run

ingest download-only fix

---

test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/azure/Core-Skills-for-Biomedical-Data-Scientists-2-pages.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/biomed-api/65/11/main.PMC6312790.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/biomed-api/75/29/main.PMC6312793.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/biomed-path/07/07/sbaa031.073.PMC7234218.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/s3/small-pdf-set/2023-Jan-economic-outlook.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/s3/small-pdf-set/Silent-Giant-(1).pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/s3/small-pdf-set/page-with-formula.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/s3/small-pdf-set/recalibrating-risk-report.pdf.json
test_unstructured_ingest/metrics/all-docs-cct.tsv

support table conversion for tabular destination connectors <- Ingest test fixtures update

---

test_unstructured_ingest/metrics/all-docs-cct.tsv

chore: remove copy line from non-matrix connectors <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/jira-diff/1/10000.json
test_unstructured_ingest/expected-structured-output/local-single-file/example-docs/language-docs/UDHR_first_article_all.txt.json
test_unstructured_ingest/metrics/aggregate-scores-cct.tsv
test_unstructured_ingest/metrics/aggregate-scores-element-type.tsv
test_unstructured_ingest/metrics/all-docs-cct.tsv
test_unstructured_ingest/metrics/all-docs-element-type-frequency.tsv

chore: add doctype to ingest evaluation functions <- Ingest test fixtures update

---

CHANGELOG.md
unstructured/__version__.py
unstructured/ingest/cli/base/cmd.py
unstructured/ingest/cli/cmds/airtable.py
unstructured/ingest/cli/cmds/azure.py
unstructured/ingest/cli/cmds/azure_cognitive_search.py
unstructured/ingest/cli/cmds/biomed.py
unstructured/ingest/cli/cmds/box.py
unstructured/ingest/cli/cmds/confluence.py
unstructured/ingest/cli/cmds/delta_table.py
unstructured/ingest/cli/cmds/discord.py
unstructured/ingest/cli/cmds/dropbox.py
unstructured/ingest/cli/cmds/elasticsearch.py
unstructured/ingest/cli/cmds/gcs.py
unstructured/ingest/cli/cmds/github.py
unstructured/ingest/cli/cmds/gitlab.py
unstructured/ingest/cli/cmds/google_drive.py
unstructured/ingest/cli/cmds/jira.py
unstructured/ingest/cli/cmds/local.py
unstructured/ingest/cli/cmds/notion.py
unstructured/ingest/cli/cmds/onedrive.py
unstructured/ingest/cli/cmds/outlook.py
unstructured/ingest/cli/cmds/reddit.py
unstructured/ingest/cli/cmds/s3.py
unstructured/ingest/cli/cmds/salesforce.py
unstructured/ingest/cli/cmds/sharepoint.py
unstructured/ingest/cli/cmds/slack.py
unstructured/ingest/cli/cmds/wikipedia.py
unstructured/ingest/cli/interfaces.py
unstructured/ingest/cli/utils.py

Add new class to wrap base config and cli mixin to help with typing:
```python
class CliConfig(BaseConfig, CliMixin):
pass
```

Add CliMix class to wrap both BaseConfig and CliMixin

---

test_unstructured_ingest/expected-structured-output/embed/example-docs/book-war-and-peace-1p.txt.json

Extend ingest options to support multiple embedding modules, add deterministic ingest test for embeddings <- Ingest test fixtures update

---

.github/workflows/ci.yml
.github/workflows/ingest-test-fixtures-update-pr.yml

Moved Azure OIDC to use only Pull Request subject, this gets rid of the noise it creates in the PR’s

ci(test): remove environment identifier

---

Dockerfile

This includes latest version and security updates available from upstream

Bump base image with latest security fixes

---

test_unstructured_ingest/metrics/aggregate-scores-cct.tsv
test_unstructured_ingest/metrics/all-docs-cct.tsv

refactor: separate click wrappers from core evaluation functionality <- Ingest test fixtures update

---

requirements/Makefile
requirements/ingest/Makefile
requirements/ingest/embed-huggingface.in

- add missing make file in ingest folder

fix: make pip compile

---

test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/s3/small-pdf-set/IRS-form-1987.pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/IRS-form-1987.pdf.json
test_unstructured_ingest/metrics/aggregate-scores-cct.tsv
test_unstructured_ingest/metrics/all-docs-cct.tsv

Klaijan/add ingest-test ci file <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/azure/Core-Skills-for-Biomedical-Data-Scientists-2-pages.pdf.json
test_unstructured_ingest/expected-structured-output/azure/IRS-form-1987.pdf.json
test_unstructured_ingest/expected-structured-output/azure/IRS-form-1987.png.json
test_unstructured_ingest/expected-structured-output/biomed-api/65/11/main.PMC6312790.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-api/75/29/main.PMC6312793.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-path/07/07/sbaa031.073.PMC7234218.pdf.json
test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper-with-table.jpg.json
test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/azure/Core-Skills-for-Biomedical-Data-Scientists-2-pages.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/biomed-api/65/11/main.PMC6312790.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/biomed-api/75/29/main.PMC6312793.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/biomed-path/07/07/sbaa031.073.PMC7234218.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/s3/small-pdf-set/2023-Jan-economic-outlook.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/s3/small-pdf-set/Silent-Giant-(1).pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/s3/small-pdf-set/page-with-formula.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/s3/small-pdf-set/recalibrating-risk-report.pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/2023-Jan-economic-outlook.pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/Silent-Giant-(1).pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/page-with-formula.pdf.json
test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/recalibrating-risk-report.pdf.json

Jj/2011 missing languages metadata <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/azure/IRS-form-1987.png.json
test_unstructured_ingest/expected-structured-output/biomed-api/65/11/main.PMC6312790.pdf.json
test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper-with-table.jpg.json
test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper.pdf.json

Fix: missing characters at the beginning of sentences on table ingest output after table OCR refactor <- Ingest test fixtures update

---

test_unstructured_ingest/metrics/aggregate-scores-cct.tsv
test_unstructured_ingest/metrics/all-docs-cct.tsv

update metrics-json-manifest <- Ingest test fixtures update

---

Dockerfile

This adds Nvidia GPU support with CUDA to container images.

Update base image to include CUDA 11.8

---

test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/azure/Core-Skills-for-Biomedical-Data-Scientists-2-pages.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/biomed-api/65/11/main.PMC6312790.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/biomed-api/75/29/main.PMC6312793.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/biomed-path/07/07/sbaa031.073.PMC7234218.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/s3/small-pdf-set/2023-Jan-economic-outlook.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/s3/small-pdf-set/Silent-Giant-(1).pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/s3/small-pdf-set/page-with-formula.pdf.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/s3/small-pdf-set/recalibrating-risk-report.pdf.json

fix(ingest): canonicalize ingest JSON <- Ingest test fixtures update

---

test_unstructured_ingest/metrics/aggregate-scores-cct.tsv
test_unstructured_ingest/metrics/all-docs-cct.tsv

Klaijan/get eval metrics ingest in <- Ingest test fixtures update

---

test_unstructured_ingest/metrics/aggregate-scores-cct.tsv
test_unstructured_ingest/metrics/all-docs-cct.tsv

ci: make script fail on eval metrics diff <- Ingest test fixtures update

---

docs/source/api.rst

Updated docker image link in documentation to be consistent with README.

docs: update docker image link

---

test_unstructured_ingest/test-ingest-src.sh

Create the file outside the if-clause.

fix: skipped file not found error

---

.github/workflows/ci.yml
test_unstructured_ingest/test-ingest-dest.sh

Add AZURE_DEST_CONNECTION_STR to list of env vars in ci ingest test

chore: enable azure destination CI tests

---

test_unstructured_ingest/expected-structured-output/biomed-api/65/11/main.PMC6312790.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-api/75/29/main.PMC6312793.pdf.json
test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper.pdf.json

fix: consider text in cid code as invalid in hi_res <- Ingest test fixtures update

---

CHANGELOG.md
unstructured/__version__.py
unstructured/partition/pdf.py

add `extract_element_types` to partition_pdf docstring and reword other parameter descriptions

Update parition_pdf docstring

---

test_unstructured_ingest/expected-structured-output/biomed-api/65/11/main.PMC6312790.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-api/75/29/main.PMC6312793.pdf.json
test_unstructured_ingest/expected-structured-output/s3/2023-Jan-economic-outlook.pdf.json
test_unstructured_ingest/expected-structured-output/s3/Silent-Giant-(1).pdf.json
test_unstructured_ingest/expected-structured-output/s3/recalibrating-risk-report.pdf.json

feat: keep all image elements when using `hi_res` strategy. <- Ingest test fixtures update

---

CHANGELOG.md
docs/source/core/chunking.rst
test_unstructured/chunking/test_basic.py
test_unstructured/partition/test_auto.py
unstructured/__version__.py
unstructured/chunking/__init__.py
unstructured/chunking/base.py
unstructured/chunking/basic.py
unstructured/chunking/title.py

This PR culminates the restructuring of chunking over my prior dozen-or-so commits by adding the new options to the API and documentation.
Separately I'll be adding a new ingest test to defend against regression, although the integration test included in this PR will do a pretty good job of that too.

feature(chunking): add basic strategy and overlap

---

docs/source/ingest/destination_connectors.rst
docs/source/ingest/destination_connectors/sql.rst

To test:
> cd docs && make HTML
changelogs:
- remove unindented line in destination connector's sql.rst file 
- add elasticsearch page into destination_connector.rst file

Fix sphinx error

---

CHANGELOG.md
test_unstructured_ingest/dest/azure-cognitive-search.sh
test_unstructured_ingest/unit/test_sql_conform_dict.py
unstructured/__version__.py
unstructured/ingest/connector/azure_cognitive_search.py
unstructured/ingest/connector/chroma.py
unstructured/ingest/connector/delta_table.py
unstructured/ingest/connector/elasticsearch.py
unstructured/ingest/connector/fsspec/fsspec.py
unstructured/ingest/connector/mongodb.py
unstructured/ingest/connector/pinecone.py
unstructured/ingest/connector/qdrant.py
unstructured/ingest/connector/sql.py
unstructured/ingest/connector/weaviate.py
unstructured/ingest/interfaces.py

* Make sure all destination connectors implement the base abstract methods using the same signatures. 
* Also leverage conform dict in the base methods to make sure it's called in a consistent fashion.
* Additional updates to move the common code into the base destination connector class

fix: ensure consistency in method signatures across destination connectors

---

test_unstructured_ingest/expected-structured-output/local-single-file-basic-chunking/handbook-1p.docx.json
test_unstructured_ingest/metrics/element-type/aggregate-scores-element-type.tsv
test_unstructured_ingest/metrics/element-type/all-docs-element-type-frequency.tsv
test_unstructured_ingest/metrics/text-extraction/aggregate-scores-cct.tsv
test_unstructured_ingest/metrics/text-extraction/all-docs-cct.tsv

feat(ingest): add basic chunking to ingest <- Ingest test fixtures update

---

CHANGELOG.md
unstructured/__version__.py
unstructured/ingest/connector/mongodb.py

Adds a driver with `unstructured` version information to the MongoDB driver.
Good to go as long as the MongoDB ingest test run successfully.

enhancement: add mongodb driver

---

test_unstructured_ingest/expected-structured-output/azure/Core-Skills-for-Biomedical-Data-Scientists-2-pages.pdf.json
test_unstructured_ingest/expected-structured-output/azure/IRS-form-1987.pdf.json
test_unstructured_ingest/expected-structured-output/azure/IRS-form-1987.png.json
test_unstructured_ingest/expected-structured-output/biomed-api/65/11/main.PMC6312790.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-api/75/29/main.PMC6312793.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-path/07/07/sbaa031.073.PMC7234218.pdf.json
test_unstructured_ingest/expected-structured-output/s3/2023-Jan-economic-outlook.pdf.json
test_unstructured_ingest/expected-structured-output/s3/Silent-Giant-(1).pdf.json
test_unstructured_ingest/expected-structured-output/s3/recalibrating-risk-report.pdf.json
test_unstructured_ingest/metrics/element-type/aggregate-scores-element-type.tsv
test_unstructured_ingest/metrics/element-type/all-docs-element-type-frequency.tsv
test_unstructured_ingest/metrics/text-extraction/aggregate-scores-cct.tsv
test_unstructured_ingest/metrics/text-extraction/all-docs-cct.tsv

fix: default hi_res model rely on inference setting <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/onedrive/utic-test-ingest-fixtures/tests-example.xls.json

fix(xlsx): xlsx subtable algorithm <- Ingest test fixtures update

---

CHANGELOG.md
test_unstructured/partition/xlsx/test_xlsx.py
unstructured/__version__.py
unstructured/partition/xlsx.py

**Summary**
Refactoring as part of `partition_xlsx()` algorithm replacement that was delayed by some CI challenges.
A separate PR because it is cohesive and relatively independent from the prior PR.

rfctr(xlsx): extract connected components

---

test_unstructured_ingest/expected-structured-output/Sharepoint-with-permissions/Shared Documents/fake-text.txt.json
test_unstructured_ingest/expected-structured-output/Sharepoint-with-permissions/Shared Documents/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/Sharepoint-with-permissions/Shared Documents/permissions-fake-text.docx.json
test_unstructured_ingest/expected-structured-output/Sharepoint-with-permissions/Shared Documents/stanley-cups.xlsx.json
test_unstructured_ingest/expected-structured-output/Sharepoint/Shared Documents/fake-text.txt.json
test_unstructured_ingest/expected-structured-output/Sharepoint/Shared Documents/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/Sharepoint/Shared Documents/permissions-fake-text.docx.json
test_unstructured_ingest/expected-structured-output/Sharepoint/Shared Documents/stanley-cups.xlsx.json

[DRAFT] fix: handling of varied SharePoint date formats <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/Sharepoint-with-permissions/Shared Documents/fake-text.txt.json
test_unstructured_ingest/expected-structured-output/Sharepoint-with-permissions/Shared Documents/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/Sharepoint-with-permissions/Shared Documents/permissions-fake-text.docx.json
test_unstructured_ingest/expected-structured-output/Sharepoint-with-permissions/Shared Documents/stanley-cups.xlsx.json

feat: element type accuracy grouping <- Ingest test fixtures update

---

CHANGELOG.md
test_unstructured/metrics/test_evaluate.py
unstructured/ingest/evaluate.py
unstructured/metrics/evaluate.py

refactor variable name for consistency.

refactor: refactor var name for consistency

---

CHANGELOG.md
unstructured/metrics/evaluate.py
unstructured/metrics/table/table_eval.py

This PR:
- replaces `-1.0` value in table metrics with `nan`s 
- corrected rows filtering basing on above

feat(eval): Correct table metrics evaluations

---

test_unstructured_ingest/expected-structured-output/azure/spring-weather.html.json
test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/1605956.json
test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/229477.json
test_unstructured_ingest/expected-structured-output/confluence-diff/testteamsp/1605859.json
test_unstructured_ingest/expected-structured-output/confluence-diff/testteamsp/1605989.json
test_unstructured_ingest/expected-structured-output/confluence-diff/testteamsp/1802252.json
test_unstructured_ingest/expected-structured-output/github/test.html.json
test_unstructured_ingest/expected-structured-output/notion/b2a12157-721e-4207-b3b7-527762b782c2.json
test_unstructured_ingest/expected-structured-output/notion/c47a4566-4c7a-488b-ac2a-1292ee507fcb.json

[DO NOT MERGE] feat: add support for start_index in html links extraction <- Ingest test fixtures update

---

CHANGELOG.md
docs/source/platforms/platform_destinations/google_cloud_destination.rst
docs/source/platforms/platform_sources/google_cloud_source.rst
unstructured/__version__.py

To test:
> cd docs && make html
Changelogs:
* added a note to have **Storage Object Viewer** IAM Role for the GCS source connector.
* added a note to have **Storage Object Creator** IAM Role for the GCS destination connector.

Update requirements for GCS IAM Role for Platform Source & Destination Connectors

---

test_unstructured_ingest/expected-structured-output/local-single-file-basic-chunking/handbook-1p.docx.json

feat(chunking): composite text gets is_continuation <- Ingest test fixtures update

---

examples/chroma-news-of-the-day/news-of-the-day.ipynb

Update the metadata `link_urls` in the News-of-the-Day notebook example.

Update link_urls metadata

---

CHANGELOG.md
setup.py
unstructured/__version__.py

Quick fix for issue https://github.com/Unstructured-IO/unstructured/issues/2658

bug/unstructured-ingest produces ModuleNotFoundError: No module named 'unstructured.txtgest

---

test_unstructured_ingest/expected-structured-output/local-single-file-basic-chunking/handbook-1p.docx.json

feat(chunking): add metadata.orig_elements serde <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/biomed-api/75/29/main.PMC6312793.pdf.json
test_unstructured_ingest/expected-structured-output/s3/2023-Jan-economic-outlook.pdf.json
test_unstructured_ingest/expected-structured-output/s3/recalibrating-risk-report.pdf.json
test_unstructured_ingest/metrics/text-extraction/aggregate-scores-cct.tsv
test_unstructured_ingest/metrics/text-extraction/all-docs-cct.tsv

Fix: embedded text not getting merged with inferred elements <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/local-single-file-chunk-no-orig-elements/multi-column-2p.pdf.json

feat: add --include-orig-elements option to Ingest CLI <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/Sharepoint-with-permissions/Shared Documents/stanley-cups.xlsx.json
test_unstructured_ingest/expected-structured-output/Sharepoint/Shared Documents/stanley-cups.xlsx.json
test_unstructured_ingest/expected-structured-output/gcs/nested-2/stanley-cups.xlsx.json
test_unstructured_ingest/expected-structured-output/local-single-file-basic-chunking/handbook-1p.docx.json
test_unstructured_ingest/expected-structured-output/local-single-file-chunk-no-orig-elements/multi-column-2p.pdf.json
test_unstructured_ingest/expected-structured-output/onedrive/utic-test-ingest-fixtures/tests-example.xls.json
test_unstructured_ingest/metrics/text-extraction/aggregate-scores-cct.tsv
test_unstructured_ingest/metrics/text-extraction/all-docs-cct.tsv

Better element IDs <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/local-single-file-basic-chunking/handbook-1p.docx.json
test_unstructured_ingest/expected-structured-output/local-single-file-chunk-no-orig-elements/multi-column-2p.pdf.json

Preparing the ground for better element IDs <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/local-single-file-basic-chunking/handbook-1p.docx.json
test_unstructured_ingest/expected-structured-output/local-single-file-chunk-no-orig-elements/multi-column-2p.pdf.json

Better element IDs - deterministic and document-unique hashes <- Ingest test fixtures update

---

CHANGELOG.md
setup.py
unstructured/__version__.py

Fixes https://github.com/Unstructured-IO/unstructured/issues/2855

fix: Brings back missing word list files

---

test_unstructured_ingest/expected-structured-output/Sharepoint-with-permissions/Shared Documents/stanley-cups.xlsx.json
test_unstructured_ingest/expected-structured-output/Sharepoint/Shared Documents/stanley-cups.xlsx.json
test_unstructured_ingest/expected-structured-output/gcs/nested-2/stanley-cups.xlsx.json

Preparing the foundation for better element IDs <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/Sharepoint-with-permissions/Shared Documents/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/Sharepoint-with-permissions/SitePages/Home.html.json
test_unstructured_ingest/expected-structured-output/Sharepoint-with-permissions/SitePages/This-is-a-title.html.json
test_unstructured_ingest/expected-structured-output/Sharepoint/Shared Documents/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/Sharepoint/SitePages/Home.html.json
test_unstructured_ingest/expected-structured-output/Sharepoint/SitePages/This-is-a-title.html.json
test_unstructured_ingest/expected-structured-output/azure/spring-weather.html.json
test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/1540126.json
test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/1605928.json
test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/1605942.json
test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/1605956.json
test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/229477.json
test_unstructured_ingest/expected-structured-output/confluence-diff/testteamsp/1605859.json
test_unstructured_ingest/expected-structured-output/confluence-diff/testteamsp/1605989.json
test_unstructured_ingest/expected-structured-output/confluence-diff/testteamsp/1802252.json
test_unstructured_ingest/expected-structured-output/confluence-diff/testteamsp/1867777.json
test_unstructured_ingest/expected-structured-output/confluence-diff/testteamsp/2589690.json
test_unstructured_ingest/expected-structured-output/confluence-diff/testteamsp/2589704.json
test_unstructured_ingest/expected-structured-output/dropbox/nested-1/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/dropbox/nested-2/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/gcs/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/gcs/nested-1/nested/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/gcs/nested-2/nested/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/github/test.html.json
test_unstructured_ingest/expected-structured-output/local-single-file-with-encoding/fake-html-cp1252.html.json

chore CORE-4775: remove html page number metadata field <- Ingest test fixtures update

---

CHANGELOG.md
test_unstructured/partition/csv/test_tsv.py
unstructured/__version__.py
unstructured/partition/tsv.py

feat: add chunking to partition_tsv

---

test_unstructured/partition/docx/test_docx.py

No code changes, strictly this single block move.
Move `Describe_DocxPartitioner` unit-test class to bottom so `DescribeDocxPartitionerOptions` unit-test to follow in subsequent commit will be together with it. Integration tests first, then unit tests, for consistency with other test modules e.g. test_pptx.
I added `Describe_DocxPartitioner` soon after I arrived, before we adopted the convention of placing unit-tests after integration tests. Move this so we can maintain that consistency with the block of tests to follow in a closely subsequent PR.

rfctr(docx): move docx unit tests to bottom

---

test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper.json

fix: decide table extraction <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/gcs/nested-1/fake-text.txt.json
test_unstructured_ingest/expected-structured-output/gcs/nested-2/fake-text.txt.json

feat: Migrate over fsspec connectors <- Ingest test fixtures update

---

CHANGELOG.md
test_unstructured/documents/test_html.py
test_unstructured/partition/test_html.py
unstructured/__version__.py
unstructured/documents/html.py
unstructured/documents/html_elements.py
unstructured/partition/html.py

**Summary**
Remove dead code and organize helpers of HTMLDocument in preparation for improvements and bug-fixes to follow

rfctr(html): improve SNR in HTMLDocument

---

test_unstructured_ingest/expected-structured-output/box/handbook-1p.docx.json
test_unstructured_ingest/expected-structured-output/box/nested-1/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/box/nested-1/nested-2/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/box/science-exploration-1p.pptx.json

fix: relative path / permissions issues with v2 fsspec connectors <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/local-single-file-basic-chunking/handbook-1p.docx.json
test_unstructured_ingest/expected-structured-output/local-single-file-chunk-no-orig-elements/multi-column-2p.pdf.json

Roman/fix ingest async connectors <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/google-drive/1m1TUgyLv0hHdlsuL7DOWBAKQtvrhWNiV-recalibrating-risk-report.pdf.json

fix: docker image publishing error <- Ingest test fixtures update

---

CHANGELOG.md
scripts/docker-smoke-test.sh
test_unstructured_ingest/expected-structured-output/google-drive/1m1TUgyLv0hHdlsuL7DOWBAKQtvrhWNiV-recalibrating-risk-report.pdf.json
unstructured/__version__.py

This PR aims to fix a docker image publishing error caused by user changes when pulling the `amd64` image from the `unstructured` `wolfi-base` image. (https://github.com/Unstructured-IO/unstructured/pull/3213).

fix: docker image publishing error

---

Dockerfile-amd64

build: fix amd64 image hash

---

CHANGELOG.md
test_unstructured/partition/test_auto.py
unstructured/__version__.py
unstructured/partition/auto.py

**Summary**
Remedy gap where `strategy` argument passed to `partition()` was not forwarded to `partition_pptx()` or `partition_docx()`.

fix(auto): partition() passes strategy to PPTX,DOCX

---

test_unstructured_ingest/expected-structured-output/onedrive/utic-test-ingest-fixtures/fake-text.txt.json
test_unstructured_ingest/expected-structured-output/onedrive/utic-test-ingest-fixtures/nested/fake-text.txt.json
test_unstructured_ingest/expected-structured-output/onedrive/utic-test-ingest-fixtures/tests-example.xls.json

feat/migrate onedrive src <- Ingest test fixtures update

---

CHANGELOG.md
test_unstructured_ingest/dest/mongodb.sh
unstructured/__version__.py
unstructured/ingest/v2/cli/cmds/__init__.py
unstructured/ingest/v2/cli/cmds/mongodb.py
unstructured/ingest/v2/examples/example_mongodb.py
unstructured/ingest/v2/processes/connectors/mongodb.py

This PR provides support for V2 mongodb destination connector.

rfctr: implement mongodb v2 destination connector

---

test_unstructured_ingest/expected-structured-output/s3/2023-Jan-economic-outlook.pdf.json

feat/persist metadata for fsspec connectors <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/s3/2023-Jan-economic-outlook.pdf.json

build(deps): bump unstructured.paddleocr 2.8.0 <- Ingest test fixtures update

---

CHANGELOG.md
requirements/base.txt
requirements/dev.txt
requirements/extra-paddleocr.in
requirements/extra-paddleocr.txt
requirements/extra-pdf-image.txt
requirements/huggingface.txt
requirements/ingest/chroma.txt
requirements/ingest/databricks-volumes.txt
requirements/ingest/embed-aws-bedrock.txt
requirements/ingest/embed-huggingface.txt
requirements/ingest/embed-octoai.txt
requirements/ingest/embed-openai.txt
requirements/ingest/embed-vertexai.txt
requirements/ingest/embed-voyageai.txt
requirements/ingest/gcs.txt
requirements/ingest/google-drive.txt
requirements/ingest/qdrant.txt
requirements/ingest/singlestore.txt
requirements/test.txt
test_unstructured_ingest/expected-structured-output/s3/2023-Jan-economic-outlook.pdf.json
unstructured/__version__.py

Bump unstructured.paddleocr to `2.8.0`

build(deps): bump unstructured.paddleocr 2.8.0

---

test_unstructured_ingest/expected-structured-output/s3/2023-Jan-economic-outlook.pdf.json

rfctr [P6M-398]: salesforce connector v2 <- Ingest test fixtures update

---

CHANGELOG.md
example-docs/simple.json
example-docs/spring-weather.html.json
test_unstructured/partition/test_auto.py
unstructured/__version__.py

**Summary**
Improve expression in auto-partition tests and fix xfails and skips. Add issues for the two hard-fails where xfail needed to stay.

rfctr(auto): fix auto-partition test xfails and skips

---

requirements/base.txt
requirements/dev.txt
requirements/extra-paddleocr.txt
requirements/extra-pdf-image.txt
requirements/huggingface.txt
requirements/ingest/astra.txt
requirements/ingest/azure.txt
requirements/ingest/chroma.txt
requirements/ingest/clarifai.txt
requirements/ingest/embed-aws-bedrock.txt
requirements/ingest/embed-huggingface.txt
requirements/ingest/embed-octoai.txt
requirements/ingest/embed-openai.txt
requirements/ingest/embed-vertexai.txt
requirements/ingest/embed-voyageai.txt
requirements/ingest/notion.txt
requirements/ingest/qdrant.txt
requirements/ingest/singlestore.txt
requirements/ingest/weaviate.txt
requirements/test.txt

build(deps): version bumps for 2024-07-15

---

CHANGELOG.md
unstructured/__version__.py
unstructured/partition/auto.py

**Summary**
Place dispatch to file-type specific partitioners in alphabetical order by file-type to ease scanning and speed up location by scrolling.
No code changes, only block line moves.

rfctr(auto): organize partition() dispatch

---

test_unstructured_ingest/expected-structured-output/box/handbook-1p.docx.json
test_unstructured_ingest/expected-structured-output/box/nested-1/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/box/nested-1/nested-2/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/box/science-exploration-1p.pptx.json
test_unstructured_ingest/expected-structured-output/dropbox/handbook-1p.docx.json
test_unstructured_ingest/expected-structured-output/dropbox/nested-1/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/dropbox/nested-2/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/dropbox/science-exploration-1p.pptx.json
test_unstructured_ingest/expected-structured-output/gcs/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/gcs/nested-1/fake-text.txt.json
test_unstructured_ingest/expected-structured-output/gcs/nested-1/nested/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/gcs/nested-2/fake-text.txt.json
test_unstructured_ingest/expected-structured-output/gcs/nested-2/nested/ideas-page.html.json
test_unstructured_ingest/expected-structured-output/gcs/nested-2/stanley-cups.xlsx.json

feat: save file id for all fsspec connectors if present <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/local-single-file-chunk-no-orig-elements/multi-column-2p.pdf.json

refactor: restructure PDF/Image example document organization <- Ingest test fixtures update

---

CHANGELOG.md
test_unstructured/partition/pdf_image/test_pdf.py
unstructured/__version__.py
unstructured/partition/pdf.py

Added fix related to https://github.com/Unstructured-IO/unstructured/pull/3431, which disables checking max pages for images

fix: disabled checking max pages for images

---

CHANGELOG.md
unstructured/__version__.py
unstructured/ingest/v2/cli/base/cmd.py
unstructured/ingest/v2/cli/base/dest.py
unstructured/ingest/v2/cli/base/src.py
unstructured/ingest/v2/pipeline/pipeline.py

fix typo: pipline>pipeline

---

CHANGELOG.md
test_unstructured/chunking/test_base.py
test_unstructured/common/test_html_table.py
test_unstructured/test_utils.py
typings/lxml/_types.pyi
typings/lxml/etree/_element.pyi
typings/lxml/etree/_module_misc.pyi
typings/lxml/etree/_parser.pyi
typings/lxml/html/__init__.pyi
typings/lxml/html/_parse.pyi
typings/pandas/__init__.pyi
typings/pandas/_typing.pyi
typings/pandas/core/frame.pyi
typings/pandas/io/api.pyi
typings/pandas/io/excel/__init__.pyi
typings/pandas/io/excel/_base.pyi
unstructured/__version__.py
unstructured/chunking/base.py
unstructured/common/html_table.py
unstructured/partition/html/parser.py
unstructured/partition/xlsx.py
unstructured/utils.py

**Summary**
Mechanical refactoring in preparation for adding (pre-chunk) `TableSplitter` in a PR stacked on this one.

rfctr(chunk): prep for adding TableSplitter

---

requirements/extra-paddleocr.txt
requirements/extra-pdf-image.txt
requirements/ingest/chroma.txt
requirements/ingest/embed-aws-bedrock.txt
requirements/ingest/embed-huggingface.txt
requirements/ingest/embed-openai.txt
requirements/ingest/embed-vertexai.txt
requirements/ingest/embed-voyageai.txt
requirements/ingest/github.txt
requirements/ingest/google-drive.txt
requirements/ingest/qdrant.txt
requirements/ingest/weaviate.txt
requirements/test.txt

build(deps): version bumps for 2024-08-26

---

CHANGELOG.md
requirements/dev.in
requirements/dev.txt
unstructured/__version__.py

Removes unnecessary `jupyter` and `ipython` dev dependencies to reduce CVE surface area.

build(deps): removed unnecessary jupyter deps

---

requirements/dev.txt
requirements/extra-pdf-image.txt
requirements/huggingface.txt
requirements/ingest/airtable.txt
requirements/ingest/azure.txt
requirements/ingest/chroma.txt
requirements/ingest/discord.txt
requirements/ingest/elasticsearch.txt
requirements/ingest/embed-aws-bedrock.txt
requirements/ingest/embed-huggingface.txt
requirements/ingest/embed-mixedbreadai.txt
requirements/ingest/embed-octoai.txt
requirements/ingest/embed-openai.txt
requirements/ingest/embed-vertexai.txt
requirements/ingest/embed-voyageai.txt
requirements/ingest/gcs.txt
requirements/ingest/onedrive.txt
requirements/ingest/outlook.txt
requirements/ingest/qdrant.txt
requirements/ingest/s3.txt
requirements/ingest/sharepoint.txt
requirements/ingest/singlestore.txt
requirements/ingest/slack.txt
requirements/test.txt

Dependency bumps for 2024-09-09.

build(deps): bumps for 2024-09-09

---

test_unstructured_ingest/expected-structured-output/azure/Core-Skills-for-Biomedical-Data-Scientists-2-pages.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-api/65/11/main.PMC6312790.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-api/75/29/main.PMC6312793.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-path/07/07/sbaa031.073.PMC7234218.pdf.json
test_unstructured_ingest/expected-structured-output/google-drive/recalibrating-risk-report.pdf.json
test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper.pdf.json
test_unstructured_ingest/expected-structured-output/s3/2023-Jan-economic-outlook.pdf.json
test_unstructured_ingest/expected-structured-output/s3/Silent-Giant-(1).pdf.json
test_unstructured_ingest/expected-structured-output/s3/page-with-formula.pdf.json
test_unstructured_ingest/expected-structured-output/s3/recalibrating-risk-report.pdf.json

feat: improve pdfminer element processing <- Ingest test fixtures update

---

requirements/base.txt
requirements/deps/constraints.txt
requirements/dev.txt
requirements/extra-csv.txt
requirements/extra-markdown.txt
requirements/extra-pdf-image.txt
requirements/extra-xlsx.txt
requirements/huggingface.txt
requirements/ingest/chroma.txt
requirements/ingest/confluence.txt
requirements/ingest/databricks-volumes.txt
requirements/ingest/embed-aws-bedrock.txt
requirements/ingest/embed-huggingface.txt
requirements/ingest/embed-octoai.txt
requirements/ingest/embed-openai.txt
requirements/ingest/embed-vertexai.txt
requirements/ingest/embed-voyageai.txt
requirements/ingest/gcs.txt
requirements/ingest/github.txt
requirements/ingest/google-drive.txt
requirements/ingest/jira.txt
requirements/ingest/onedrive.txt
requirements/ingest/outlook.txt
requirements/ingest/s3.txt
requirements/ingest/salesforce.txt
requirements/ingest/sharepoint.txt
requirements/ingest/singlestore.txt
requirements/test.txt

Remove `langchain-community>=0.2.5` and `wrapt>=1.14.0` pins and add `importlib-metadata>=8.5.0` pin

remove more dependency pins

---

test_unstructured_ingest/expected-structured-output/azure/Core-Skills-for-Biomedical-Data-Scientists-2-pages.pdf.json
test_unstructured_ingest/expected-structured-output/google-drive/recalibrating-risk-report.pdf.json
test_unstructured_ingest/expected-structured-output/s3/recalibrating-risk-report.pdf.json

Fix/reduce memory usage <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/outlook/21be155fb0c95885.eml.json
test_unstructured_ingest/expected-structured-output/outlook/497eba8c81c801c6.eml.json
test_unstructured_ingest/expected-structured-output/outlook/4a16a411f162ebbb.eml.json
test_unstructured_ingest/expected-structured-output/salesforce/EmailMessage/02sHu00001efErPIAU.eml.json
test_unstructured_ingest/expected-structured-output/salesforce/EmailMessage/02sHu00001efErQIAU.eml.json

rfctr(part): remove double-decoration 5 <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/outlook/21be155fb0c95885.eml.json
test_unstructured_ingest/expected-structured-output/outlook/497eba8c81c801c6.eml.json
test_unstructured_ingest/expected-structured-output/outlook/4a16a411f162ebbb.eml.json
test_unstructured_ingest/expected-structured-output/salesforce/EmailMessage/02sHu00001efErPIAU.eml.json
test_unstructured_ingest/expected-structured-output/salesforce/EmailMessage/02sHu00001efErQIAU.eml.json

DO NOT MERGE: CI test run only <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/s3/page-with-formula.pdf.json
test_unstructured_ingest/expected-structured-output/sftp/folder1/folder2/wiki_movie_plots_small2.csv.json
test_unstructured_ingest/expected-structured-output/sftp/folder1/wiki_movie_plots_small.csv.json

feat/remove ingest code, use new dep for tests <- Ingest test fixtures update

---

CHANGELOG.md
test_unstructured/partition/test_auto.py
unstructured/__version__.py

fix(auto): quick fix for auto test failing in CI

---

test_unstructured_ingest/expected-structured-output/outlook/21be155fb0c95885.eml.json
test_unstructured_ingest/expected-structured-output/outlook/497eba8c81c801c6.eml.json
test_unstructured_ingest/expected-structured-output/outlook/4a16a411f162ebbb.eml.json

rfctr(email): eml partitioner rewrite <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/s3/Silent-Giant-(1).pdf.json

rfctr(csv): minify HTML and table text is cct <- Ingest test fixtures update

---

CHANGELOG.md
requirements/base.txt
requirements/extra-paddleocr.txt
requirements/extra-pdf-image.in
requirements/extra-pdf-image.txt
requirements/extra-xlsx.txt
requirements/test.txt
unstructured/__version__.py

- bump version to 0.16.3 based on Pluto's fix on layout parsing
- update unstructured-inference version to 0.8.1 in requirement/extra-pdf-image

release: version 0.16.3 

---

test_unstructured_ingest/expected-structured-output/biomed-api/65/11/main.PMC6312790.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-api/75/29/main.PMC6312793.pdf.json
test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper.pdf.json
test_unstructured_ingest/expected-structured-output/s3/page-with-formula.pdf.json

feat: support pdf link extraction in hi_res strategy <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/local-single-file-basic-chunking/handbook-1p.docx.json
test_unstructured_ingest/expected-structured-output/s3/page-with-formula.pdf.json

chunk: relax table segregation during chunking <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/google-drive/fake.docx.json
test_unstructured_ingest/expected-structured-output/google-drive/nested/fake.docx.json
test_unstructured_ingest/expected-structured-output/google-drive/recalibrating-risk-report.pdf.json
test_unstructured_ingest/expected-structured-output/google-drive/test-drive-doc.docx.json
test_unstructured_ingest/expected-structured-output/s3/Silent-Giant-(1).pdf.json
test_unstructured_ingest/expected-structured-output/s3/page-with-formula.pdf.json

fix: improve false-positive Title elements on Chinese text <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/outlook/21be155fb0c95885.eml.json
test_unstructured_ingest/expected-structured-output/outlook/497eba8c81c801c6.eml.json
test_unstructured_ingest/expected-structured-output/outlook/4a16a411f162ebbb.eml.json

chore: dependency bumps <- Ingest test fixtures update

---

scripts/user/unstructured-get-json.sh

E.g., now can run:
```bash
$ unstructured-get-json.sh --trace --verbose --images /t/docs/Captur-1317-5_ENG-p5.pdf
$ IMAGE_BLOCK_TYPES='"title","table","image"' unstructured-get-json.sh --trace --verbose --images /t/docs/Captur-1317-5_ENG-p5.pdf
```
It was discovered during testing that "narrativetext" does not work, probably due to camel casing of NarrativeText 😬

feat: add --images support to unstructured-get-json.sh 

---

CHANGELOG.md
unstructured/__version__.py

small minor version change to trigger workflows. and fix the open CVEs we had.

minor bump to resolve open CVEs

---

test_unstructured_ingest/expected-structured-output/azure/Core-Skills-for-Biomedical-Data-Scientists-2-pages.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-api/65/11/main.PMC6312790.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-api/75/29/main.PMC6312793.pdf.json
test_unstructured_ingest/expected-structured-output/google-drive/recalibrating-risk-report.pdf.json
test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper.pdf.json

[wip] Feat/supplement inferred with extracted <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/google-drive/fake.docx.json
test_unstructured_ingest/expected-structured-output/google-drive/nested/fake.docx.json
test_unstructured_ingest/expected-structured-output/google-drive/recalibrating-risk-report.pdf.json
test_unstructured_ingest/expected-structured-output/google-drive/test-drive-doc.docx.json
test_unstructured_ingest/expected-structured-output/jira-diff/1/10000.json
test_unstructured_ingest/expected-structured-output/jira-diff/JCTP2/10009.json

feat: allow extraction of camel cased element type names <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/1605956.json
test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/229477.json
test_unstructured_ingest/expected-structured-output/confluence-diff/testteamsp/1605859.json
test_unstructured_ingest/expected-structured-output/confluence-diff/testteamsp/1605989.json
test_unstructured_ingest/expected-structured-output/confluence-diff/testteamsp/1802252.json
test_unstructured_ingest/expected-structured-output/notion/c47a4566-4c7a-488b-ac2a-1292ee507fcb.json
test_unstructured_ingest/expected-structured-output/salesforce/EmailMessage/02sHu00001efErPIAU.eml.json
test_unstructured_ingest/expected-structured-output/salesforce/EmailMessage/02sHu00001efErQIAU.eml.json

feat: include images when partitioning html <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/1605956.json
test_unstructured_ingest/expected-structured-output/confluence-diff/MFS/229477.json
test_unstructured_ingest/expected-structured-output/confluence-diff/testteamsp/1605859.json
test_unstructured_ingest/expected-structured-output/confluence-diff/testteamsp/1605989.json
test_unstructured_ingest/expected-structured-output/confluence-diff/testteamsp/1802252.json
test_unstructured_ingest/expected-structured-output/notion/c47a4566-4c7a-488b-ac2a-1292ee507fcb.json
test_unstructured_ingest/expected-structured-output/salesforce/EmailMessage/02sHu00001efErPIAU.eml.json
test_unstructured_ingest/expected-structured-output/salesforce/EmailMessage/02sHu00001efErQIAU.eml.json

feat: support extracting image url in html <- Ingest test fixtures update

---

test_unstructured_ingest/expected-structured-output/biomed-api/65/11/main.PMC6312790.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-api/75/29/main.PMC6312793.pdf.json
test_unstructured_ingest/expected-structured-output/biomed-path/07/07/sbaa031.073.PMC7234218.pdf.json
test_unstructured_ingest/expected-structured-output/google-drive/recalibrating-risk-report.pdf.json
test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper-with-table.jpg.json
test_unstructured_ingest/expected-structured-output/local-single-file-with-pdf-infer-table-structure/layout-parser-paper.pdf.json

fix: hi_res PDF parsing: only uncategorized text for extracted elements <- Ingest test fixtures update

---

.github/workflows/docker-publish.yml
scripts/docker-smoke-test.sh

Successful build and test: https://github.com/Unstructured-IO/unstructured/actions/runs/14730300234/job/41342657532
Failing test_json_to_html CI job fix here: https://github.com/Unstructured-IO/unstructured/pull/3992

fix: failing build

---

test_unstructured_ingest/expected-structured-output/local-single-file-with-encoding/fake-html-cp1252.html.json
test_unstructured_ingest/expected-structured-output/pdf-fast-reprocess/azure/Core-Skills-for-Biomedical-Data-Scientists-2-pages.pdf.json

feat: detect language for PDFs <- Ingest test fixtures update

---

scripts/sync_fork.sh

From the base folder of this repo, run:
```bash
./scripts/sync_fork.sh git@github.com:aseembits93/unstructured.git optimize-_assign_hash_ids-memtfran
```
Check to make sure the only remote is `origin` with:
```bash
git remote
```
Check the diff from `main` with:
```bash
git diff main
```

feat: Add simple script to sync fork with local branch
